### ISSUE TITLE
chrome app不小心删掉了，能自己再建一个吗

### ISSUE THREAD

**Issue by wangyingbo** [hectorqin/reader#100]

**Comment by hectorqin** [comment]
可以，那是pwa模式，可以随时删除重建的，大部分数据都在服务器上，只有一些阅读配置等是在本地浏览器的

**Comment by wangyingbo** [comment]
> 可以，那是pwa模式，可以随时删除重建的，大部分数据都在服务器上，只有一些阅读配置等是在本地浏览器的

手机上我知道可以。Mac上怎么创建呢？

**Comment by hectorqin** [comment]
<img width="744" alt="image" src="https://user-images.githubusercontent.com/14220132/168458863-58211672-fc81-4c8d-bfb4-d0d4ee12d2e6.png">

地址栏右侧

**Comment by wangyingbo** [comment]
> <img alt="image" width="744" src="https://user-images.githubusercontent.com/14220132/168458863-58211672-fc81-4c8d-bfb4-d0d4ee12d2e6.png">
> 
> 地址栏右侧

感谢感谢~可以了
