### ISSUE TITLE
最新本docker版的不能后台播语音

### ISSUE THREAD

**Issue by rickthun5941** [hectorqin/reader#101]
前一个版本还是可以使用,更新以后发现无法后台播放云语音或者ssr的音频,这个功能是被切割了吗

**Comment by hectorqin** [comment]
云语音或者ssr的音频？是指音频源吗？这个最近没有改过哦，后台播放受浏览器限制的

**Comment by rickthun5941** [comment]
> 云语音或者ssr的音频？是指音频源吗？这个最近没有改过哦，后台播放受浏览器限制的

云语音和音频源都是没法后台播放,浏览器safari和chrome都不行

**Comment by rickthun5941** [comment]
> 云语音或者ssr的音频？是指音频源吗？这个最近没有改过哦，后台播放受浏览器限制的

原来是添加到主屏幕后就不能后台播放了😅
