### ISSUE TITLE
求每个用户可以有自己的webdav空间，

### ISSUE THREAD

**Issue by onlypeng** [hectorqin/reader#103]
求每个用户存在自己的webdav空间，或加入webdav功能，能指向阅读app的webdav备份路径，以另一种方法跟阅读app数据同步

**Comment by hectorqin** [comment]
这个功能是有的，我的公众号上有关于 WebDAV功能 的教程

https://mp.weixin.qq.com/s?__biz=MjM5MzMyMDgyMA==&mid=2249483683&idx=1&sn=0f9bb1b0c84d94c9d7bd11995c031012
