### ISSUE TITLE
切换源的时候碰到错误

### ISSUE THREAD

**Issue by wisteria66** [hectorqin/reader#105]
![fbb85992faa309918ef22b8f1997b1b](https://user-images.githubusercontent.com/105471343/168559198-5bf5dea3-f8d1-4d2c-8707-4e110c1e06a8.png)

**Comment by hectorqin** [comment]
这个要提供一下接口日志

**Comment by wisteria66** [comment]
请问大佬接口日志怎么查啊

**Comment by hectorqin** [comment]
storage/logs 目录

**Comment by wisteria66** [comment]
我是在电脑上用，请问这个目录具体在哪个位置？

**Comment by hectorqin** [comment]
mac 在 ~/.reader/logs，其它的在程序目录

**Comment by wisteria66** [comment]
大佬，我用Koyeb 免费搭建的是一个阅读网页版，这个就是个网址，哪里去找程序目录啊，小白太难了，我把网址附上：yuedu-wisteria163.koyeb.app/，大佬你看看吧，实在是搞不明白了





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hectorqin/reader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月18日(星期三) 上午8:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hectorqin/reader] 切换源的时候碰到错误 (Issue #105)



 mac 在 ~/.reader/logs，其它的在程序目录

**Comment by hectorqin** [comment]
所有书源都不行吗？

**Comment by hectorqin** [comment]
没开启多用户模式还是不要把链接发上来了，换源问题一般是源的问题，使用其它书源看看吧

**Comment by wisteria66** [comment]
好的，放弃挣扎了，以后再说吧





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hectorqin/reader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月18日(星期三) 下午5:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hectorqin/reader] 切换源的时候碰到错误 (Issue #105)



 没开启多用户模式还是不要把链接发上来了，换源问题一般是源的问题，使用其它书源看看吧

**Comment by hectorqin** [comment]
是的，这个是日志

**Comment by wisteria66** [comment]
大佬，我觉得我这个问题其实是书源导入后非常容易被清理，可能是搜索后加入书架阅读时想换源书源就不在了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hectorqin/reader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月19日(星期四) 上午8:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hectorqin/reader] 切换源的时候碰到错误 (Issue #105)



 是的，这个是日志

**Comment by hectorqin** [comment]
是的，我之前试过了，不知道为啥数据老是被清理了，是不是别人在用你的地址？

**Comment by wisteria66** [comment]
不是这个原因，之前那个地址我已经删掉了，换了个新的地址，但是还是同样的情况，而且书源被清理用不了了，但是书源管理里面还是可以看到那些书源，反应比较滞后




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hectorqin/reader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月20日(星期五) 上午8:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hectorqin/reader] 切换源的时候碰到错误 (Issue #105)



 是的，我之前试过了，不知道为啥数据老是被清理了，是不是别人在用你的地址？

**Comment by hectorqin** [comment]
web页面的书源、RSS源等默认是读取本地缓存的

**Comment by wisteria66** [comment]
明白了，大佬你啥时再搞个网址让我加加进去，每次重来挺烦的，书架也不见了





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hectorqin/reader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月20日(星期五) 上午9:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hectorqin/reader] 切换源的时候碰到错误 (Issue #105)



 web页面的书源、RSS源等默认是读取本地缓存的

**Comment by hectorqin** [comment]
demo服务器目前还有空位

**Comment by wisteria66** [comment]
谢谢大佬，我进去了，搞定了！

发自我的iPhone

**Comment by wisteria66** [comment]
是的，就是每次我先导入书源，然后搜索书籍加入书架，之后阅读的时候切换源就会错误，之后就变成书源不存在，每次都这样，不知道哪里有问题。我看到有人说用这种方式搭建的话存在一种问题就是数据会被清理，不知道是不是这个原因，但是我也太迅速了，几分钟就不行了。








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hectorqin/reader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月18日(星期三) 下午5:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hectorqin/reader] 切换源的时候碰到错误 (Issue #105)



 所有书源都不行吗？
