### ISSUE TITLE
过滤规则不识别换行"\n"

### ISSUE THREAD

**Issue by Meng-X-G** [hectorqin/reader#106]
例如这个规则就是不生效的 
{
        "name": "文本替换",
        "pattern": "。\n。",
        "replacement": "。\n",
        "scope": "XXXX;https://XXXXXX"
    }

**Comment by hectorqin** [comment]
替换规则优化了一版，可以试试

**Comment by hectorqin** [comment]
使用正则的话，转移符号应该要转义一下，`\\n`，自己测试一下吧

```js
content.replace(
  new RegExp(rule.pattern),
  rule.replacement
);
```

**Comment by Meng-X-G** [comment]
还是不行，试了好几本书，都是不生效
![image](https://user-images.githubusercontent.com/49837258/170004042-379e565c-f604-41ef-a47b-bca7bbeb7b73.png)

**Comment by hectorqin** [comment]
正则问题，自己多测试测试吧

**Comment by zml9640** [comment]
解决了吗？用edge听书的时候遇到换行，间隔时间太长了，要是能净化换行就好了

**Comment by zml9640** [comment]
@Meng-X-G 
![微信截图_20220529212815](https://user-images.githubusercontent.com/67811948/170872680-b74de5e9-0ca7-46f2-9d4c-92296551169f.jpg)
换行解决了吗，1到2之间的换行怎么净化掉

**Comment by Meng-X-G** [comment]
![image](https://user-images.githubusercontent.com/49837258/171105170-e310cec1-b5aa-4281-9d6f-f519528a06f9.png)
![image](https://user-images.githubusercontent.com/49837258/171105264-27782453-098b-4cf3-9008-2dbe16e6e7e3.png)
![image](https://user-images.githubusercontent.com/49837258/171106050-71d80140-7219-48a5-899f-e2db517dafcf.png)
目前还是无解，我自己在网页上测试没问题，但是在阅读里测试的时候只匹配第一个，剩下的就不匹配了。
不知道是我的正则有问题，还是bug。

**Comment by zml9640** [comment]
我试了你这个正则，在源阅读是可行的，但是这里是不行的，所以应该还是这个的bug @Meng-X-G

**Comment by zml9640** [comment]
现在找了个笨办法，把小说下载下来，再把换行去掉，然后本地导入

**Comment by Meng-X-G** [comment]
![image](https://user-images.githubusercontent.com/49837258/171616607-4c8d082b-ee40-41b7-a204-e143a10feb44.png)
更新到这个版本后，已经没问题了，感谢
