### ISSUE TITLE
fork后的项目，fetch and merge 原仓库后，railway自动部署后，阅读记录，书架，书源都清空了

### ISSUE THREAD

**Issue by wangyingbo** [hectorqin/reader#111]
如题，fork后的项目，fetch and merge 原仓库的近期修改后，railway触发trigger自动部署后，阅读记录，书架，书源都清空了。railway上重新部署项目会清空本地数据库吗？如果后期时间长了想同步一下原仓库的最新代码，可能旧的记录就没了，辛苦作者看一下，感恩

**Comment by wangyingbo** [comment]
fix by myself

**Comment by hectorqin** [comment]
麻烦在这里分享一下解决方案，谢谢

**Comment by nihilvs0** [comment]
> 麻烦在这里分享一下解决方案，谢谢

没找到设置volume的方法. 
要不将数据改为数据库存储? 或者将本服务作为webdav的客户端,, 数据存储到第三方webdav服务器

**Comment by hectorqin** [comment]
这个比较难，也很慢

**Comment by nihilvs0** [comment]
> 这个比较难，也很慢

异步同步就可以   最多同步失败缺失一小部分数据, 不过本地上传书籍也同步需要过去, 对第三方webdav流量消耗比较大.

要不支持下载数据? 在重新部署前手动备份一份到本地, 部署完后再上传还原, 或者支持手动备份到第三方webdav也行, 就是使用起来麻烦了点

**Comment by nihilvs0** [comment]
感觉最好还是支持数据库存储吧

**Comment by RouJiANG-14** [comment]
> fix by myself

怎么处理的，能告知一下么？？

**Comment by SeanRao** [comment]
> fix by myself

所以要怎么解决呢，能指教一下吗

**Comment by Ecalose** [comment]
这里给个思路，用rclone将对应目录进行同步

**Comment by wangyingbo** [comment]
> > fix by myself
> 
> 所以要怎么解决呢，能指教一下吗

我是用的onedrive做的整个目录的同步的同步.

**Comment by duhd1993** [comment]
这种PaaS服务一般都是stateless的，最好把数据存储从本地文件，改到数据库，这样就可以利用一些免费的数据库服务保存状态。但就需要大改了。

**Comment by hectorqin** [comment]
改用数据库的话，工作量就太大了，而且涉及到本地书籍也是无解。使用文件系统，结构一目了然，方便用户自行修改

**Comment by hectorqin** [comment]
新版支持设置 mongoUrl 来保存书源等数据到mongodb。

**Comment by hectorqin** [comment]
但是本地书籍、书籍缓存等数据是不会保存到mongodb的
