### ISSUE TITLE
Booksources can't be imported & After the import is successful, it still shows no book source when opened on other devices

### ISSUE THREAD

**Issue by HelloMusician** [hectorqin/reader#113]
Booksources can't be imported & After the import is successful, it still shows no book source when opened on other devices.

I imported the book source (5.6M) of the icebreaker, and it shows that the import failed, and the import can be successful after checking some of them. So what is the maximum number of book sources that can be imported at one time? In addition, after importing the book source on one device, the import needs to be repeated on other devices. Is this my problem or is it just like this?

Devices：Ipad mini4(ios15), windows 10 64bit, andriod 11

**Comment by hectorqin** [comment]
书源导入一次就行了，建议不要导入太多书源，会影响搜书速度。
web页面会缓存书源数据，如果书源未更新，需要点击 `书源管理 - 缓存书源` 来刷新缓存

**Comment by HelloMusician** [comment]
谢谢大佬！

hector ***@***.***> 于2022年5月23日周一 10:42写道：
