### ISSUE TITLE
docker版本

### ISSUE THREAD

**Issue by BaiBaiAi** [hectorqin/reader#116]
内存占用越来越大

**Comment by hectorqin** [comment]
访问  `http://ip:端口/reader3/getSystemInfo` 看看内存占用信息

**Comment by jacklaplace** [comment]
666，居然自带如此强大的功能。

我用的docker版本v2.2.2-05290917，刚刚部署好，仅导入13本txt小说，内存如下：

{"isSuccess":true,"errorMsg":"","data":{"freeMemory":"81M","totalMemory":"310M","maxMemory":"875M"}}

**Comment by skyofwing** [comment]
> 实际占用内存是 310 - 81 = 230M 如果觉得内存占用太大，可以用 openj9 的镜像，只是镜像比较大

 为啥我的占用这么大 T_T
{"isSuccess":true,"errorMsg":"","data":{"freeMemory":"3878M","totalMemory":"6734M","maxMemory":"14233M","dayRegisterUser":0,"dayLoginUser":1,"sevenDayRegisterUser":0,"sevenDayLoginUser":1,"monthRegisterUser":1,"monthLoginUser":1,"keepUser":1}}
