### ISSUE TITLE
段落间的换行怎么净化掉

### ISSUE THREAD

**Issue by zml9640** [hectorqin/reader#117]
就是用edge浏览器听书的时候，遇到段落的间隔时间有点长，想替换成标点符号或在干脆直接去掉

**Comment by hectorqin** [comment]
从网络请求里面提供一下 章节内容

**Comment by zml9640** [comment]
![微信截图_20220529212815](https://user-images.githubusercontent.com/67811948/170872058-ba638a16-8786-4e40-b9b0-927cbc32d474.jpg)
点下一章的时候，小标题不会变，而且用edge听书的时候两个标题都会重复朗读，建议把小标题去掉，还有用edge听书，1到2这个段落间的时间有点长，能不能把段落净化掉，直接一章就一个段落

**Comment by hectorqin** [comment]
暂时不考虑针对某一个浏览器做特殊优化，如果需要的人很多，那再评估

**Comment by zml9640** [comment]
这个不是浏览器的问题，用这个"。([\w\W]*?)\n"  再源阅读是可以常替换的，阅读3没试过，应该是可以的

**Comment by hectorqin** [comment]
试试这个 `[\r\n]*`

**Comment by zml9640** [comment]
问题解决，感谢！！
