### ISSUE TITLE
请问不能自定义字体吗？

### ISSUE THREAD

**Issue by Morax-xyc** [hectorqin/reader#122]
没看到自定义字体的选项，而且选择字体也没反应，一直都是系统浏览器的字体而非选择的字体

**Comment by lmingzhi** [comment]
电脑上浏览器可以生效，手机浏览器不起作用

**Comment by hectorqin** [comment]
手机浏览器没有内置那些字体，所以不会生效

**Comment by Morax-xyc** [comment]
通过css的方式内置字体呢？

**Comment by hectorqin** [comment]
字体文件太大，暂时不考虑加载网络字体

**Comment by Morax-xyc** [comment]
> 字体文件太大，暂时不考虑加载网络字体

通过这个[webfontloader](https://github.com/typekit/webfontloader)可以异步加载，是否能通过这个以优化网络字体加载？

还有，PWA应用的离线机制应该可以做到一次加载后只需本地调用吧？

（我不是很懂前端，如果实在不行就算了）

**Comment by hectorqin** [comment]
我看看

**Comment by viewfirst** [comment]
我注意到阅读界面其实有部分内置字体的。那么能否设置允许单个用户自行上传字体到DOCKER或者服务器端，然后绑定到其用户配置中提供全平台显示？

**Comment by hectorqin** [comment]
没找到合适的字体文件，我也没法测试开发，所以暂时搁置
