### ISSUE TITLE
为啥 Railway创建新项目提示账户未验证

### ISSUE THREAD

**Issue by erzong210** [hectorqin/reader#123]
![image](https://user-images.githubusercontent.com/106464390/170857519-d137c1fc-aabb-4b39-ac82-18fd829c0599.png)

**Comment by hectorqin** [comment]
看右下角的提示吧，具体我也没试过

**Comment by wisteria66** [comment]
我也碰到过，原因是因为账号太新，Railway 限制是要求 Github 账号注册满180天

**Comment by wisteria66** [comment]
没有办法，等180天吧

发自我的iPhone

**Comment by wisteria66** [comment]
免费的就是坑，我用koyeb更坑，看了没一会书源就被清了，阅读界面变成找不到书源，要继续看的话只能重新导入书源重新搜索书籍

发自我的iPhone

**Comment by Neo2077** [comment]
。。。。。。。。。。。。180天
