### ISSUE TITLE
ipad版edge访问reader无法调用浏览器“大声朗读”进兴朗读。

### ISSUE THREAD

**Issue by kelven1217** [hectorqin/reader#124]
其他网页没问题，不知道是什么原因导致？而reader集成得朗读功能不能在ipad得edge里使用新得neural系列朗读角色如xiaoxiaoneural等，只有传统得几个声音（婷婷等），感觉声音比较死板，希望改进下。

**Comment by kelven1217** [comment]
PC版edge上面所述功能都是正常得。
![](https://s3.bmp.ovh/imgs/2022/05/29/4452c3a3904e4370.png)

**Comment by kelven1217** [comment]
而ipad上得edge是这样得：（直接用浏览器得大声朗读功能也无效）
![](https://s3.bmp.ovh/imgs/2022/05/29/98304a0c27a2f87d.jpg)

**Comment by zml9640** [comment]
我是直接调浏览器的朗读，但是一直是读两个标题，而且标题还不一样，希望把第1个小标题去掉

**Comment by kelven1217** [comment]
> 我是直接调浏览器的朗读，但是一直是读两个标题，而且标题还不一样，希望把第1个小标题去掉
@zml9640  你有用IPAD版edge试过吗？我直接调用大声朗读连声音都没有。

**Comment by zml9640** [comment]
有声音的，我不知道怎么传图片上来

**Comment by kelven1217** [comment]
> 有声音的，我不知道怎么传图片上来

@zml9640  https://www.imgurl.org/ 用这个图床然后复制markdown代码上来就可以了。奇怪我在ipad上得edge是没办法直接用浏览器得大声朗读得，内置是可以出声但是只有婷婷这些老得声音。

**Comment by zml9640** [comment]
![Uploading 7830406a62463cf737648f93dc622f9.png…]()

**Comment by zml9640** [comment]
![7830406a62463cf737648f93dc622f9](https://user-images.githubusercontent.com/67811948/170870822-47d88802-5518-42e9-aca2-dc34e7270866.png)

**Comment by zml9640** [comment]
新版本的edge有时候就是不好用，建议用46.3这个版本，听书的话比新版本好，你可以试试46.3.26这个版本

**Comment by kelven1217** [comment]
> 新版本的edge有时候就是不好用，建议用46.3这个版本，听书的话比新版本好，你可以试试46.3.26这个版本

iPad还能用老版本？

**Comment by zml9640** [comment]
可以啊，在爱思助手就能装老版本的，我是自己抓包的 @kelven1217

**Comment by kelven1217** [comment]
> 可以啊，在爱思助手就能装老版本的，我是自己抓包的 @kelven1217 

那你看看能不能调用晓晓这些基于神经网络的声音

**Comment by zml9640** [comment]
![微信截图_20220529212815](https://user-images.githubusercontent.com/67811948/170871300-1d31c10b-eb9d-4b95-b04c-57bf74948291.jpg)
我就是这个版本的，可以用的
![微信截图_20220529212948](https://user-images.githubusercontent.com/67811948/170871378-fd47d5ac-b1da-4e9f-827a-d5215cc75aa1.jpg)

**Comment by zml9640** [comment]
但是这样会先读旁边的书架，书源很烦人，我是有个5s手机越狱，用按键精灵写个脚本，实现自动化下一章，但是有个小标题每次都重复，还不更新

**Comment by zml9640** [comment]
![微信截图_20220529212948](https://user-images.githubusercontent.com/67811948/170871735-37262fc4-ac18-4c90-94e3-275698186b0c.jpg)
就像这样，小标题不会自动更新，非要刷新才会自动更新，而且听书的话，会两个标题都读 @kelven1217

**Comment by kelven1217** [comment]
> ![微信截图_20220529212948](https://user-images.githubusercontent.com/67811948/170871735-37262fc4-ac18-4c90-94e3-275698186b0c.jpg)
> 就像这样，小标题不会自动更新，非要刷新才会自动更新，而且听书的话，会两个标题都读 @kelven1217 

明白了 哈哈，你这算小问题。

**Comment by kelven1217** [comment]
@zml9640 

![](https://s3.bmp.ovh/imgs/2022/05/29/974502f336b7b2b2.jpg)
你点这个按钮能调用xiaoxiao吗

**Comment by zml9640** [comment]
这里不行，必须浏览器里面调用 ，经常用的话建议越狱，然后用按键精灵或者别的软件实现自动化

**Comment by zml9640** [comment]
![微信截图_20220529212815](https://user-images.githubusercontent.com/67811948/170872410-9edd4c0c-982f-48ec-8278-b704a853811a.jpg)
edge听书，1到2这个段落间的时间有点长，能不能把段落净化掉，直接一章就一个段落 @kelven1217

**Comment by hectorqin** [comment]
> ![微信截图_20220529212815](https://user-images.githubusercontent.com/67811948/170872410-9edd4c0c-982f-48ec-8278-b704a853811a.jpg) edge听书，1到2这个段落间的时间有点长，能不能把段落净化掉，直接一章就一个段落 @kelven1217

使用 [\r\n]* 净化
