### ISSUE TITLE
自动滚动，像素滚动，平滑滚动

### ISSUE THREAD

**Issue by jacklaplace** [hectorqin/reader#125]
油猴脚本： AutoScroll by OscarKoo
安装链接： https://greasyfork.org/users/11909
使用效果： 双击屏幕，小说开始自动滚动，类似鼠标滚轮和中键滚动功能，再双击左键，滚动停止。

代码看着很简单，如下，还可以自行修改数字，控制滚动速度，以下是我使用的全部代码：

;(function(document) {
  var enable = false;
  var handler = 0;

  var dbclick = function() {
    enable = !enable;
    clearTimeout(handler);
    if (enable) aScroll();
  };

  document.body.removeEventListener('dblclick', dbclick);
  document.body.addEventListener('dblclick', dbclick);

  var aScroll = function() {
    if (enable) document.documentElement.scrollTop += 1;
    handler = setTimeout(aScroll, 20);
  };
})(document);

请问一下，这个功能能否添加到docker的程序里？
（因为我的个别设备不能使用chrome浏览器）

**Comment by hectorqin** [comment]
这个滚动看着不会很累吗

**Comment by jacklaplace** [comment]
不会累啊，电脑看文档、网页、论文，习惯滚轮滚动了，均速滚动；反而是内置那个功能像歌词秀，或者提词器一样，按段落大小进行滚动，第一次用不习惯，哈哈哈。

按人体工学来看，均速滚动，眼球要一直跟踪动态的文字，而提词器滚动差不多是静态的，前者应该比后者累一点和费眼睛，但我想说的是，后者按段落大小进行滚动，长的段落一下子向上滚过去一百个字，小段落则滚过去一行两行的，这个滚动的速度和间隔时间没规律性啊，我预判不足的话，眼睛就把握不住我是要看快一点呢，还是放慢一点看，特别是长段落和短段落交替的时候。均速滚动的话，速度是一个定量，眼睛就知道保持一个什么样的浏览速度就行。

所以提词器滚动，比较适合一些简单的、不长的段落，比如歌词，当遇到长度相差大的段落，它每一次滚动的时间间隔就不一样。

**Comment by hectorqin** [comment]
v2.3.0 已添加

**Comment by jacklaplace** [comment]
docker更新了 image latest，已经有像素滚动的功能了，大佬牛啤！

个人感觉，像素为1的时候为平滑滚动，大于1那是跳动了，
所以大于1好像没啥意义，姑且留着这个功能吧，也许别人需要呢。

滚动最快速度是50，不够快啊，能否调到20啊？

个人原因，我电脑是调到最大的60字体，滚动速度50还是不够快，所以希望字体能最大调到80，滚动速度最快能到10，而且是一个单位一个单位来递增递减。对了，卧室我用的电视机看小说呢。

其实我还有一个想说的，数字那个位置，能否设置为可输入状态，而不是只能靠点击加号减号。当然，加号减号还是要保留的，只是建议可以直接输入数字更好，最大字体80，最快速度为10，我给每个设备更改的时候就更方便了。

至于延伸的保存个人阅读模式方案，保存为方案1，方案2，就像Windows的主题一样，各个设备即点即用、即开即同步，留待以后以后吧。

以上，谢谢作者孜孜不倦敲代码带来的佳作！

**Comment by jacklaplace** [comment]
最新 v2.3.0-06280925

滚动像素，点击数字可以直接输入数字，其他的比如翻页速度，点击数字都不可以更改呀，翻页速度最快还是50，大佬能否调到20啊？

新功能，配置方案-新增方案，我使用了一下，发现和阅读主题-自定义一样，都是仅保存在浏览器本机里的设置，并不是保存到nas-docker的设置里，因此不同的设备间还是无法直接同步阅读方案、阅读主题。

谢谢作者更新新功能！

**Comment by jacklaplace** [comment]
好的收到，原来是这么用的。

其他的功能慢慢来，能打开，能像其他app一样个性化看小说，已经很奈斯了。至于管理书架，排后面再说，现在也是可以管理的，只不过是一个个去点，不能批量管理。瑕不掩瑜，大佬辛苦了。

**Comment by jacklaplace** [comment]
你也太勤快了，刚刚测试最新版，v2.4.0-06300937

首页左侧“书籍管理”里边可以全选，进行删除之类的操作了

像素滚动，滚动速度那里，抽空设置最快为20啊，现在只能到50就不能调了，还有字体最大60，建议到80

**Comment by jacklaplace** [comment]
效率太高了！完美！感谢！
