### ISSUE TITLE
树莓派arm64位系统启动报错

### ISSUE THREAD

**Issue by rayv0705** [hectorqin/reader#127]
报错如下:
Loading library prism_sw from resource failed: java.lang.UnsatisfiedLinkError: /root/.openjfx/cache/11.0.2/libprism_sw.so: /root/.openjfx/cache/11.0.2/libprism_sw.so: 无法打开共享对象文件: 没有那个文件或目录 (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)
java.lang.UnsatisfiedLinkError: /root/.openjfx/cache/11.0.2/libprism_sw.so: /root/.openjfx/cache/11.0.2/libprism_sw.so: 无法打开共享对象文件: 没有那个文件或目录 (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)

**Comment by hectorqin** [comment]
试试 openj9 的镜像
