### ISSUE TITLE
epub 字体相关问题

### ISSUE THREAD

**Issue by Tompkins-liu** [hectorqin/reader#128]
本地导入的epub文件无法调整“正文字体”、“字体大小”和“段落间距”。在IOS中，字体过小

版本：docker-compose 多用户 v2.2.2-05310144

**Comment by jacklaplace** [comment]
同版本，chrome测试epub，的确无法调整字体大小，也不能调正文背景色，点击黑夜模式正文也不生效。

**Comment by hectorqin** [comment]
epub是一个网页，字体大小是设置在 body 上的，如果body里面的元素定义了字体大小，那就会被覆盖

**Comment by hectorqin** [comment]
新版优化了一些，试试看
