### ISSUE TITLE
希望可以完善接口文档的支持

### ISSUE THREAD

**Issue by wapscccs** [hectorqin/reader#13]
希望可以尽快完善接口文档，很多接口文档现在都还是很清晰，非常感谢
其次还有一个小问题，当我复制一大段json书源时系统总是提示我这不是json格式
@hectorqin

**Comment by wapscccs** [comment]
类似下面的书源无法导入，提示必须是json格式

`

 

    {
        "bookSourceComment": "搜索用的是百度站内搜索",
        "bookSourceGroup": "🎉 精品,百度搜",
        "bookSourceName": "🎉 落秋中文网📱",
        "bookSourceType": 0,
        "bookSourceUrl": "https:\/\/h.lqbook.com",
        "bookUrlPattern": "",
        "concurrentRate": "",
        "customOrder": -88897993,
        "enabled": true,
        "enabledExplore": true,
        "exploreUrl": "完本::\/full\/{{page}}.html\n玄幻::\/list\/1_{{page}}.html\n修真::\/list\/2_{{page}}.html\n都市::\/list\/3_{{page}}.html\n历史::\/list\/4_{{page}}.html\n网游::\/list\/5_{{page}}.html\n科幻::\/list\/6_{{page}}.html",
        "header": "{\n  \"User-Agent\": \"Mozilla\/5.0 (Linux; Android 8.0.0; Pixel 2 XL Build\/OPD1.170816.004) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/85.0.4183.121 Mobile Safari\/537.36 Edg\/85.0.564.68\"\n}",
        "lastUpdateTime": 1640061329341,
        "loginCheckJs": "",
        "loginUi": "",
        "loginUrl": "",
        "respondTime": 6036,
        "ruleBookInfo": {
            "author": "class.info@tag.a.0@text",
            "coverUrl": ".bookinfo@img@src",
            "intro": ".intro@text",
            "kind": "class.info@tag.a.1@text&&class.info@tag.p.2@text&&class.info@tag.p.3@text##状态：|更新：|\\s.*",
            "lastChapter": "class.info@tag.a.2@text",
            "name": "class.info@h1@text##\\\/.*",
            "tocUrl": "text.章节目录@href||.more@href"
        },
        "ruleContent": {
            "content": "id.nr1@all",
            "nextContentUrl": "text.下一页@href",
            "replaceRegex": "##落秋中文.*|最新章节！|... -->>|本章未完，点击下一页继续阅读"
        },
        "ruleExplore": {
            "author": ".mr15@text",
            "bookList": ".list-item",
            "bookUrl": "a.0@href",
            "coverUrl": "img@src",
            "intro": ".article@a@span@text",
            "name": ".article@a.0@text"
        },
        "ruleSearch": {
            "author": "",
            "bookList": "#results .c-result",
            "bookUrl": "data-log\n@js:\n\/\/java.log(result);\njson=eval(\"(\"+result+\")\");\njson.mu.replace(\/www\/g,\"h\");",
            "coverUrl": "",
            "intro": "div[role=\"text\"]@span.1@text",
            "kind": "",
            "lastChapter": ".c-text-line-text.0@text",
            "name": ".c-title-text@text##最新章节.*"
        },
        "ruleToc": {
            "chapterList": ".even@a",
            "chapterName": "text",
            "chapterUrl": "href",
            "nextTocUrl": "text.下一页@href"
        },
        "searchUrl": "https:\/\/m.baidu.com\/s?wd=site:lqbook.com {{key}},{\"webView\":true}",
        "weight": 0
    }

`

**Comment by hectorqin** [comment]
我这边测试使用demo服务添加这个书源是正常的哦，有没有错误截图？

**Comment by wapscccs** [comment]
> 我这个截图测试使用demo服务添加这个书源是正常的哦，有没有错误？

非常抱歉，我发现了问题，是导入书源时全选复制删除默认的内容的时候最后有个花括号没有被复制上，导致删除时没有删除到

**Comment by wapscccs** [comment]
是否可以完善下API文档呢？我想将他用在API接口上

**Comment by hectorqin** [comment]
暂时没有时间，欢迎pr

**Comment by EasierLu** [comment]
@hectorqin  请问 `接口服务配置` 具体是在哪个文件进行配置呢？
