### ISSUE TITLE
大佬有考虑加入书签功能吗

### ISSUE THREAD

**Issue by xhpk** [hectorqin/reader#130]
感觉这个还是很实用的

**Comment by jacklaplace** [comment]
这不是必需品功能，得排队到后面才增加了，现在是处于保证基本功能齐全、流畅的开发阶段吧。

其实还有一变通的方法：

首先，现有的一个功能是，打开小说，选中几个文字，就弹出一个替换的窗口，你可以直接输入关键字书签书签书签，当然还可以写个短评，这些内容插入到小说正文之后，以后你想要找到这个书签位置，就全文搜索关键字书签书签书签，哈哈哈，这个方法可还行吗？

不过现在全文搜索这个功能也还没有，这个应该属于基础功能吧？

**Comment by hectorqin** [comment]
书签功能以后有空再看
全文搜索只适合本地小说，没多大必要

**Comment by qingmuhy** [comment]
其实我还想要标注功能，如果标注功能完善感觉epub的阅读体验会有不少的提升。

**Comment by xhpk** [comment]
> 其实我还想要标注功能，如果标注功能完善感觉epub的阅读体验会有不少的提升。
排队排队

**Comment by hectorqin** [comment]
新版已添加全文搜索功能和书签功能，全文搜索网文需要提前缓存章节内容。

**Comment by xhpk** [comment]
> 新版已添加全文搜索功能和书签功能，全文搜索网文需要提前缓存章节内容。

大哥牛逼！
顺便问下，阅读app支持从webdav导入书籍了,但是只在/webdav/books目录下，请问服务器端能否打通本地书仓和webdav呢

**Comment by hectorqin** [comment]
如果备份文件里面书籍路径存储的是相对路径，可以自行通过软链接实现，即将本地书仓软链接到用户的webdav/books目录。如果是绝对路径那就不好弄了

**Comment by xhpk** [comment]
> 如果备份文件里面书籍路径存储的是相对路径，可以自行通过软链接实现，即将本地书仓软链接到用户的webdav/books目录。如果是绝对路径那就不好弄了

测试了下，软链接方式行不通。不过这都小问题，有时间再考虑吧。
