### ISSUE TITLE
搜索时报错 java.lang.IllegalArgumentException: json string can not be null or empty

### ISSUE THREAD

**Issue by Meng-X-G** [hectorqin/reader#131]
在源阅读上测试该书源没问题。
[书源文件JSON](http://file.mxg.show/shareBookSource(1).json)
![image](https://user-images.githubusercontent.com/49837258/172368791-18213d53-bfe6-42f6-99e4-d869d00528c8.png)

**Comment by hectorqin** [comment]
书源兼容问题，暂时没时间去看，建议试试其它书源

**Comment by hectorqin** [comment]
Docker 新版提供了书源调试的功能，可以自己调试修改
