### ISSUE TITLE
本地书导入正常，打开提示获取目录失败

### ISSUE THREAD

**Issue by gewenlong365** [hectorqin/reader#138]
本地导入txt书，目录正常，但是打开就提示获取章节目录失败，未配置书源
![错误提示](https://user-images.githubusercontent.com/78864083/173721405-a8bdbd47-5de2-47ae-b0e7-d67b6bad6617.png)
![界面1](https://user-images.githubusercontent.com/78864083/173721409-aa9c463a-7ccc-441e-8ed7-235ab5bb26d9.png)

**Comment by gewenlong365** [comment]
版本v2.2.2-05310144

**Comment by hectorqin** [comment]
是不是用的免费部署平台？如果是的话，可能是数据被清理了，暂时无解

**Comment by gewenlong365** [comment]
> 是不是用的免费部署平台？如果是的话，可能是数据被清理了，暂时无解

用的hectorqin/reader安装，哦原来还有正式收费版？感谢回复，我尝试一下

**Comment by hectorqin** [comment]
试试 v2.3.0 版本看看

**Comment by hectorqin** [comment]
有可能是这个问题，因为使用了文件名和作者名作为文件夹名称
