### ISSUE TITLE
删除书籍时显示书籍信息错误

### ISSUE THREAD

**Issue by wbsnpc** [hectorqin/reader#139]
![bc4784e9374dc73993efec3854c22f0](https://user-images.githubusercontent.com/82518037/174032931-d1ee8856-7679-4750-b16b-caa30bde6efd.jpg)

**Comment by hectorqin** [comment]
是不是用的免费部署平台？如果是的话，可能是数据被清理了，暂时无解

**Comment by wbsnpc** [comment]
> 是不是用的免费部署平台？如果是的话，可能是数据被抓了，暂时无解
好的，谢谢

**Comment by wbsnpc** [comment]
好的，感谢

**Comment by wbsnpc** [comment]
问题是在我换某个书源之后，显示换源失败，然后书架就会出现没有名字的书籍，然后我去清理无效书源时，那本书的书源无法选择删除
![dde7d2b18dc9c442b425172911428c1](https://user-images.githubusercontent.com/82518037/174508978-fefa1b41-190c-4352-b1be-ba68927a5e2e.jpg)

**Comment by hectorqin** [comment]
这个删除功能后续有时间看看能不能优化

**Comment by hectorqin** [comment]
Docker 新版已优化
