### ISSUE TITLE
服务器端是否可以通过代理连接书源？

### ISSUE THREAD

**Issue by lhx332251335** [hectorqin/reader#14]
我通过docker部署了应用，在网页上添加书源后，有些需要通过代理连接。
我看到说明的“接口服务配置”部分有提到代理，但我并没有找到如何去配置，比如配置文件路径什么的。
我尝试把那些关键字作为环境变量，貌似也没有效果。

**Comment by hectorqin** [comment]
使用环境变量配置就行

**Comment by mt25cyb** [comment]
> 使用环境变量配置就行
想全局通过代理服务器，要如何使用环境变量来配置？

**Comment by mt25cyb** [comment]
> 使用环境变量配置就行

我想全局通过代理服务器，要如何使用环境变量来配置？

**Comment by hectorqin** [comment]
> > 使用环境变量配置就行
> 
> 我想全局通过代理服务器，要如何使用环境变量来配置？

现在不支持环境遍历配置代理了，建议使用其他方式
