### ISSUE TITLE
有声小说进度条无法调整

### ISSUE THREAD

**Issue by zeerdeer** [hectorqin/reader#143]
时间显示0 ,进度条也不能拖动
v2.0.3
EDGE/Firefox
Openwrt docker

**Comment by hectorqin** [comment]
浏览器兼容问题优先级会比较低，建议使用 chrome 试试

**Comment by hectorqin** [comment]
浏览器兼容问题优先级会比较低，建议使用 chrome 试试

**Comment by hectorqin** [comment]
这个是已经修复了吗？
