### ISSUE TITLE
iOS能否将书的内容和web界面缓存到手机本地实现离线阅读？

### ISSUE THREAD

**Issue by itcbx** [hectorqin/reader#146]
我记得好像web界面是可以实现离线阅读的，不知能不能实现

**Comment by jacklaplace** [comment]
这估计有点难，毕竟这个是服务器端的软件，而你想要实现一个客户机端的功能，你可以直接安装一个legado软件在手机上啊，总不能reader把legado的事情全干了。

哦，IOS没有legado，那就尴尬。

那你部署reader外网访问，这就解决了。就是你走在大街上，都可以随时访问家里nas架设的reader小说。

**Comment by itcbx** [comment]
> 这估计有点难，毕竟这个是服务器端的软件，而你想要实现一个客户机端的功能，你可以直接安装一个legado软件在手机上啊，总不能reader把legado的事情全干了。
> 
> 哦，IOS没有legado，那就尴尬。
> 
> 那你部署reader外网访问，这就解决了。就是你走在大街上，都可以随时访问家里nas架设的reader小说。

仅仅是缓存web界面是可以实现离线访问的，如果书籍内容再缓存在本地，就可以实现完全的离线阅读了，只是说离线时不能抓取新的小说而已

**Comment by itcbx** [comment]
> pwa模式可以离线访问，章节内容也可以在阅读界面缓存

对，我说的就是这个意思，就是现在pwa模式要怎么缓存，然后那个章节内容缓存的我好像一直不能缓存到手机本地，好像那个缓存功能只是缓存到服务器的？我是用docker创建的

**Comment by hectorqin** [comment]
可以缓存到本地的

**Comment by itcbx** [comment]
pwa要不要页面适配才能实现离线访问功能？然后那个章节缓存我一直保存不到本地手机不成功好奇怪

**Comment by hectorqin** [comment]
不需要，直接缓存应该就可以了，你可以在书架页面查看章节内容缓存大小
