### ISSUE TITLE
BUG：当一级目录0未获取到url时，发生错误

### ISSUE THREAD

**Issue by Ecalose** [hectorqin/reader#148]
在Legado里他会直接用标题替代(适用于有大标题的情况)，在reader里则
"[00:05.401] ┌获取正文内容 (长度：0)
[00:05.401] String index out of range: 50"

它会继续尝试获取正文，或许正文获取那边处理有点问题？
**https://github.com/hectorqin/reader/blob/d1e47d12425e4558ee4cd95be2019ce2b3fb7a8c/src/main/java/io/legado/app/model/webBook/WebBook.kt#L201-L241**

**Comment by hectorqin** [comment]
不太明白你的意思

**Comment by Ecalose** [comment]
就是有的网站会有像这样的大标题，在legado里它会把他用大标题替代，不继续获取正文;而在reader里也看到了该逻辑，但貌似并没有生效，reader会继续尝试获取正文，然后发生错误

--------原始邮件--------
2022年6月24日 上午9:13，hector 来信：

**Comment by Ecalose** [comment]
补张图,邮箱没发出来
![微信图片_20220624130609](https://user-images.githubusercontent.com/47114714/175466160-578100e2-0b49-44eb-b8fc-1ba2017c0290.jpg)


reader
![微信图片_20220624131411](https://user-images.githubusercontent.com/47114714/175466948-b2ce0842-d060-4860-8c56-841ab921e332.jpg)


legado
![微信图片_20220624130530](https://user-images.githubusercontent.com/47114714/175467017-c6d7f9a9-adcd-4b2a-b961-ebf899f92b0f.png)

**Comment by Ecalose** [comment]
legado里应该是这段
**https://github.com/gedoor/legado/blob/0486763dd1a04a58518c097075986e732aeee7ec/app/src/main/java/io/legado/app/model/webBook/WebBook.kt#L267-L270**

**Comment by hectorqin** [comment]
提供一下书源和书籍信息，我看看

**Comment by Ecalose** [comment]
> 提供一下书源和书籍信息，我看看

ok，我去tg上私你

**Comment by hectorqin** [comment]
再试试看

**Comment by Ecalose** [comment]
> 再试试看

唔，现在目录正常了，但用了那个书源的正文获取不到

**Comment by hectorqin** [comment]
调试信息有返回网络请求日志，自行调试吧

**Comment by Ecalose** [comment]
> 调试信息有返回网络请求日志，自行调试吧

唔，我再去想想，这个issue先关了

**Comment by Ecalose** [comment]
ok，tg上我私发你

--------原始邮件--------
2022年6月24日 下午2:09，hector 来信：
