### ISSUE TITLE
webdav返回401

### ISSUE THREAD

**Issue by alhricke** [hectorqin/reader#15]
开启了 reader.app.secure 选项，使用网页注册的用户名和密码登录，然后返回401，无限的循环登录……这个问题怎么解决？使用docker搭建的……

**Comment by hectorqin** [comment]
加一下TG群，发一下日志看看

**Comment by alhricke** [comment]
仔细看了一些日志，问题已解决，需要登录管理员开启相对应的webdav权限，或者修改是enable_webdav，默认是关闭的

**Comment by db-one** [comment]
@alhricke 请问一下你具体是怎么解决的？
enable_webdav是加在windowConfig.json里面吗  还是直接加在docker创建的命令里？
我两种方法都试过了 还是不行 直接找不到网页
![image](https://user-images.githubusercontent.com/20243226/159928813-6c73a34b-9542-42af-95c8-261b6dff61dd.png)


![image](https://user-images.githubusercontent.com/20243226/159928840-7e388ec7-34fb-46d1-9c54-8f3b23386771.png)

![image](https://user-images.githubusercontent.com/20243226/159928892-b1381a7e-a34e-4cf8-87bd-d4ba26dacc36.png)

web 是已经正常运行的了
![image](https://user-images.githubusercontent.com/20243226/159928927-615877c4-01e2-4411-bb4f-084df5a9329a.png)

**Comment by alhricke** [comment]
登录管理模式，找到用户管理，在里面打开webdav的开关即可，或者在\storage\data\users.json 里面修改相对应的内容



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月24日(星期四) 晚上9:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hectorqin/reader] webdav返回401 (Issue #15)





 
@alhricke 请问一下你具体是怎么解决的？
 enable_webdav是加在windowConfig.json里面吗  还是直接加在docker创建的命令里？
 我两种方法都试过了 还是不行 直接找不到网页
 
 

 

 
web 是已经正常运行的了

**Comment by db-one** [comment]
感谢回到  已经搞定了  我配置的是自用版   而自用版是没有webdav的web管理功能的，所有一直显示404，但实际上是已经运行的
