### ISSUE TITLE
最新版书源切换有问题

### ISSUE THREAD

**Issue by wisteria66** [hectorqin/reader#150]
大佬，我现在用的是https://reader.htmake.com/，我看您更新了，但是我刚刚使用的时候发现书源切换有问题，当你打开书架上的书籍想换源时首先提示书源链接不能为空，你按加载更多变成没有更多了。这个也不是书源本身的问题，因为我试了下新搜索一本书加入书架切换书源时没有问题，当我回到首页后再点开这个本就会出现上面的问题。
![1](https://user-images.githubusercontent.com/105471343/175551673-3b9d35f9-c2a9-42a9-895f-22a556abde0b.png)
![2](https://user-images.githubusercontent.com/105471343/175551699-b7aaa9ea-02a5-41a3-8de5-d21c419f6ac2.png)

**Comment by hectorqin** [comment]
Docker 新版已经修复了
