### ISSUE TITLE
搜索书源下 书源分类显示不全，手机可以滚动，web端无法滑动选择

### ISSUE THREAD

**Issue by kentvk04** [hectorqin/reader#153]
搜索书源下 书源分类显示不全，手机可以滚动，web端无法滑动选择

![image](https://user-images.githubusercontent.com/108311369/176065222-f4c29cce-9ab1-469b-a89c-1fe5587d29ea.png)

BUG修复
index.css 
 .popup-wrapper .data-wrapper .cata .explore-group{
     display:block;
}

**Comment by hectorqin** [comment]
使用鼠标中键，或者聚焦后使用 左右键
