### ISSUE TITLE
移动模式听书时当前段落错位

### ISSUE THREAD

**Issue by duhd1993** [hectorqin/reader#159]
![IMG_FF79D0EF3408-1](https://user-images.githubusercontent.com/2936633/177024456-848fd550-1714-4c94-9ef4-57618622c876.jpeg)

如图，当前朗读段落上面有几行被遮住了。如果是网文，段落比较短，整个段落都会被遮住。
IOS Safari，reader 2.0.3

**Comment by hectorqin** [comment]
ios机型比较多，我没有机型来适配界面

**Comment by duhd1993** [comment]
换到master branch自己build没问题了。为什么不用CI自动打包发布release呢？

**Comment by hectorqin** [comment]
release发布的桌面端不知道能不能用 CI自动打包，目前有自动编译 Docker版的

**Comment by duhd1993** [comment]
可以的，
https://github.com/softprops/action-gh-release
https://github.com/marvinpinto/action-automatic-releases
https://github.com/ncipollo/release-action
都可以。谢谢，有docker也行了
