### ISSUE TITLE
[Bug]docker版分组问题

### ISSUE THREAD

**Issue by NiuXZi** [hectorqin/reader#16]
启用和禁用一个分组时，下面会自动创建一个分组。
例如启用或引用“全部”时，下面会创建一个名为“全部”的分组。

顺便问下，docker版的怎么分组啊，直接改json吗？改了group后，书就直接不见了。

**Comment by hectorqin** [comment]
这个测试未发现问题，你看看你的版本号是多少？

> 启用和禁用一个分组时，下面会自动创建一个分组。

在书架界面点击封面，会弹出书籍信息，在书籍信息里面修改分组

**Comment by jacklaplace** [comment]
> 这个测试未发现问题，你看看你的版本号是多少？
> 
> > 启用和禁用一个分组时，下面会自动创建一个分组。
> 
> 在书架界面点击封面，会弹出书籍信息，在书籍信息里面修改分组

我用的docker版本v2.2.2-05290917

建议导入书籍的时候（或者添加新的书籍的时候），弹窗里书名、作者、规则可以增加一个这（几）本书归于哪个分组的选项，好方便整理全部藏书。

比如，我建立了几个分组：未完结、2021已阅、2020已阅、网友推荐等等标签分组，当导入多本书的时候，要一个个去点封面来归类分组，就挺麻烦的。

最后，谢谢作者分享这个程序！

**Comment by hectorqin** [comment]
后续会优化一下导入时设置分组
