### ISSUE TITLE
请问web端导入的本地书籍如何和阅读app同步

### ISSUE THREAD

**Issue by xhpk** [hectorqin/reader#163]
我尝试了一下，在web和阅读app都导入了一本书，然后保证了书名和作者都是一致的，然后使用webdev来进行同步，再在web打开就出现找不到书的情况。**排查了一下，貌似是书源不同步，想请问有好的办法解决吗？谢谢大佬**
**例如通过webdev恢复的book_url是这样的**
![image](https://user-images.githubusercontent.com/40262993/177183054-6c7fe45d-bd24-456f-b48f-c50736ebd33f.png)
**而在web导入后的book_url是这样的**
![image](https://user-images.githubusercontent.com/40262993/177184173-f48efe4f-40f2-4f2b-9efa-e15aabaf3f47.png)

**Comment by hectorqin** [comment]
> 然后使用webdev来进行同步

同步之后就不要再手动同步了，会自动同步进度的，不然就会被覆盖

**Comment by xhpk** [comment]
> > 然后使用webdev来进行同步
> 
> 同步之后就不要再手动同步了，会自动同步进度的，不然就会被覆盖

哦哦，明白了，知道咋搞了。
顺便问一下，这个自动同步进度，大概是多久保存保存一次，或者说需要什么条件触发呢

**Comment by hectorqin** [comment]
服务端是实时的，APP同步逻辑不清楚

**Comment by xhpk** [comment]
> 服务端是实时的，APP同步逻辑不清楚
明白了，三克油哥！
