### ISSUE TITLE
请问源码运行的方式有提供吗？

### ISSUE THREAD

**Issue by cksspk** [hectorqin/reader#164]
rt
clone代码到本地。无法运行
当前环境 m1
jdk11

**Comment by cksspk** [comment]
![Uploading image.png…]()

**Comment by cksspk** [comment]
<img width="1526" alt="image" src="https://user-images.githubusercontent.com/37790595/177456725-8afc3e4a-c762-4ab9-85ee-acb011c8d31c.png">

**Comment by hectorqin** [comment]
使用 build.sh 脚本看看
