### ISSUE TITLE
首次导入书源时如果过多会导致nginx内存溢出错误，是否可以接口分批导入，比如50条一次

### ISSUE THREAD

**Issue by 2545504198** [hectorqin/reader#166]
首次导入书源时如果过多会导致nginx内存溢出错误，是否可以接口分批导入，比如50条一次

**Comment by hectorqin** [comment]
建议不要导入太多书源，不然会很慢的

**Comment by 2545504198** [comment]
那也行，就是倒入时候点击没反应，还是打开F12才发现是内存溢出问题
还有就是书架的分组能不能加一个排序，不能排序的话就只能切换分组去排序了

**Comment by hectorqin** [comment]
可以手动修改 bookGroup.json 里面的 order

**Comment by hectorqin** [comment]
新版已添加分组排序功能
