### ISSUE TITLE
成功启动服务之后，在浏览器界面访问时的报错

### ISSUE THREAD

**Issue by xuan-ming** [hectorqin/reader#167]
后端连接失败 TypeError: Cannot read properties of undefined (reading 'data')

加载书源列表失败 Error: Network Error

加载分组列表失败 Error: Network Error

加载RSS订阅列表失败 Error: Network Error

加载替换规则失败 Error: Network Error

加载书签失败 Error: Network Error

**Comment by hectorqin** [comment]
看一下服务日志，检查一下前端接口设置
