### ISSUE TITLE
webdav无效

### ISSUE THREAD

**Issue by yoval** [hectorqin/reader#168]
网址：https://book.bizha.top/
账号：testacco
密码：testacco
登录网站正常，用户管理中，书仓与Webdav是开启状态。

webdav :http://book.bizha.top/reader3/webdav/
账号密码同上，备份提示是 Unauthorized

**Comment by hectorqin** [comment]
<img width="247" alt="image" src="https://user-images.githubusercontent.com/14220132/178231137-244d794f-14f7-43c1-b112-9394bd73c695.png">

Webdav 没有开启
