### ISSUE TITLE
ARM64设备安装docker打开IP:8080容器就自动重启，每个镜像都安装试过，换过N1和贝壳云都是这种情况。

### ISSUE THREAD

**Issue by aixufan** [hectorqin/reader#17]
stdout: ██████  ███████  █████  ██████  ███████ ██████  
stdout: ██   ██ ██      ██   ██ ██   ██ ██      ██   ██ 
stdout: ██████  █████   ███████ ██   ██ █████   ██████  
stdout: ██   ██ ██      ██   ██ ██   ██ ██      ██   ██ 
stdout: ██   ██ ███████ ██   ██ ██████  ███████ ██   ██ 
stdout:                                                 
stdout: 
stderr: kotlin.io.NoSuchFileException: storage-backup: The source file doesn't exist.
stderr: 	at kotlin.io.FilesKt__UtilsKt.copyRecursively(Utils.kt:263)
stderr: 	at kotlin.io.FilesKt__UtilsKt.copyRecursively$default(Utils.kt:260)
stderr: 	at org.lightink.reader.api.YueduApi.migration$suspendImpl(YueduApi.kt:391)
stderr: 	at org.lightink.reader.api.YueduApi.migration(YueduApi.kt)
stderr: 	at org.lightink.reader.api.YueduApi.initRouter$suspendImpl(YueduApi.kt:91)
stderr: 	at org.lightink.reader.api.YueduApi.initRouter(YueduApi.kt)
stderr: 	at org.lightink.reader.verticle.RestVerticle.start$suspendImpl(RestVerticle.kt:83)
stderr: 	at org.lightink.reader.verticle.RestVerticle.start(RestVerticle.kt)
stderr: 	at io.vertx.kotlin.coroutines.CoroutineVerticle$start$1.invokeSuspend(CoroutineVerticle.kt:53)
stderr: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
stderr: 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
stderr: 	at io.vertx.kotlin.coroutines.VertxCoroutineExecutor.execute(VertxCoroutine.kt:214)
stderr: 	at kotlinx.coroutines.ExecutorCoroutineDispatcherBase.dispatch(Executors.kt:64)
stderr: 	at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:413)
stderr: 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:25)
stderr: 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
stderr: 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:154)
stderr: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
stderr: 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
stderr: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
stderr: 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
stderr: 	at io.vertx.kotlin.coroutines.CoroutineVerticle.start(CoroutineVerticle.kt:51)
stderr: 	at io.vertx.core.Verticle.start(Verticle.java:66)
stderr: 	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:556)
stderr: 	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
stderr: 	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
stderr: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
stderr: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405)
stderr: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
stderr: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
stderr: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
stderr: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
stderr: 	at java.lang.Thread.run(Thread.java:748)
stdout: #
stdout: # A fatal error has been detected by the Java Runtime Environment:
stdout: #
stdout: #  Internal Error (assembler_aarch64.hpp:1156), pid=7, tid=0x0000007f901caaa0
stdout: #  guarantee(Rs != Rn && Rs != Rt) failed: unpredictable instruction
stdout: #
stdout: # JRE version: OpenJDK Runtime Environment (8.0_212-b04) (build 1.8.0_212-b04)
stdout: # Java VM: OpenJDK 64-Bit Server VM (25.212-b04 mixed mode linux-aarch64 compressed oops)
stdout: # Derivative: IcedTea 3.12.0
stdout: # Distribution: Custom build (Sat May  4 17:44:26 UTC 2019)
stdout: # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
stdout: #
stdout: # An error report file with more information is saved as:
stdout: # //hs_err_pid7.log
stdout: #
stdout: # Compiler replay data is saved as:
stdout: # //replay_pid7.log
stdout: #
stdout: # If you would like to submit a bug report, please include
stdout: # instructions on how to reproduce the bug and visit:
stdout: #   https://icedtea.classpath.org/bugzilla
stdout: #
stdout: ██████  ███████  █████  ██████  ███████ ██████  
stdout: ██   ██ ██      ██   ██ ██   ██ ██      ██   ██ 
stdout: ██████  █████   ███████ ██   ██ █████   ██████  
stdout: ██   ██ ██      ██   ██ ██   ██ ██      ██   ██ 
stdout: ██   ██ ███████ ██   ██ ██████  ███████ ██   ██ 
stdout:                                                 
stdout: 
stderr: kotlin.io.NoSuchFileException: storage-backup: The source file doesn't exist.
stderr: 	at kotlin.io.FilesKt__UtilsKt.copyRecursively(Utils.kt:263)
stderr: 	at kotlin.io.FilesKt__UtilsKt.copyRecursively$default(Utils.kt:260)
stderr: 	at org.lightink.reader.api.YueduApi.migration$suspendImpl(YueduApi.kt:391)
stderr: 	at org.lightink.reader.api.YueduApi.migration(YueduApi.kt)
stderr: 	at org.lightink.reader.api.YueduApi.initRouter$suspendImpl(YueduApi.kt:91)
stderr: 	at org.lightink.reader.api.YueduApi.initRouter(YueduApi.kt)
stderr: 	at org.lightink.reader.verticle.RestVerticle.start$suspendImpl(RestVerticle.kt:83)
stderr: 	at org.lightink.reader.verticle.RestVerticle.start(RestVerticle.kt)
stderr: 	at io.vertx.kotlin.coroutines.CoroutineVerticle$start$1.invokeSuspend(CoroutineVerticle.kt:53)
stderr: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
stderr: 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
stderr: 	at io.vertx.kotlin.coroutines.VertxCoroutineExecutor.execute(VertxCoroutine.kt:214)
stderr: 	at kotlinx.coroutines.ExecutorCoroutineDispatcherBase.dispatch(Executors.kt:64)
stderr: 	at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:413)
stderr: 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:25)
stderr: 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
stderr: 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:154)
stderr: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
stderr: 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
stderr: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
stderr: 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
stderr: 	at io.vertx.kotlin.coroutines.CoroutineVerticle.start(CoroutineVerticle.kt:51)
stderr: 	at io.vertx.core.Verticle.start(Verticle.java:66)
stderr: 	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:556)
stderr: 	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
stderr: 	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
stderr: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
stderr: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405)
stderr: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
stderr: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
stderr: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
stderr: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
stderr: 	at java.lang.Thread.run(Thread.java:748)

**Comment by hectorqin** [comment]
手动创建 `storage/data/default` 目录，重启容器，或者等新版本
