### ISSUE TITLE
漫画书籍缓存在服务器中的图片并没有被使用

### ISSUE THREAD

**Issue by zezh4350** [hectorqin/reader#173]
漫画书籍的图片缓存会存储在路径：storage\data\username\bookname\e0505dfdc5006638045598f94794bdb6\images
其中章节的图片src依旧是书源的地址，致使阅读时图片加载来源于书源，而非服务器中的缓存。
![BaiduShurufa_2022-7-14_13-57-20](https://user-images.githubusercontent.com/61725651/178910525-7b8a1d29-282d-49d1-b646-0503ab68bb0e.png)

**Comment by hectorqin** [comment]
新版已添加该功能，但不会保存到缓存文件
