### ISSUE TITLE
书籍阅读缓存清理问题

### ISSUE THREAD

**Issue by zezh4350** [hectorqin/reader#174]
检查服务器中的数据发现其中存有了很多不在书籍中的缓存文件，经简单的测试其产生与清理的方式如下：
        书籍被搜索并阅读后，服务器中都会存在有缓存文件，目前只有先加入书架，再从书架中删除才能够清除服务器中的阅读缓存，亦或者直接在服务器中找到文件删除。

提供2个不成熟的建议：
A：将“本地缓存”功能模块整在“用户缓存管理”，区分“服务器缓存”和“浏览器缓存” ，在“服务器”缓存中增加缓存批量清理功能，批量清理当前账号下在书架与不在书架中的缓存。
B：在书架中的书籍才会在服务器中留下阅读缓存。

**Comment by hectorqin** [comment]
临时书籍已经使用临时缓存了。清理服务器缓存可以直接在 用户数据管理 里面删除对应书籍目录
