### ISSUE TITLE
漫画阅读跳图和加载下一章直接在章节底BUG

### ISSUE THREAD

**Issue by xrmhxj** [hectorqin/reader#175]
跳图BUG：从上到下阅读并下划漫画图片，显示图片的索引顺序正常是0-1-2-3-4-...，有些情况下就是0-1-2-4-...，跳过了中间的图3。可能原因是图片动态预加载的数量太少，图4比图3先一步加载完成，元素显示焦点被图4先一步获得。

加载下一章直接在章节底BUG：可能原因是图片动态加载完成时的顺序问题，元素显示焦点被最后一张图获得。

向上滑不动不丝滑BUG：加载下一章直接在章节底时想拉回头部，或者想回看上面的内容，向上滑动时有时显示区域会被拉回至原点。

**Comment by hectorqin** [comment]
> 跳图BUG

这不是bug，有些图片可能网络加载慢或者地址错误导致图片加载慢或者失败，建议先缓存再阅读。

> 加载下一章直接在章节底BUG
> 向上滑不动不丝滑BUG

这些暂时不确定问题所在，先缓存再阅读试试

**Comment by zezh4350** [comment]
> > 跳图BUG
> 
> 这不是bug，有些图片可能网络加载慢或者地址错误导致图片加载慢或者失败，建议先缓存再阅读。
> 
已经将数据缓存在服务器中，内网阅读还是存在这个问题。或指的是缓存在浏览器中？

**Comment by hectorqin** [comment]
图片没法缓存到浏览器的，看看网络请求吧，是图片加载失败还是图片加载太慢？

**Comment by zezh4350** [comment]
图片没有加载失败，阅读向下滑动的时候就是突然跳图

**Comment by hectorqin** [comment]
那这暂时无解
