### ISSUE TITLE
夜间模式切换的时候会重置为默认样式

### ISSUE THREAD

**Issue by ws132** [hectorqin/reader#179]
手机端Safari和桌面端Firefox都能稳定复现。
在夜间模式下，点击页面右边栏夜间模式切换按钮会重置为白天的默认样式，但字体和页面设置数值都正常显示。
手机夜晚模式自动切换的时候也会重置。
只要手动在样式表选择页面选择其他样式就能恢复正常，但此时页面右边栏夜间模式切换按钮就会失效，无法点击。

**Comment by ws132** [comment]
版本号：v2.5.7-07190617
安装方式：Docker-Compose自建

**Comment by ws132** [comment]
如果有用的话，我记得好像是2.5.3好像就开始就有了，不一定准确。

**Comment by hectorqin** [comment]
设置一下 默认白天方案和默认黑夜方案

**Comment by ws132** [comment]
> 设置一下 默认白天方案和默认黑夜方案

……3Q，谢谢大大解答～🥰
试着设置了一下，就没问题了。
以防有人不知道，在这里说一下怎么操作：
配置方案（内置黑夜）→阅读主题（黑夜）→自定义设置字体大小、间距等等→方案类型（黑夜默认）
配置方案（内置白天）→阅读主题（随便选个好看的颜色）→自定义设置字体大小、间距等等→方案类型（白天默认）
