### ISSUE TITLE
能否支持导入书源时自动检测排除含JavaScript条目

### ISSUE THREAD

**Issue by ma0shu** [hectorqin/reader#18]
1、试了不少书源都报 #3 的错，出了错就只能删了配置文件重来，能不能支持在导入时就检测？
2、同样的书源，为什么用docker搭的就不报错，用本地server端搭的就报错？
3、在线导入书源时，前一次导入的全选数量会留在后面（比如第一次导入51条，第二次100条只显示51条，刷新后正常）
4、1.90的Server端版本号标的是v1.8.0-03231151？
感谢!

**Comment by hectorqin** [comment]
1. 可以手动删除失效书源的，在失效书源管理页面，暂时无法在导入时检测 javascript，可以自行写脚本清理
2. 建议使用docker版本，docker版本更新比较快，本地server会收到本地的jvm环境影响
3. 我有空再看看
4. 推荐使用docker版本，我有空更新一下release

**Comment by hectorqin** [comment]
1. Docker新版已支持在导入时检测使用了 Javascript 和 Webview 的书源

**Comment by ma0shu** [comment]
> 1. Docker新版已支持在导入时检测使用了 Javascript 和 Webview 的书源
好耶，感谢！

另外部署命令的$(PWD)是不是要改成$(pwd),[](https://blog.csdn.net/sxzlc/article/details/107678379)不然会报错

**Comment by hectorqin** [comment]
嗯，mac是有 PWD 命令的，linux可能只有 pwd，我有空改一下
