### ISSUE TITLE
本地txt文件上传报错问题

### ISSUE THREAD

**Issue by wwwxeb** [hectorqin/reader#182]
本地文件上传null错误，文件已经上传成功，解析失败。   
下载源代码本地运行跟踪调试发现报错代码如下：   
`
io.legado.app.data.entities   

data class Book   

284            book.bookUrl = book.bookUrl.replace(Regex("^${rootPath}"), "")   

285            book.originName = book.originName.replace(Regex("^${rootPath}"), "")   

`
这两行用了正则表达式报错，我对正则不熟悉，好像是路径的斜杠导致的，去掉正则就可以正常运行了。

**Comment by hectorqin** [comment]
windows 环境吗？

**Comment by hectorqin** [comment]
试试 beta 版看看

**Comment by wwwxeb** [comment]
> windows 环境吗？

是的，我是在docker上跑的报错，然后再wndiws上跟踪了一下代码，发现是这段代码的问题。
我更新一下docker试试

**Comment by wwwxeb** [comment]
> 试试 beta 版看看

试过了，doker镜像的last版本可以正常上传本地文件，看来是我之前的容器没更新导致的。

**Comment by hectorqin** [comment]
嗯，docker版 2.5.6 就修复了，Windows 版刚修复了一版
