### ISSUE TITLE
用大佬自己搭建的https://reader.htmake.com最近老是出问题，进去就是空白，书架的书都不见了

### ISSUE THREAD

**Issue by wisteria66** [hectorqin/reader#190]

**Comment by wisteria66** [comment]
![微信图片_20220729210622](https://user-images.githubusercontent.com/105471343/181768117-1c1a4abd-f9c8-4d4a-a085-2c7ca725cd70.png)

**Comment by hectorqin** [comment]
用的人太多了。。。服务器扛不住了，已经重启了
