### ISSUE TITLE
服务器版本是否支持本地书籍呢？

### ISSUE THREAD

**Issue by fantasyjqc** [hectorqin/reader#198]
看了下好像只有客户端版本支持在localStore放入txt等文件，不知道服务器版本是否可以使用？如何使用呢

**Comment by hectorqin** [comment]
本地书籍不是放在localstorage的，都可以导入本地书籍

**Comment by fantasyjqc** [comment]
> 

我是指是否可以按目录直接读取服务器上已经存在的txt之类的小说呢。
