### ISSUE TITLE
多设备切换问题

### ISSUE THREAD

**Issue by HuZengKan** [hectorqin/reader#199]
环境：服务端docker部署
我在两个设备上阅读同一本书（2台手机+电脑都有这个问题）
1.在A手机阅读到100章，关闭浏览器
2.切换到B手机阅读到200章，关闭浏览器
3.再回到A手机，书架页面显示阅读章节为200章，但是如果直接点击进入阅读，页面却是100章（之前在A手机读到的位置），如果要正常阅读200章，必须要在书架页面刷新一次才能进200章（刷新特别慢）
这个是缓存问题吗？请问有没有解决的办法

**Comment by ws132** [comment]
缓存问题，没什么太好的办法。
可以试试后台关闭浏览器，然后再进。

**Comment by HuZengKan** [comment]
> 

关闭后台进程没用，缓存还在，估计只能清除浏览器数据才有效，还是用刷新吧……
