### ISSUE TITLE
建议把书能够预读到服务器上

### ISSUE THREAD

**Issue by lalakiop** [hectorqin/reader#20]
预读的资源都放在本地，如果书源失效（特别是一些小众的书籍）会导致看到一半就没法看，或者得更换书源。建议可以在阅读时将正本书全部下载到服务器上。如果能够把侧边音量键翻页的功能加上就更好啦。

**Comment by hectorqin** [comment]
缓存到服务器可以考虑
web没法监听到音量键的使用

**Comment by hectorqin** [comment]
已支持缓存章节内容到服务器，需要开启选项 `--reader.app.cacheChapterContent=true`
