### ISSUE TITLE
Windows 10 能否/如何自定义 JAVA 路径？

### ISSUE THREAD

**Issue by H-Tung** [hectorqin/reader#202]
我用scoop安装了openjdk17 `D:\Applications\Scoop\apps\openjdk17\current`，想问能否像[FreePlane](https://www.freeplane.org/)一样在环境变量里通过读取 JAVA_HOME 路径解决依赖？

**Comment by hectorqin** [comment]
直接用 cmd 启动jar就行了

**Comment by H-Tung** [comment]
十分感谢！ `java -jar PATHTOJAR` 是第一次了解到
