### ISSUE TITLE
docker版本默认的管理员账号是什么？

### ISSUE THREAD

**Issue by huajianjiu** [hectorqin/reader#213]
我自定义了管理员密码，但是运行起来之后我不知道登录的账号

**Comment by Becods** [comment]
左边栏里找到加载用户空间，输入管理员密码

多用户版自行注册账号

**Comment by huajianjiu** [comment]
> 左边栏里找到加载用户空间，输入管理员密码
> 
> 多用户版自行注册账号

多谢
