### ISSUE TITLE
进度同步及书仓下载功能问题

### ISSUE THREAD

**Issue by ColdFoam** [hectorqin/reader#221]
![photo_2022-09-19_22-43-58](https://user-images.githubusercontent.com/30315539/191045295-769e8262-8580-4183-b4d5-2b688b782749.jpg)

手机和电脑浏览器阅读，上面是书架界面显示三百零九章是手机阅读进度同步过来，但是点进阅读界面就变成下面之前电脑浏览器阅读进度

![photo_2022-09-19_22-44-10](https://user-images.githubusercontent.com/30315539/191045380-5a569690-879c-41d2-abfb-6c16e535a072.jpg)
############################################################################################
![photo_2022-09-19_22-44-14](https://user-images.githubusercontent.com/30315539/191045422-321d3064-aed2-4e76-8014-1ca1c7e0a34a.jpg)

![photo_2022-09-19_22-44-18](https://user-images.githubusercontent.com/30315539/191045479-a15813e6-6945-492f-9eaf-a3e18ea4412d.jpg)

![photo_2022-09-19_22-44-21](https://user-images.githubusercontent.com/30315539/191045515-d5b606dc-d79b-47bb-8fb9-f4b5a2e00d10.jpg)

以及书仓下载功能错误

**Comment by ColdFoam** [comment]
> 

是一样的，不是app和reader，是安卓浏览器网页和电脑浏览器网页，之前用阅读app和reader好像也出现过，有时候可以有时候不同步，就是书架显示的进度是最新看到的进度，点进小说里面就变成这个设备之前看到的地方，刚刚试了一下，点进小说前点下书架的刷新好像就没事，可以同步，话说接口日志在哪个位置。。

**Comment by ColdFoam** [comment]
> 

Docker-Compose，接口日志是/home/reader/logs里面的吗

**Comment by xhpk** [comment]
> ![photo_2022-09-19_22-43-58](https://user-images.githubusercontent.com/30315539/191045295-769e8262-8580-4183-b4d5-2b688b782749.jpg)
> 
> 手机和电脑浏览器阅读，上面是书架界面显示三百零九章是手机阅读进度同步过来，但是点进阅读界面就变成下面之前电脑浏览器阅读进度
> 
> ![photo_2022-09-19_22-44-10](https://user-images.githubusercontent.com/30315539/191045380-5a569690-879c-41d2-abfb-6c16e535a072.jpg) ############################################################################################ ![photo_2022-09-19_22-44-14](https://user-images.githubusercontent.com/30315539/191045422-321d3064-aed2-4e76-8014-1ca1c7e0a34a.jpg)
> 
> ![photo_2022-09-19_22-44-18](https://user-images.githubusercontent.com/30315539/191045479-a15813e6-6945-492f-9eaf-a3e18ea4412d.jpg)
> 
> ![photo_2022-09-19_22-44-21](https://user-images.githubusercontent.com/30315539/191045515-d5b606dc-d79b-47bb-8fb9-f4b5a2e00d10.jpg)
> 
> 以及书仓下载功能错误

快餐店的书可还行

**Comment by ColdFoam** [comment]
> 书仓下载应该修复了，你试试v2.7.1看看

2.7.1可以下载了
