### ISSUE TITLE
隔天或者过段时间看就出现跑满CPU

### ISSUE THREAD

**Issue by CuteLeaf** [hectorqin/reader#224]
使用的是docker运行，重启一下服务就恢复了，但第二天一看又占满CPU了，不知道啥情况，出现好几次了
![QQ截图20220922233135](https://user-images.githubusercontent.com/43440669/191789969-8cb1645d-e067-408c-81b7-2bf369c4017b.png)
![QQ截图20220922233017](https://user-images.githubusercontent.com/43440669/191789956-dd84ef5d-5056-4900-ba7b-71b0e289bc56.png)

**Comment by ctaoist** [comment]
这么严重的问题还能无解？？
