### ISSUE TITLE
上传书籍 Error: Request failed with status code 404

### ISSUE THREAD

**Issue by fsdsoyu** [hectorqin/reader#23]
ubuntu20.04 docker下

[DefaultDispatcher-worker-4] 12:10:01.048 INFO  VertExt - storage key: [data, users] path: /storage/data/users.json
[DefaultDispatcher-worker-4] 12:10:01.048 INFO  VertExt - storage key: [data, fsdsoyu, bookshelf] path: /storage/data/fsdsoyu/bookshelf.json
[DefaultDispatcher-worker-4] 12:10:01.048 INFO  VertExt - storage key: [data, fsdsoyu, bookSource] path: /storage/data/fsdsoyu/bookSource.j>
[DefaultDispatcher-worker-5] 12:10:01.189 INFO  VertExt - storage key: [data, fsdsoyu, 万族入侵：我有一剑可破万法_, 6786452b580552d67351540>
[DefaultDispatcher-worker-3] 12:10:01.359 INFO  VertExt - storage key: [data, fsdsoyu, 万族入侵：我有一剑可破万法_/6786452b580552d673515404>
[DefaultDispatcher-worker-3] 12:10:01.360 INFO  VertExt - storage key: [data, fsdsoyu, bookshelf] path: /storage/data/fsdsoyu/bookshelf.json
[DefaultDispatcher-worker-3] 12:10:01.362 INFO  VertExt - storage key: [data, fsdsoyu, bookshelf] path: /storage/data/fsdsoyu/bookshelf.json
[DefaultDispatcher-worker-1] 12:10:01.364 INFO  YueduApi - Loop: 1 concurrentCount: 1 lastIndex: 0  costTime: 177 ms
[DefaultDispatcher-worker-1] 12:10:01.364 INFO  YueduApi - Loop: 2 concurrentCount: 0 lastIndex: 1  costTime: 0 ms
[DefaultDispatcher-worker-1] 12:10:01.364 INFO  YueduApi - 书架书籍更新检查结束
[vert.x-eventloop-thread-2] 12:10:27.797 WARN  LoggerHandlerImpl - 10.0.0.11 - - [Tue, 12 Apr 2022 04:10:27 GMT] "POST /reader/importBookPr>
[vert.x-eventloop-thread-2] 12:10:41.775 WARN  LoggerHandlerImpl - 10.0.0.11 - - [Tue, 12 Apr 2022 04:10:41 GMT] "POST /reader/importBookPr>

**Comment by hectorqin** [comment]
日志不完整，打开开发者工具，截一下网络请求的图片
