### ISSUE TITLE
kindle的自带浏览器无法访问

### ISSUE THREAD

**Issue by hermersnana** [hectorqin/reader#27]
kindle的自带浏览器无法访问

**Comment by hectorqin** [comment]
我这边的咪咕版kindle是可以打开的

**Comment by hectorqin** [comment]
用kindle打开这个页面，截图看看     https://html5test.com/

**Comment by xiaoyu886** [comment]
![Uploading image.jpg…]()这是我的kindle voyage,5.13.6的系统

**Comment by hermersnana** [comment]
谢谢您的回复，附件pdf是测试结果
[PDF-Dokument.pdf](https://github.com/hectorqin/reader/files/8494586/PDF-Dokument.pdf)

**Comment by hectorqin** [comment]
这个kindle的浏览器太落后了，无法兼容

**Comment by hermersnana** [comment]
谢谢了，等新的kindle到了话，我试试新的kindle是否可以。

**Comment by superfat1988** [comment]
Kindle Oasis 2 (KO2) （第9代）5.14.2同样无法打开， 浏览器h5分数为155。 官方固件坑。

**Comment by hermersnana** [comment]
最新测试kindle paperwhite 11 版本5.14.2 也不行。不知是否搞个简易版本给原系统的。能看书就行。读书还是kindle比较方便。

**Comment by hectorqin** [comment]
暂时没有办法，阉割的太厉害了

**Comment by hermersnana** [comment]
谢谢，辛苦了。

**Comment by jacklaplace** [comment]
> 用kindle打开这个页面，截图看看 https://html5test.com/

看来是不支持 IE浏览器 11了，是吗？昨天才发现用IE 11打不开reader docker小说

**Comment by jacklaplace** [comment]
更新一下，win10的edge浏览器可以打开看这个小说的，edge版本为 40.15035.0.0
