### ISSUE TITLE
简繁转换bug

### ISSUE THREAD

**Issue by MXGMXG** [hectorqin/reader#275]
![image](https://user-images.githubusercontent.com/49837258/203359694-7030e3c2-527c-4f6c-b7c8-062c6fb23c5d.png)

首先确定服务器返回的字是"土著"，可是显示的是”土着“

![image](https://user-images.githubusercontent.com/49837258/203360292-bc5cb061-e826-4eeb-8402-f8c1b8c82441.png)

转为繁体后显示为"土著"
猜测应该是选择简体时强制转换，所以把"著"判定为繁体，导致的bug。
解决方案：添加一个”原文“选项

**Comment by Meng-X-G** [comment]
困扰了好久，找了半天终于找到问题了。希望尽快修复（我还以为是书源问题，换了半天都是这样才感觉不对劲😭😭😭）

**Comment by Meng-X-G** [comment]
大佬什么时候更新呢，错别字好难受😭

**Comment by ausmas** [comment]
吞噬星空 乾巫币也被简化成干巫币，找了好久原因 XD
