### ISSUE TITLE
自建docker-compose版本，导入书源失败

### ISSUE THREAD

**Issue by wclmgcd** [hectorqin/reader#28]
导入书源失败 Error: Request failed with status code 404，

**Comment by hectorqin** [comment]
提供一下日志看看

**Comment by wclmgcd** [comment]
[main] 18:21:16.428 INFO  ReaderApplicationKt - Starting ReaderApplicationKt on a764667567f3 with PID 9 (/app/bin/reader.jar started by root in /)
[main] 18:21:16.432 DEBUG ReaderApplicationKt - Running with Spring Boot v2.1.6.RELEASE, Spring v5.1.8.RELEASE
[main] 18:21:16.435 INFO  ReaderApplicationKt - The following profiles are active: prod
[vert.x-eventloop-thread-0] 18:21:26.159 INFO  YueduApi - port: 8080
[vert.x-eventloop-thread-0] 18:21:26.169 INFO  YueduApi - serverPort: 8080
[vert.x-eventloop-thread-0] 18:21:26.452 INFO  VertExt - osName: Linux currentDir: /
[vert.x-eventloop-thread-0] 18:21:26.747 INFO  VertExt - storage key: [cache, invalidBookSourceList] path: /storage/cache/invalidBookSourceList.json
[vert.x-eventloop-thread-0] 18:21:26.856 INFO  RestVerticle - port: 8080
[main] 18:21:27.259 INFO  ThreadPoolTaskScheduler - Initializing ExecutorService 'taskScheduler'
[main] 18:21:27.446 INFO  ReaderApplicationKt - Started ReaderApplicationKt in 14.8 seconds (JVM running for 18.194)
[vertx-blocked-thread-checker] 18:21:27.647 WARN  BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-0,5,main]=Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2097 ms, time limit is 2000 ms
[vert.x-eventloop-thread-0] 18:21:27.944 INFO  RestVerticle - Server running at: http://localhost:8080
[vert.x-eventloop-thread-0] 18:21:27.944 INFO  RestVerticle - Web reader running at: http://localhost:8080
[vert.x-eventloop-thread-0] 18:22:50.060 INFO  LoggerHandlerImpl - 112.112.112.112 - - [Thu, 14 Apr 2022 10:22:49 GMT] "GET / HTTP/1.1" 200 4647 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:22:50.565 INFO  LoggerHandlerImpl - 112.112.112.112 - - [Thu, 14 Apr 2022 10:22:50 GMT] "GET /css/app.0dccd3ad.css HTTP/1.1" 200 4916 "http://45.111.11.111:4395/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:22:51.995 INFO  LoggerHandlerImpl - 112.112.112.112 - - [Thu, 14 Apr 2022 10:22:51 GMT] "GET /js/app.33656218.js HTTP/1.1" 200 58779 "http://45.111.11.111:4395/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:22:52.435 INFO  LoggerHandlerImpl - 112.112.112.112 - - [Thu, 14 Apr 2022 10:22:50 GMT] "GET /css/chunk-vendors.101fdb7d.css HTTP/1.1" 200 115694 "http://45.111.11.111:4395/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:22:55.591 INFO  LoggerHandlerImpl - 112.112.112.112 - - [Thu, 14 Apr 2022 10:22:55 GMT] "GET /img/icons/apple-touch-icon-152x152.png HTTP/1.1" 200 10730 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:22:55.604 INFO  LoggerHandlerImpl - 112.112.112.112 - - [Thu, 14 Apr 2022 10:22:55 GMT] "GET /img/icons/favicon-16x16.png HTTP/1.1" 200 1031 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:23:35.227 INFO  LoggerHandlerImpl - 112.112.112.112 - - [Thu, 14 Apr 2022 10:22:51 GMT] "GET /js/chunk-vendors.352edeae.js HTTP/1.1" 200 671286 "http://45.111.11.111:4395/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:23:40.839 INFO  LoggerHandlerImpl - 112.112.112.112 - - [Thu, 14 Apr 2022 10:23:40 GMT] "GET /css/index.0ce29b06.css HTTP/1.1" 200 26695 "http://45.111.11.111:4395/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:23:40.883 INFO  RestVerticle - GET http://45.111.11.111:4395/reader3/getUserInfo
[vert.x-eventloop-thread-0] 18:23:40.884 INFO  RestVerticle - request body: 
[DefaultDispatcher-worker-1] 18:23:40.941 INFO  LoggerHandlerImpl - 112.112.112.112 - - [Thu, 14 Apr 2022 10:23:40 GMT] "GET /reader3/getUserInfo HTTP/1.1" 200 74 "http://45.111.11.111:4395/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:23:41.176 INFO  LoggerHandlerImpl - 112.112.112.112 - - [Thu, 14 Apr 2022 10:23:41 GMT] "GET /assets/reader.css HTTP/1.1" 200 54 "http://45.111.11.111:4395/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:23:44.263 INFO  LoggerHandlerImpl - 112.112.112.112 - - [Thu, 14 Apr 2022 10:23:40 GMT] "GET /js/index.1854783d.js HTTP/1.1" 200 120824 "http://45.111.11.111:4395/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:23:51.294 INFO  LoggerHandlerImpl - 112.112.112.112 - - [Thu, 14 Apr 2022 10:23:51 GMT] "GET /fonts/element-icons.535877f5.woff HTTP/1.1" 200 28200 "http://45.111.11.111:4395/css/chunk-vendors.101fdb7d.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:23:51.332 INFO  RestVerticle - GET http://45.111.11.111:4395/reader3/getBookshelf?refresh=0
[vert.x-eventloop-thread-0] 18:23:51.332 INFO  RestVerticle - request body: 
[DefaultDispatcher-worker-1] 18:23:51.341 INFO  VertExt - storage key: [data, default, bookshelf] path: /storage/data/default/bookshelf.json
[DefaultDispatcher-worker-1] 18:23:51.350 INFO  LoggerHandlerImpl - 112.112.112.112 - - [Thu, 14 Apr 2022 10:23:51 GMT] "GET /reader3/getBookshelf?refresh=0 HTTP/1.1" 200 42 "http://45.111.11.111:4395/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:23:51.634 INFO  RestVerticle - GET http://45.111.11.111:4395/reader3/getSources?simple=1
[vert.x-eventloop-thread-0] 18:23:51.634 INFO  RestVerticle - request body: 
[DefaultDispatcher-worker-3] 18:23:51.639 INFO  VertExt - storage key: [data, default, bookSource] path: /storage/data/default/bookSource.json
[vert.x-eventloop-thread-0] 18:23:51.641 INFO  RestVerticle - GET http://45.111.11.111:4395/reader3/getBookGroups
[vert.x-eventloop-thread-0] 18:23:51.641 INFO  RestVerticle - request body: 
[DefaultDispatcher-worker-3] 18:23:51.643 INFO  LoggerHandlerImpl - 112.112.112.112 - - [Thu, 14 Apr 2022 10:23:51 GMT] "GET /reader3/getSources?simple=1 HTTP/1.1" 200 42 "http://45.111.11.111:4395/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:23:51.651 INFO  RestVerticle - GET http://45.111.11.111:4395/reader3/getRssSources?simple=1
[vert.x-eventloop-thread-0] 18:23:51.652 INFO  RestVerticle - request body: 
[DefaultDispatcher-worker-2] 18:23:51.661 INFO  VertExt - storage key: [data, default, bookGroup] path: /storage/data/default/bookGroup.json
[DefaultDispatcher-worker-2] 18:23:51.661 INFO  LoggerHandlerImpl - 112.112.112.112 - - [Thu, 14 Apr 2022 10:23:51 GMT] "GET /reader3/getBookGroups HTTP/1.1" 200 42 "http://45.111.11.111:4395/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[DefaultDispatcher-worker-2] 18:23:51.667 INFO  VertExt - storage key: [data, default, rssSources] path: /storage/data/default/rssSources.json
[DefaultDispatcher-worker-2] 18:23:51.669 INFO  LoggerHandlerImpl - 112.112.112.112 - - [Thu, 14 Apr 2022 10:23:51 GMT] "GET /reader3/getRssSources?simple=1 HTTP/1.1" 200 42 "http://45.111.11.111:4395/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:23:54.114 INFO  LoggerHandlerImpl - 112.112.112.112 - - [Thu, 14 Apr 2022 10:23:54 GMT] "GET /css/reader.0f4efb18.css HTTP/1.1" 200 34079 "http://45.111.11.111:4395/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:23:54.123 INFO  LoggerHandlerImpl - 112.112.112.112 - - [Thu, 14 Apr 2022 10:23:54 GMT] "GET /js/reader.4f77f7bf.js HTTP/1.1" 200 86923 "http://45.111.11.111:4395/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[DefaultDispatcher-worker-2] 18:30:00.025 INFO  VertExt - storage key: [cache, invalidBookSourceList] path: /storage/cache/invalidBookSourceList.json
[DefaultDispatcher-worker-2] 18:30:00.027 INFO  YueduApi - 开始检查书架书籍更新
[DefaultDispatcher-worker-2] 18:30:00.030 INFO  VertExt - storage key: [data, default, bookshelf] path: /storage/data/default/bookshelf.json
[DefaultDispatcher-worker-2] 18:30:00.034 INFO  YueduApi - 书架书籍更新检查结束
[vert.x-eventloop-thread-0] 18:37:38.114 INFO  LoggerHandlerImpl - 172.25.0.1 - - [Thu, 14 Apr 2022 10:37:38 GMT] "GET / HTTP/1.1" 200 4647 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:38:01.800 INFO  LoggerHandlerImpl - 172.25.0.1 - - [Thu, 14 Apr 2022 10:38:01 GMT] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:38:05.307 INFO  LoggerHandlerImpl - 172.25.0.1 - - [Thu, 14 Apr 2022 10:38:05 GMT] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:38:18.197 INFO  LoggerHandlerImpl - 172.25.0.1 - - [Thu, 14 Apr 2022 10:38:18 GMT] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:38:20.062 INFO  LoggerHandlerImpl - 172.25.0.1 - - [Thu, 14 Apr 2022 10:38:20 GMT] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:38:53.325 INFO  LoggerHandlerImpl - 172.25.0.1 - - [Thu, 14 Apr 2022 10:38:53 GMT] "GET / HTTP/1.1" 200 4647 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:38:53.715 INFO  LoggerHandlerImpl - 172.25.0.1 - - [Thu, 14 Apr 2022 10:38:53 GMT] "GET /css/chunk-vendors.101fdb7d.css HTTP/1.1" 200 115694 "https://www.xxxxx.com/reader/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:38:53.733 INFO  LoggerHandlerImpl - 172.25.0.1 - - [Thu, 14 Apr 2022 10:38:53 GMT] "GET /css/app.0dccd3ad.css HTTP/1.1" 200 4916 "https://www.xxxxx.com/reader/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:38:53.748 INFO  LoggerHandlerImpl - 172.25.0.1 - - [Thu, 14 Apr 2022 10:38:53 GMT] "GET /js/chunk-vendors.352edeae.js HTTP/1.1" 200 671286 "https://www.xxxxx.com/reader/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:38:53.762 INFO  LoggerHandlerImpl - 172.25.0.1 - - [Thu, 14 Apr 2022 10:38:53 GMT] "GET /js/app.33656218.js HTTP/1.1" 200 58779 "https://www.xxxxx.com/reader/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:38:54.427 WARN  LoggerHandlerImpl - 172.25.0.1 - - [Thu, 14 Apr 2022 10:38:54 GMT] "GET /3/getUserInfo HTTP/1.1" 404 53 "https://www.xxxxx.com/reader/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:38:54.433 INFO  LoggerHandlerImpl - 172.25.0.1 - - [Thu, 14 Apr 2022 10:38:54 GMT] "GET /css/index.0ce29b06.css HTTP/1.1" 200 26695 "https://www.xxxxx.com/reader/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:38:54.442 INFO  LoggerHandlerImpl - 172.25.0.1 - - [Thu, 14 Apr 2022 10:38:54 GMT] "GET /js/index.1854783d.js HTTP/1.1" 200 120824 "https://www.xxxxx.com/reader/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:38:54.742 INFO  LoggerHandlerImpl - 172.25.0.1 - - [Thu, 14 Apr 2022 10:38:54 GMT] "GET /img/icons/apple-touch-icon-152x152.png HTTP/1.1" 200 10730 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:38:54.823 INFO  LoggerHandlerImpl - 172.25.0.1 - - [Thu, 14 Apr 2022 10:38:54 GMT] "GET /img/icons/favicon-16x16.png HTTP/1.1" 200 1031 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:38:55.044 WARN  LoggerHandlerImpl - 172.25.0.1 - - [Thu, 14 Apr 2022 10:38:55 GMT] "GET /3/getBookshelf?refresh=0 HTTP/1.1" 404 53 "https://www.xxxxx.com/reader/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:38:55.056 INFO  LoggerHandlerImpl - 172.25.0.1 - - [Thu, 14 Apr 2022 10:38:55 GMT] "GET /fonts/element-icons.535877f5.woff HTTP/1.1" 200 28200 "https://www.xxxxx.com/reader/css/chunk-vendors.101fdb7d.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:38:55.438 INFO  LoggerHandlerImpl - 172.25.0.1 - - [Thu, 14 Apr 2022 10:38:55 GMT] "GET /js/reader.4f77f7bf.js HTTP/1.1" 200 86923 "https://www.xxxxx.com/reader/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:38:55.453 INFO  LoggerHandlerImpl - 172.25.0.1 - - [Thu, 14 Apr 2022 10:38:55 GMT] "GET /css/reader.0f4efb18.css HTTP/1.1" 200 34079 "https://www.xxxxx.com/reader/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:39:20.280 WARN  LoggerHandlerImpl - 172.25.0.1 - - [Thu, 14 Apr 2022 10:39:20 GMT] "GET /getBookshelf?refresh=0 HTTP/1.1" 404 53 "https://www.xxxxx.com/reader/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
[vert.x-eventloop-thread-0] 18:39:49.221 ERROR RestVerticle - vertx exception: {}
java.lang.IllegalArgumentException: invalid version format: 'ZZÙÐ	
WZÛJØ´-¦Y¿ÞÐMBË:FÕ®3

**Comment by hectorqin** [comment]
估计是你的反向代理没配置好吧

**Comment by wclmgcd** [comment]
我用ip:4395访问也是一样，是不是后端没有填对？可是我看后端是绿色的正常的。还有这个8080的端口可不可以更改？我在另一台VPS 上部署，因为miniflux要占用8080端口，所以不成功

**Comment by hectorqin** [comment]
可以改的，使用  java -jar build/libs/reader-$version.jar  --reader.server.port=8080

**Comment by wclmgcd** [comment]
> 可以改的，使用  java -jar build/libs/reader-$version.jar  --reader.server.port=8080 

感谢大佬，换用caddy2反向代理成功，不过在另一台VPS上，改端口不成功，找不到reader.jar的地址

**Comment by wclmgcd** [comment]
还有，大佬可以加入预读功能吗？就是阅读时提前自动缓存5章10章。 一般在海外的vps线路不好，所以增加阅读的连续性

**Comment by hectorqin** [comment]
java -jar  后面的路径，需要自行修改
 
 目前有缓存章节的功能，点击阅读进度显示缓存选项

**Comment by wclmgcd** [comment]
>  java -jar  后面的路径，需要自行修改
>  
>  目前有缓存章节的功能，点击阅读进度显示缓存选项

感谢，是自己安装的Java版本低了
