### ISSUE TITLE
多端阅读时进度不同步问题

### ISSUE THREAD

**Issue by gavinliuisme** [hectorqin/reader#285]
阅读进度会存储在docker里以及浏览器本地存储default@readingRecent里

当本地存储存在default@readingRecent时会直接读取而不比较docker值

那就有存在一种情况，我A电脑阅读到100章，然后再到B电脑阅读到120章，那么再次回到A电脑阅读时显示已读到120章，但是点击会跳转到100章

建议比较两个地方的时间戳，取最新值

另建议在阅读到某一章底部时可以再次点击空格或pagedown键跳转下一章

**Comment by woliuguojian** [comment]
就是从书架进入也是一样会跳转到100章

**Comment by woliuguojian** [comment]
> 多端阅读时，建议从书架列表里面进入阅读，最近阅读是从本地存储读取的进度


就是从书架进入也是一样会跳转到100章

**Comment by woliuguojian** [comment]
docker v2.7.3-12200107 自用版

**Comment by woliuguojian** [comment]
> 你的版本是多少？
> 
> > 另建议在阅读到某一章底部时可以再次点击空格或pagedown键跳转下一章
> > 这个功能应该是有的哦

用鼠标点击翻页是会自动跳下一章，但是用键盘应该是没有

**Comment by woliuguojian** [comment]
> 方向键 下 可以翻页及跳章
嗯，方向下是可以的，建议空格和pagedown都加上

> 刷新页面应该会获取最新章节吧
并不会，书架显示是最新章，但是点击会读取default@readingRecent还是会跳100章

**Comment by woliuguojian** [comment]
![image](https://user-images.githubusercontent.com/34774269/209095666-eac07a4e-d5d1-4d1f-8d6c-a38541a51a19.png)

**Comment by woliuguojian** [comment]
> ![image](https://user-images.githubusercontent.com/34774269/209095666-eac07a4e-d5d1-4d1f-8d6c-a38541a51a19.png)

在这个页面我从书架点击就会跳转第25章，而不是第30章，会不会是我的书籍来也是通过txt导入的缘故呢

**Comment by woliuguojian** [comment]
![gaollg0](https://user-images.githubusercontent.com/34774269/209098204-06d652a5-cbab-4f3e-9cc6-3b40445e3639.GIF)

**Comment by woliuguojian** [comment]
![image](https://user-images.githubusercontent.com/34774269/209103603-b5910caf-4a95-4592-8089-b9262fe1c48b.png)
![image](https://user-images.githubusercontent.com/34774269/209103699-a854b681-feaa-4779-9443-0b9c7bb598c3.png)
![image](https://user-images.githubusercontent.com/34774269/209103866-7e48d5e8-951e-440f-9c79-551074df5903.png)

**Comment by woliuguojian** [comment]
![image](https://user-images.githubusercontent.com/34774269/209105100-d539b7e8-6f4c-4c8d-86f6-da4e732b12b1.png)

saveBookProgress这里index:327就是第25章

**Comment by Dnine7** [comment]
我用服务器部署的 也存在多端阅读进度不同步的问题

**Comment by Dnine7** [comment]
浏览器添加书籍阅读第一章节 然后IOS端阅读到第七章后
![2e00c770929391fdd1cfb3798b4465c](https://github.com/hectorqin/reader/assets/107341308/9c26f840-654f-4f19-8269-1dff161d661d)
![d8439f1cc2311953cabdefb1cccbb4d](https://github.com/hectorqin/reader/assets/107341308/cc6ac27a-9e84-4535-abdc-0f1bf6c2ab38)
点击书籍进入
![193c9b71a10628a727853b237728ff2](https://github.com/hectorqin/reader/assets/107341308/7ece179d-ce83-4f9d-a8fa-890949302afe)
是否是取得本地缓存里的index呢？

**Comment by Dnine7** [comment]
有刷新页面 点击书的标题进入的

**Comment by Dnine7** [comment]
刚才又测试了一下 刷新页面没用 要点右上角的那个刷新 再进阅读页面 就可以同步了
