### ISSUE TITLE
Kindle 端问题反馈贴

### ISSUE THREAD

**Issue by hectorqin** [hectorqin/reader#326]
v3.0.0 开始新增了 `simple-web` 简易UI，用于支持 `kindle` 访问，访问路径 `http://ip:端口/simple-web/`。
欢迎大家在这里积极反馈问题！

**Comment by dushu8** [comment]
碰到了几个问题
1.http://ip:端口/simple-web/ 这个链接结尾必须有个/，开始没加，显示  Resource not found，如果能自动跳转到正确页面就更好了
2.我的是kindle Oasis，打开后，一直显示 “正在获取书记信息...请稍后”，不能正确的跳转到登录或者菜单去，电脑上、手机上都能正常跳转
3.手机上使用后，书籍列表最近在看的都会在最后一页，能调整一下就好了

**Comment by dushu8** [comment]
> 1、下个版本添加 2、试试 `https://reader.htmake.com/simple-web/` 3、之后会优化的
> 
> > 碰到了几个问题 1.[http://ip:端口/simple-web/](http://ip:%E7%AB%AF%E5%8F%A3/simple-web/) 这个链接结尾必须有个/，开始没加，显示 Resource not found，如果能自动跳转到正确页面就更好了 2.我的是kindle Oasis，打开后，一直显示 “正在获取书记信息...请稍后”，不能正确的跳转到登录或者菜单去，电脑上、手机上都能正常跳转 3.手机上使用后，书籍列表最近在看的都会在最后一页，能调整一下就好了
> > 我的环境是在docker下安装的，以上问题，我在你的测试链接 https://reader.htmake.com/ 上发现是一样的

我是用`https://reader.htmake.com/simple-web/`站点试过的，效果一样，一直显示 “正在获取书记信息...请稍后”

**Comment by dushu8** [comment]
v3.0.1版本问题反馈：
1. 关于http://ip:端口/simple-web/ 这个链接结尾必须有个/的问题，现在会强制跳转到加/的地址，但是你的这个地址https://reader.htmake.com/simple-web 这样输入会正常跳转到加/的地址并且正常访问，我的地址不会，我的地址是nginx代理出来一个端口，并且这个端口只能https访问，我看历史记录中，你会跳转到**http**://ip:端口/simple-web/，猜测跟这个有关
2. 现在可以正常登录并展示列表，但是，点击按钮【继续阅读】后会一直显示 “正在加载本章内容...”  ，同样的书，在电脑chrome浏览器中，会先显示“目录加载成功”，接着就会显示正常内容 ，你的地址和我的地址都是这样的

**Comment by wharry** [comment]
咪咕 kindle 内嵌的浏览器打开时，一直显示 “正在获取书记信息...请稍后”

**Comment by Aspirinea** [comment]
Kindle PW4 点击继续阅读后报错如下
![微信图片_20230401231030](https://user-images.githubusercontent.com/47356247/229297577-2df50cda-f869-44bf-8e9d-256713401451.jpg)

**Comment by soloyu** [comment]
刷新也不行

hectorqin ***@***.***> 于 2023年4月12日周三 16:05写道：

**Comment by HarveyZed** [comment]
书架没显示全，我总共12本书，只显示出来11本

**Comment by hubery055** [comment]
申请试用失败，发送验证码失败 Error: Request failed with status code 404
