### ISSUE TITLE
想装docker版本，怎么卸载桌面版

### ISSUE THREAD

**Issue by Animism001** [hectorqin/reader#33]
一开始装了桌面版，现在用虚拟机装了群晖，想安装docker版本的，要怎么才能访问虚拟机里面的docker版本啊？现在在电脑上打开localhost：8080，显示的还是原来的windows桌面版的，即使我把整个reader文件夹和java都删了还是可以访问，这是怎么回事啊，求救！！！我一开始是在笔记本上装的桌面版，然后苹果手机访问不了，后来又在台式机上装了桌面版，还是不行，然后现在用笔记本和台式打开localhost：8080，它们竟然各玩各的！！！笔记本打开的是之前在笔记本上配置好的reader，台式机打开的是台式机上配置好的，我软件快卸载了，怎么办？？？

**Comment by Animism001** [comment]
虚拟机访问的问题解决了，现在就想知道怎么卸载原先桌面版的残余了，TG群搜不到，不知道怎么加

**Comment by hectorqin** [comment]
桌面版的不是免安装的吗？把进程关了，直接删掉就行了啊

**Comment by Animism001** [comment]
我删了，连java都卸载了，还重启了几次电脑（win11 笔记本和台式都一样），但是在浏览器里（edge）输入localhost:8080还是可以进入web界面，v1.9.0-04070858

**Comment by Animism001** [comment]
我知道怎么回事了，删除之后还需要清除浏览器cookie，刚刚清楚了浏览器数据，就不能打开localhost:8080了

**Comment by hectorqin** [comment]
这个是pwa模式的浏览器缓存
