### ISSUE TITLE
请问如何更改听书的语音与手机使用听书功能

### ISSUE THREAD

**Issue by zlw310282** [hectorqin/reader#34]
目前电脑可用的语音仅系统自带的，怎么能接入如百度、阿里等语音api，
另外手机上尝试了几个浏览器貌似暂不支持听书。
万分期待！

**Comment by xsix123** [comment]
使用edge浏览器就能用微软自己的tts了，有xiaoxiao可以用，还要啥自行车！

**Comment by zlw310282** [comment]
我这pc版的是Microsoft Huihui Desktop - Chinese (Simplified) ，嘿嘿嘿

**Comment by hectorqin** [comment]
手机浏览器的限制很大，不建议使用听书功能
