### ISSUE TITLE
Rss订阅失效

### ISSUE THREAD

**Issue by NatsumiXD** [hectorqin/reader#343]
```
org.xmlpull.v1.XmlPullParserException: No valid parser classes found in parameter classNames to newInstance() that contained ' org.kxml2.io.KXmlParser org.kxml2.io.KXmlSerializer '
```
测试rss:
https://www.zhihu.com/rss

**Comment by NatsumiXD** [comment]
几乎所有的rss都会报错（

**Comment by skeaven** [comment]
org.xmlpull.v1.XmlPullParserException: No valid parser classes found in parameter classNames to newInstance() that contained ' org.kxml2.io.KXmlParser org.kxml2.io.KXmlSerializer '
