### ISSUE TITLE
如何将nas中已有的书籍导入书架

### ISSUE THREAD

**Issue by xsix123** [hectorqin/reader#35]
我是在群晖的docker中安装的，以前下载的书籍都存在群晖里，怎么能直接将其批量导入到书架中？基本都是txt格式。

**Comment by hectorqin** [comment]
web页面导入，支持多选的

**Comment by hectorqin** [comment]
有空可以考虑加这个功能

**Comment by hectorqin** [comment]
新版已支持本地书仓功能，将 nas 小说目录挂载到 `storage/localStore`，即可在本地书仓页面选择加入书架
