### ISSUE TITLE
用户上限问题。

### ISSUE THREAD

**Issue by bbsx123** [hectorqin/reader#359]
用户上限只能15人，不管怎么改都会自动变成15人。那个授权按钮点击查看后就会马上变成原来的15人，给一些朋友都注册不进去，说已经达到上限了。更新秘钥随便写就报错。javax.crypto.BadPaddingException: Decryption error。
我是docker部署的，READER_APP_USERLIMIT设置没用。请大兄弟看看是什么问题。

**Comment by yanglihao347** [comment]
同问，之前50人还好说，现在身边几个朋友都不够用了 QAQ~

**Comment by yangxq1995** [comment]
有收费版了吗 也没看到相关链接啊
