### ISSUE TITLE
请问能自动加载下一章和缓存无效

### ISSUE THREAD

**Issue by Silentely** [hectorqin/reader#36]
希望能增加自动加载下一章的功能，每次看完本章都需要点加载下一章太麻烦了；
我看这个变量cacheChapterContent=true 缓存章节内容，我在创建docker容器时添加以下变量
-e READER_APP_CACHECHAPTERCONTENT=true
但是并没有生效，想问下docker容器是这样操作么？

**Comment by hectorqin** [comment]
cacheChapterContent=true   这个配置是缓存缓存章节内容到服务器

上下翻页模式的自动加载下一章可以考虑加一下，但是会有一些问题，比如章节进度等

**Comment by Silentely** [comment]
> 

非常感谢、可以设置个开关 开启自动加载下一章就隐藏掉章节进度等会出问题的功能、也算是给一个选择吧

**Comment by hectorqin** [comment]
新版已支持自动缓存下一章
