### ISSUE TITLE
webdav无法设置，登录界面循环

### ISSUE THREAD

**Issue by Animism001** [hectorqin/reader#37]
输入IP:端口/reader3/webdav之后提示登录，输入用户/密码之后又重新弹出登录界面，手机上试过也是不行，不知道怎么回事，多用户环境，用户什么的也是要文档要求设置的，用的是虚拟机群晖+docker版本

**Comment by qiebu3509** [comment]
webdav没开，加载用户空间输入密码。进入管理，在管理用户空间里把用户的webdav开了
