### ISSUE TITLE
请教大佬有没有可能支持笔记和添加书签功能？

### ISSUE THREAD

**Issue by toyqiu** [hectorqin/reader#377]
只有这个遗憾了，太强大了！已经完全放弃阅读类 app 了。

**Comment by toyqiu** [comment]
> 书签功能有的啊，笔记可以暂时用书签代替，就是界面上不怎么好展示

请恕我愚钝，冒昧求教一下怎么使用书签功能？
![image](https://github.com/hectorqin/reader/assets/479873/b2ce1d00-7ccf-4047-921e-74c11682de0f)

我试来试去，好像只能导入某种文件，并不能把当前页面添加书签。

**Comment by Joe-2002** [comment]
请问是否还有机会支持 笔记or标注 功能 以及标注的导出
