### ISSUE TITLE
不支持 adoptOpenJDK ?

### ISSUE THREAD

**Issue by lwsgh** [hectorqin/reader#38]
![image](https://user-images.githubusercontent.com/15621914/163906003-27cbeca8-41e9-4156-ae66-a8cc43d84e9e.png)

**Comment by hectorqin** [comment]
可能是你环境变量没配置好？不过最好还是用 oracle jdk

**Comment by lwsgh** [comment]
环境变量没问题, 其它程序都可以, 只有 reader 报错

**Comment by hectorqin** [comment]
尝试用命令行启动吧

**Comment by hectorqin** [comment]
docker镜像用的就是 openjdk，是不是你的jdk版本太低

**Comment by lwsgh** [comment]
命令行启动没有问题
exe 执行有问题, 版本8~17都试了, 全部不好用

**Comment by hectorqin** [comment]
那就用命令行启动吧，可以自己写个bat命令。应该是你的环境变量配置有问题
