### ISSUE TITLE
ios手机不能记住阅读位置

### ISSUE THREAD

**Issue by iowong** [hectorqin/reader#380]
只能记住某一章 不能记住具体位置  比如第二章看到一半 再打开就会跳到第二章开始

**Comment by iowong** [comment]
> 什么翻页方式？

上下滚动

**Comment by iowong** [comment]
> 什么翻页方式？

docker部署  web访问的

**Comment by brydio** [comment]
上次保存的阅读偏好设置也会丢失，每次都需要手动恢复一下
