### ISSUE TITLE
打开页面和导入书源时接口报错 io.vertx.core.json.DecodeException: Failed to decode:No content to map due to end-of-input

### ISSUE THREAD

**Issue by fxxisme** [hectorqin/reader#392]
使用脚本一键部署的，镜像是openj9
![image](https://github.com/hectorqin/reader/assets/39211654/cccd54ee-3ade-448b-8b47-93deead62ba2)

**Comment by fxxisme** [comment]
管理模式下删除缓存就好了

**Comment by SouLXH** [comment]
是去 【数据目录管理】中删除cache吗，我删除了 还是不行

**Comment by fxxisme** [comment]
> 是去 【数据目录管理】中删除cache吗，我删除了 还是不行

是的，里面的都删掉，本地缓存也可以清除下
