### ISSUE TITLE
在railway平台部署后过一会就崩溃了

### ISSUE THREAD

**Issue by Lizihao233** [hectorqin/reader#399]
部署日志一直显示[main] INFO com.htmake. reader .ReaderApplication - Starting application with args:

**Comment by Amarterlus** [comment]
是的 我这也这样
c.htmake.reader.ReaderApplicationKt - No active profile set, falling back to default profiles: default
com.htmake.reader.ReaderApplication - Starting application with args: []

**Comment by Lizihao233** [comment]
感觉问题可能出在部署文件里这段命令上
“RUN \
    rm src/main/java/com/htmake/reader/ReaderUIApplication.kt; \
    gradle -b cli.gradle assemble --info; \
    mv ./build/libs/*.jar `./build/libs/reader.jar”
我感觉问题可能出在这个reader.jar的文件上了，或者ReaderApplication.kt上

**Comment by Lizihao233** [comment]
![FF828D40-2C79-474A-81E7-7BBD3ABBEFDF](https://github.com/hectorqin/reader/assets/100866782/550f9ac1-e1ca-49f4-aefb-163b88931ba5)

**Comment by Lizihao233** [comment]
目前最新的情况，日志比之前多了一些内容![90C1D4CA-920C-4111-938A-8AE250029A78](https://github.com/hectorqin/reader/assets/100866782/f73bbc56-3be5-45a0-b02d-fa05bbd12f0d)

**Comment by Lizihao233** [comment]
我删掉项目之后重新部署的，书源还没加呢

**Comment by Lizihao233** [comment]
这个地方点了没反应

**Comment by Lizihao233** [comment]
三个点哪个位置是重启，重新部署和移除，左下角显示来自副本的日志点了没有反应，每次部署完三五分钟就会崩溃，环境变量我就设置了一个8080端口和READER_APP_SECURE 
![40AD3BE0-7E8E-40FD-99E9-79FB64F893FE](https://github.com/hectorqin/reader/assets/100866782/72c7d00c-6002-4366-9855-62855e7672c7)
，

**Comment by 1x2y3zz** [comment]
我用arch的nerdctl compose部署也有这样的bug，但之前用Ubuntu nerdctl compose就没有这样的问题，两个系统甚至装在同一个电脑上
