### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by ifwlzs** [hectorqin/reader#4]
1. 背景太少，希望可以用户自行选择放在对应图片文件夹里
2. 宽度选择太少，建议增加1120px,1280px等等（我看他各档差值都是160px）（可能会有用手机打开的情况，值得考虑）
3. 字体颜色希望能用户自定义
4. win的启动，，，这个窗体白板也太大了把，建议搞成启动后不显示窗体，直接缩到小控制栏里，且仅显示图标。
5. 看书的页面，标题可以改成书名或者章节名
6. 页面工具栏，左右栏可以根据用户需求设置当前样式或者上下浮动的横条
7. 配置可以考虑用户自己编辑json配置文件，或者窗体内添加各种设置选项（win端）。或者在首页设置

**Comment by hectorqin** [comment]
第四点是什么意思？能截个图吗？

**Comment by ifwlzs** [comment]
> 第四点是什么意思？能截个图吗？

启动过程：
![GIF 2021-9-7 10-31-15](https://user-images.githubusercontent.com/49548316/132275244-f10243f1-727d-4e5c-9ec2-12af9cfa8f18.gif)


我的意思是这个主界面默认是不显示的，像火绒那样隐藏到控制栏这里,可以点击小图标打开这个窗口

![image](https://user-images.githubusercontent.com/49548316/132274745-41cb05e4-71d3-4af2-ad69-4754d9e01ce1.png)

![image](https://user-images.githubusercontent.com/49548316/132274929-b93636db-e086-441d-8863-964d360be8de.png)
![image](https://user-images.githubusercontent.com/49548316/132274980-8baf6505-7977-489f-86db-94a87097b6af.png)

**Comment by hectorqin** [comment]
新版已支持这些功能
