### ISSUE TITLE
web端可以考虑增加定时备份webdav的功能

### ISSUE THREAD

**Issue by sundaqiang** [hectorqin/reader#40]
web端可以考虑增加定时备份webdav的功能

**Comment by hectorqin** [comment]
这个功能没有多大必要

**Comment by sundaqiang** [comment]
> 这个功能没有多大必要

webdav主要就是为了和阅读app同步，如果需要看完关网页前手动点备份webdav。那么这个意义也就不是很大了。定时备份也只是用js控制，实际上对服务端并没有很大的性能消耗。

**Comment by hectorqin** [comment]
书籍阅读进度是实时同步的，只有书籍分组，书架书籍，书源等需要手动备份。主要是因为服务器端和阅读app还是有区别的，无法同步本地书籍的，webdav更多是为了方便的从app迁移过来
