### ISSUE TITLE
导入本地书源报错

### ISSUE THREAD

**Issue by a512154224** [hectorqin/reader#41]
![image](https://user-images.githubusercontent.com/28529130/164627363-fdaaf669-fa9c-49e4-bead-76a5094b074a.png)

**Comment by hectorqin** [comment]
提供一下日志和网络请求截图

**Comment by a512154224** [comment]
想通过webdav的方式还原，但是app3.0提示无法连接webdav

**Comment by hectorqin** [comment]
看看接口日志

**Comment by hectorqin** [comment]
webdav 需要进入用户管理界面开启webdav功能

**Comment by a512154224** [comment]
你好，自用版如何进入用户管理界面开启webdav

**Comment by hectorqin** [comment]
自用版默认开启

**Comment by a512154224** [comment]
但是我用阅读3.0app设置webdav备份，备份时提示连接失败
webdav服务器：http://10.80.2.102:8080/reader3/webdav/
用户名：default
密码：123456

**Comment by hectorqin** [comment]
提供一下接口日志

**Comment by a512154224** [comment]
> 提供一下接口日志
#
[Uploading reader-2022-04-25.0.log…]()

**Comment by a512154224** [comment]
[reader-2022-04-25.0.log](https://github.com/hectorqin/reader/files/8551422/reader-2022-04-25.0.log)

**Comment by hectorqin** [comment]
看到有备份请求，去看看 storage/data/default/webdav 里面有没有文件吧

**Comment by a512154224** [comment]
> 看到有备份请求，去看看 storage/data/default/webdav 里面有没有文件吧

webdav下生成了一个legado/bookProgress 两个目录，但是内容是空的，备份时是提示failed to connect to 10.80.2.102:8080

**Comment by hectorqin** [comment]
你这上面的日志怎么不完整

**Comment by adl10929** [comment]
出现同样问题，导入书源失败，default/webdav这两个文件都没有

**Comment by zwb124** [comment]
我也是导入书源失败，单用户多用户都这样

**Comment by hectorqin** [comment]
提供一下日志吧

**Comment by zwb124** [comment]
> 提供一下日志吧

我直接把书源文件给拷贝到目录里了，就行了
[reader-2022-05-24.0.log](https://github.com/hectorqin/reader/files/8760220/reader-2022-05-24.0.log)

**Comment by zwb124** [comment]
对了，跟之前用railway时一样，epub是不能导入的，感觉是对epub格式的识别问题

**Comment by hectorqin** [comment]
没有发现书源导入出错的日志，epub导入出错是格式问题，这个以后有空会优化的

**Comment by zwb124** [comment]
> 没有发现书源导入出错的日志，epub导入出错是格式问题，这个以后有空会优化的

我也不知道，就是点导入书源没有任何反应，能识别出来书源列表，但就是导入没反应，迫不得已直接拷贝到服务器上了
