### ISSUE TITLE
docker webdav 多用户环境变量版本 405

### ISSUE THREAD

**Issue by Saszr** [hectorqin/reader#42]
用户已开 webdav ，用户登陆 webdav

<img width="494" alt="image" src="https://user-images.githubusercontent.com/22406550/164896176-b423f42a-bc7c-41fc-b429-7c99f43f46e7.png">

另外 tg 链接挂了，用户不存在

**Comment by hectorqin** [comment]
webdav不支持浏览器访问，tg群已关闭
