### ISSUE TITLE
arm，docker部署内存泄露严重

### ISSUE THREAD

**Issue by dawei233** [hectorqin/reader#43]
cpu99 内存蹭蹭蹭往上涨，一晚上涨了6.2g占用 ，cpu全程99

就拉下来镜像然后启动后建了俩账号就啥都没动了

**Comment by dawei233** [comment]
不知道其他人有这个毛病吗
今天重启以后还是这样 cpu 99 内存肉眼可见上涨

**Comment by hectorqin** [comment]
看看接口日志

**Comment by dawei233** [comment]
![image](https://user-images.githubusercontent.com/31338729/164954056-e3af630f-b848-47ac-b842-2140bbd2831a.png)
超级大等我下载一个看看

**Comment by dawei233** [comment]
[首尔ARM2C24T_reader-2022-04-24.0.log](https://github.com/hectorqin/reader/files/8548953/ARM2C24T_reader-2022-04-24.0.log)

**Comment by hectorqin** [comment]
不知道你的服务器是被人攻击了还是怎么的，访问的域名是  http://www.pn637.cn:9756

**Comment by dawei233** [comment]
> 不知道你的服务器是被人攻击了还是怎么的，访问的域名是 http://www.pn637.cn:9756

一脸懵逼，是这个服务被攻击吗，我关掉就好了，额昨天才开始搞的， 就有人攻击我头疼

**Comment by NZESupB** [comment]
估计ip+默认8080端口被人扫段直接cc攻击了.换个端口或者用nginx域名强制ssl试试吧.

**Comment by dawei233** [comment]
> 估计ip+默认8080端口被人扫段直接cc攻击了.换个端口或者用nginx域名强制ssl试试吧.

好的我用caddy上个ssl
