### ISSUE TITLE
导出为epub格式，实际下载的是TXT（另外包含关于书仓的一点建议）

### ISSUE THREAD

**Issue by fireflyfeihuo** [hectorqin/reader#432]
部署环境：群晖6.23 docker部署
部署版本：v3.2.5-08170832
在书籍管理-导出中选择导出为epub，实际浏览器下载的是txt文档
（这个书籍是我本地导入的，导入的时候用的是TXT）
请问这个导出为epub是只能导出原本就是epub格式的书籍吗？还是确实是一个BUG
另外，既然有书仓功能，建议在删除书架的时候可以保留书籍的封面简介等信息，这样书仓里面的书籍如果是txt格式就可以自动匹配了，不用重新设置

**Comment by fireflyfeihuo** [comment]
最后能不能加一个评分和读后感，这样方便读完后回顾这个小说怎么样
封面、简介、评分和读后感可以保存在本地，用书名（文件名）进行匹配？

**Comment by fireflyfeihuo** [comment]
> 书仓的优化暂时还没想好，评分和读后感好像不太适合网文？

我是觉得既然有书仓这个功能，肯定是往书籍管理方面去做的。
现在的我是手动给书加了分组，比如好书，一般、垃圾等，用来区分，但是加上评分功能，就能直白的搜索评级来判断自己当时觉得好不好看了
读后感也可以看做评论，对于我这种个人用户来说，可以看看自己读完的想法，因为时间久了，记忆也会模糊，多人共同使用的话评论就更有趣了
我之前使用的小说刮削项目就是有评分和评论的（会自动从豆瓣、龙空刮削），但那个项目每个网站都得自己写脚本，我就放弃了
现在这个阅读可以导入书源就方便很多，如果加上评分和评论就可以当自己的书库了，我是重度爱好者，看的小说也超过，有些零几年的书网上都不太找到了，我才准备把他们都保存下来

另外，如果能加上转换epub就好了，毕竟封面和目录都做了，不转浪费，当然这属于锦上添花，没有也不影响使用

**Comment by zushl** [comment]
> > 书仓的优化暂时还没想好，评分和读后感好像不太适合网文？
> 
> 我是觉得既然有书仓这个功能，肯定是往书籍管理方面去做的。 现在的我是手动给书加了分组，比如好书，一般、垃圾等，用来区分，但是加上评分功能，就能直白的搜索评级来判断自己当时觉得好不好看了 读后感也可以看做评论，对于我这种个人用户来说，可以看看自己读完的想法，因为时间久了，记忆也会模糊，多人共同使用的话评论就更有趣了 我之前使用的小说刮削项目就是有评分和评论的（会自动从豆瓣、龙空刮削），但那个项目每个网站都得自己写脚本，我就放弃了 现在这个阅读可以导入书源就方便很多，如果加上评分和评论就可以当自己的书库了，我是重度爱好者，看的小说也超过，有些零几年的书网上都不太找到了，我才准备把他们都保存下来
> 
> 另外，如果能加上转换 epub 就好了，毕竟封面和目录都做了，不转浪费，当然这属于锦上添花，没有也不影响使用

强烈要求加上刮削，现在看的书手动换个源就能有封面之类，但是总归是不方便
