### ISSUE TITLE
搜书的时候点书或加入书架都会报错

### ISSUE THREAD

**Issue by Dxrrrrrr** [hectorqin/reader#439]
搜书点开书和加入书架就会报错
com.script.ScriptException: org.mozilla.javascript.EcmaError: ReferenceError: "Base64" is not defined. (#1(eval)#12) in #1(eval) at line number 12
docker-comp部署

**Comment by Dxrrrrrr** [comment]
![image](https://github.com/hectorqin/reader/assets/23625406/e9c04987-11b5-4910-9792-a80320cc3b0a)

**Comment by Dxrrrrrr** [comment]
![image](https://github.com/hectorqin/reader/assets/23625406/0fbe1484-6d71-4b65-a230-348c67814d46)

**Comment by hectorqin** [comment]
书源不兼容
