### ISSUE TITLE
配置书源太麻烦太繁琐

### ISSUE THREAD

**Issue by huguangjun580** [hectorqin/reader#442]
docker版本安装之后，书源可以从官网示例导出，再导入到本地。麻烦的就是自定义添加书源，这个地方的操作，愣是没看懂是什么规则该如何配置其它网址，即使加进去了似乎也不管用（没反应）。所以说这个地方太繁琐、麻烦。

**Comment by hectorqin** [comment]
添加书源订阅，点击同步书源
