### ISSUE TITLE
element的dialog问题

### ISSUE THREAD

**Issue by kukume** [hectorqin/reader#443]
大佬能不能把dialog设置一下close-on-click-modal。
用电脑，每次稍微点一下，dialog就退出了。

**Comment by hectorqin** [comment]
点击背景是会关闭弹窗的

**Comment by kukume** [comment]
可以改成点击背景不关闭弹窗吗？或者可以提供个开关吗？

**Comment by hectorqin** [comment]
这个以后有空加个设置吧

**Comment by miaowmint** [comment]
不止点击背景是会关闭弹窗；在弹窗里点击，鼠标移动到弹窗外，再松开，也会关闭弹窗，这就导致我登录的时候总是不小心把登录弹窗误关掉TvT

**Comment by hectorqin** [comment]
这个，或许你该换个鼠标了。。

**Comment by miaowmint** [comment]
> 这个，或许你该换个鼠标了。。

你没有这个情况吗？我在所有自建以及其他人的reader里都有这个问题
至于换鼠标。。。难以想象会有这方面的原因，我两个月之前刚换的罗技G502X lightspeed

另附视频
https://github.com/hectorqin/reader/assets/58991169/4e476694-f314-42e9-9690-43ef0df57be9

**Comment by kukume** [comment]
我也是有这个问题，所以我想不让点击其他地方关掉弹窗

**Comment by miaowmint** [comment]
> 我也是有这个问题，所以我想不让点击其他地方关掉弹窗

点击背景关闭弹窗我觉得没问题，但是我拖动的时候不小心鼠标移出去了也会关闭探窗就很糟心了

**Comment by miaowmint** [comment]
另外在电脑浏览器阅读的时候如果不小心选中了一部分文字就会自动跳出来操作页

![image](https://github.com/hectorqin/reader/assets/58991169/36e0db3c-63b9-4c0f-b41e-66af2bdc3982)

而这个页面却不能通过点击背景关闭弹窗，而是必须要点到 X 上才能关闭，我个人来说觉得有点不顺手，建议这个弹窗也可以点击背景关闭

另附视频
https://github.com/hectorqin/reader/assets/58991169/3fbdfb75-5465-4e2b-ad01-964057ab2d69

**Comment by hectorqin** [comment]
可以关闭选择文字后的操作

**Comment by hectorqin** [comment]
用到鼠标的情况应该是比较少的，阅读时翻页可以使用快捷键。另外，拖动鼠标的时候为啥会按住左键？
