### ISSUE TITLE
手机版的chrome使用bug

### ISSUE THREAD

**Issue by kukume** [hectorqin/reader#444]
在手机版的chrome，上滑和下滑，相应的顶栏会隐藏或者出现，在顶栏隐藏或者出现之后且手离开屏幕时，滚轮会乱动，会出现异常情况（不会用文字来描述）。
https://minio.kuku.me/kuku/screen-20231003-190147.mp4
见此视频

**Comment by hectorqin** [comment]
建议添加为pwa应用再使用，顶部栏的出现和隐藏是浏览器控制的，顶部栏的出现和隐藏会影响浏览器的视口变化，导致页面重新计算渲染

**Comment by kukume** [comment]
这个可以修复吗？阅读app的网页版是没有这个问题的

**Comment by hectorqin** [comment]
这不是bug，不会修复

**Comment by kukume** [comment]
高度变化为什么需要重新渲染呢？就拿github来说，高度变化页面是没有变化的，只有宽度变化才会自适应
