### ISSUE TITLE
替换规则的替换范围能否改成可以支持全局

### ISSUE THREAD

**Issue by kfab1983** [hectorqin/reader#447]
目前添加替换时，替换范围里填写的是 ：
书名；目录页网址，只在特定网站的特定某本小说生效。
也可以省略；目录页网址，在特定书名的小说都生效。
但是无法同时省略书名和目录地址，会提示替换范围不能为空，也就是无法全局生效。

能否支持全局？

**Comment by hectorqin** [comment]
使用*号看看

**Comment by kfab1983** [comment]
> 使用*号看看

用*号可以点确定，但实际不生效。
