### ISSUE TITLE
eval不可用

### ISSUE THREAD

**Issue by gjmhmm8** [hectorqin/reader#451]
获取章节内容失败！

com.script.ScriptException: org.mozilla.javascript.EcmaError: SyntaxError: syntax error (#2(eval)#9) in #2(eval) at line number 9
3.26

**Comment by hectorqin** [comment]
仔细检查一下书源的js语法

**Comment by gjmhmm8** [comment]
我在阅读3没问题，但是到这里就用不了，eval函数执行错误，和语法没关，大概率是你js引擎或者配置的问题
