### ISSUE TITLE
删除失效书源报错

### ISSUE THREAD

**Issue by lukemin** [hectorqin/reader#455]
**为避免无效问题和冗余问题，提问前请确认**
1. 你确定Google不能解决你的问题
2. 你确定已有的issue不能解决你的问题
3. 你确定issue的title按照格式如下：[web/simple-web/server]：description

**Describe the bug 描述你遇到的问题**
A clear and concise description of what the bug is.  简洁有效的说明。
删除失效书源报错
**To Reproduce 如何重现问题**
Steps to reproduce the behavior:  把你遇到的问题的发生步骤替换掉下面的内容：
检测失效书源，批量删除时报错。

**Expected behavior  期待修复的效果**
A clear and concise description of what you expected to happen. 简单描述。

**Screenshots 如有必要，可以截图说明**
![1699324093482](https://github.com/hectorqin/reader/assets/12003375/99c5ade1-6518-4f64-80b2-6c56b1fbe293)

**版本说明**
 - OS: [e.g. win]  说明操作系统  ubuntu 20
 - Deploy Method 说明软件部署方式 docker
 - Program Version 说明软件版本 v3.2.6-08280832
 - Browser [e.g. chrome, safari]  说明终端、浏览器型号 edge

**Additional context 其他说明**
Add any other context about the problem here. 添加你认为有必要的内容，否则不写。

**Comment by Arvinsyt** [comment]
一样，批量删除时就报这个错误，但单个删除就没问题

**Comment by hectorqin** [comment]
嗯，批量删除是有个bug

**Comment by caliban511** [comment]
我也一样，选了4个书源，然后批量删除，结果批量删除了4次才删完，，，😂😂😂
