### ISSUE TITLE
移动端 “未配置书源” 错误

### ISSUE THREAD

**Issue by CEX68** [hectorqin/reader#458]
**To Reproduce 如何重现问题**
移动端刷新就会显示 “未配置书源”。选择一个书源后就可以正常显示了。

https://github.com/hectorqin/reader/assets/115330187/afb24c43-07b8-452b-bf22-bb0d739746be

PC 端刷新没有这个问题。
删除 storage 文件夹，重启 docker 不能修复。
运行在付费 VPS 而不是 #121 中的 railway 上。

**版本说明**
 - OS: [e.g. win]  IOS
 - Deploy Method Docker
 - Program Version v3.2.6-08280831
 - Browser Chrome

**Comment by hectorqin** [comment]
是怎么加入书架的？

**Comment by CEX68** [comment]
> 是怎么加入书架的？

通过 “搜索书籍”

**Comment by hectorqin** [comment]
是不是加入书架之后删除了这个书源？

**Comment by CEX68** [comment]
> 是不是加入书架之后删除了这个书源？

没有
