### ISSUE TITLE
未登录情况下显示内容过多

### ISSUE THREAD

**Issue by carolcoral** [hectorqin/reader#459]
## 版本信息
* v3.2.6-08280832

## 问题描述
当用户未登录的时候可以完整查看 `书源设置` 、 `书架设置` 、 `最近阅读` 、 `后端设定` 等配置信息

## 期望

1. 当用户未登录的情况下，仅可以查看 `搜索` 、 `搜索设置`
2. 区分普通用户和管理员的显示权限：
    * 管理员：保持当前版本的显示内容
    * 普通用户：搜索、搜索设置、最近阅读、webdav

**Comment by hectorqin** [comment]
这些都是保存在本地的，不存在越权的情况

**Comment by carolcoral** [comment]
嗯，只是不想让普通用户能够看到这些信息，可以么🥹

通过环境变量直接设置管理员帐号，注册帐号全部都是普通用户，普通用户除了 `搜索` 外都无法查看，或者 `管理员` 可以控制普通用户的显示项

**Comment by TonyInTokyo** [comment]
最好有强制登录的选项， 不登录自己转登录界面才好。

**Comment by hectorqin** [comment]
以后有空再看吧

**Comment by hectorqin** [comment]
未登录会隐藏部分按钮

**Comment by carolcoral** [comment]
> 未登录会隐藏部分按钮

给大佬点赞
