### ISSUE TITLE
导入epub书籍提示不支持zip格式？

### ISSUE THREAD

**Issue by Timiyu** [hectorqin/reader#460]
<img width="1570" alt="image" src="https://github.com/hectorqin/reader/assets/17613068/160037da-dd62-46d9-92b9-fd3bfccf9fb2">

<img width="1681" alt="image" src="https://github.com/hectorqin/reader/assets/17613068/60177f7a-07bb-4df7-a636-27de43a66dc6">

**Comment by Timiyu** [comment]
<img width="596" alt="image" src="https://github.com/hectorqin/reader/assets/17613068/184b2752-708c-4f41-ba40-fe7df24ea964">

**Comment by hectorqin** [comment]
文件后缀名是不是zip？
