### ISSUE TITLE
希望修改书源获取时间的限制，现在的限制是10000ms，对于某些需要复杂解析的源太少了。

### ISSUE THREAD

**Issue by hubery055** [hectorqin/reader#470]
希望修改书源获取时间的限制，现在的限制是10000ms，对于某些需要复杂解析的源太少了。

很多第三方源需要复杂的替换，这需要时间，很明显10000ms的设置有些过于保守了，希望能给一个更长的时间，或者给一个自定义的机会。

**Comment by hectorqin** [comment]
什么场景？搜索？换源？

**Comment by coulsontl** [comment]
> 什么场景？搜索？换源？

@hectorqin  换源的时候我也遇到过这个问题，有一些书源是移动端网页获取完整的目录需要串行遍历请求好多个网页所以时间比较长；如果能自定义比较合理
