### ISSUE TITLE
大佬麻烦看一下阅读跳章的问题

### ISSUE THREAD

**Issue by 516966395** [hectorqin/reader#471]
大佬麻烦问一下上下滚动的方式会出现快到章节尾部的时候自动跳转到下一章的情况  这个问题频繁出现   ios 设备

**Comment by luochenbj** [comment]
我这边是用WIN PC端，窗口模式，空格键翻页，会不定期的出现敲击空格以后往下翻20-30个页面。

**Comment by hectorqin** [comment]
有空再看

**Comment by hectorqin** [comment]
空格键翻页应该是你装的浏览器插件吧？reader本身没有提供空格键翻页的功能
