### ISSUE TITLE
assets 绝对路径引用导致 书架设置>导入书籍 报错

### ISSUE THREAD

**Issue by greatbody** [hectorqin/reader#472]
**为避免无效问题和冗余问题，提问前请确认**
1. 你确定Google不能解决你的问题
2. 你确定已有的issue不能解决你的问题
3. 你确定issue的title按照格式如下：[web/simple-web/server]：description

**Describe the bug 描述你遇到的问题**
上传 UMD文件到书架失败。
**To Reproduce 如何重现问题**
1. Go to '书架设置，导入书籍'
2. 选择 umd 文件，上传
3. See error `java.io.FileNotFoundException: /assets/admin/book/喻世明言.umd (No such file or directory)`

**Expected behavior  期待修复的效果**
正常展示书籍。不报错。

**别的不说了，直接说出问题的地方**

src/main/java/io/legado/app/model/localBook/UmdFile.kt 文件中

```kotlin
    private fun readUmd(): UmdBook? {
        val input = File(book.bookUrl).inputStream()
        return UmdReader().read(input)
    }
```

`book.bookUrl` 看起来是给前端加载显示用的路径，拼接的是 '/assets/[user]/book/[bookfile]' 但是确误用了这个来读文件，导致加载失败。

对 kotlin 不熟悉，麻烦请修复。

**Comment by greatbody** [comment]
@hectorqin 大佬终于出现了，求修改。因为这个项目大佬现在是半开源，所以不清楚怎么改才能整个流程跑通，所以就没敢下手改。只粗略定位了一下似乎出 bug 的地方，还请海涵。

**Comment by hectorqin** [comment]
不错，应该就是这里，我周末看看有没有时间修复吧

**Comment by greatbody** [comment]
> 不错，应该就是这里，我周末看看有没有时间修复吧

@hectorqin 大佬记得来修哈

**Comment by hectorqin** [comment]
新版本已修复
