### ISSUE TITLE
bookshelf突然被清空

### ISSUE THREAD

**Issue by qiebu3509** [hectorqin/reader#473]
io.vertx.core.json.DecodeException: Failed to decode:Cannot deserialize instance of `java.util.ArrayList` out of VALUE_NUMBER_INT token at [Source: (String)"1 "; line: 1, column: 1]

bookshelf.json突然被清空导致无法正常，删除文件就正常，书架也就清空了。也不是第一次了

**Comment by hectorqin** [comment]
什么版本？

**Comment by qiebu3509** [comment]
> 什么版本？

镜像：hectorqin/reader:latest
版本是v3.2.6-08280832
多用户
只能APP备份还原bookshelf了

**Comment by tfei9** [comment]
解决没，我也报这个错，之前一直是好的，前几天突然报这个错。
群晖7.0docker

**Comment by qiebu3509** [comment]
> 解决没，我也报这个错误，一直都好，前几天突然报这个错误。 群晖7.0docker

你看一下你的bookshelf.json是不是清空了，如果是的话你可以在手机阅读APP备份，解压你的备份ZIP，然后还原bookshelf.json或删掉

**Comment by Akarin-o-o** [comment]
同样的问题，报错好久了，刚才上后台看bookshelf.json确实被清空了
