### ISSUE TITLE
密码设置在配置文件中改变最小长度。

### ISSUE THREAD

**Issue by macbie** [hectorqin/reader#476]
是否可以在配置文件中指定密码最小长度。
UserController.kt 中相关代码
        if (password.length < 8) {
            return returnData.setErrorMsg("密码不能低于8位")
        }
...

**Comment by greatbody** [comment]
我理解密码长度设置是合理的，用一个密码管理器来管理密码就好了。

**Comment by hectorqin** [comment]
试试新版本，新增参数  `reader.app.minUserPasswordLength=8`
