### ISSUE TITLE
[BUG]直接刷新网页无法显示

### ISSUE THREAD

**Issue by greatbody** [hectorqin/reader#477]
# 复现方式（网址套上了 Cloudflare CDN）
1. 打开一本小说，可以开始阅读
2. 刷新浏览器
# 现象
一直显示加载中，但是什么都没有
# 问题根因
初步猜测是没有处理好 react 的路由导致的。

# 问题
不知道大佬现在 docker 版的服务端的网页的代码是否完全开源了，如果开源了，我乐意试试改改。

**Comment by greatbody** [comment]
<img width="718" alt="image" src="https://github.com/hectorqin/reader/assets/6984599/1013c780-b2a3-476b-b099-74675a2bde24">

经过简单调试，发现直接 ip 访问和通过域名访问的一个区别在 autoShowPosition 这个函数在通过域名访问的时候会失败。由于代码有混淆，所以无法继续排查。 @hectorqin

**Comment by greatbody** [comment]
@hectorqin 大佬如果可以开源代码，方便大家提 PR

**Comment by hectorqin** [comment]
控制台有报错信息吗？

**Comment by greatbody** [comment]
大佬这个能修么？

**Comment by hectorqin** [comment]
> 大佬这个能修么？

复现不了，无法定位问题

**Comment by greatbody** [comment]
> > 大佬这个能修么？
> 
> 复现不了，无法定位问题

私信我，给大佬账户密码在我的网站上可以复现。

**Comment by hectorqin** [comment]
在公众号上私信我吧
