### ISSUE TITLE
Desktop版本启动闪退

### ISSUE THREAD

**Issue by tp1415926535** [hectorqin/reader#479]
**Desktop版本启动闪退**
安装后打开exe显示窗体"正在启动服务..."然后闪退了。并且安装后文件夹结构跟[文档](https://github.com/hectorqin/reader/blob/master/doc.md#windows--macos--linux)描述的不一样，并没有json配置：
- Reader Desktop
  - resources
    - reader.jar
  - Reader Desktop.exe
  - Uninstall Reader Desktop

**To Reproduce**
1. 安装[Reader.Desktop_3.2.7_x64_zh-CN.msi](https://github.com/hectorqin/reader/releases/download/v3.2.7/Reader.Desktop_3.2.7_x64_zh-CN.msi)
2. 启动 Reader Desktop.exe

**Screenshots**
![闪退Gif](https://github.com/hectorqin/reader/assets/58326584/59afe672-0959-4522-b8a9-e0bf68351840)

**版本说明**
 - OS: WIN10
 - Deploy Method: 安装
 - Program Version: 3.2.7_x64
 - Java:  版本8 更新271
![java](https://github.com/hectorqin/reader/assets/58326584/61ea1bf5-a056-400f-81c8-28e8dacb3bf4)

**Comment by hectorqin** [comment]
建议使用 `[reader-server-3.2.7.zip](https://github.com/hectorqin/reader/releases/download/v3.2.7/reader-server-3.2.7.zip)`
