### ISSUE TITLE
请问，如何退出正在使用的用户？

### ISSUE THREAD

**Issue by liuxiaoleo** [hectorqin/reader#48]
因为第一次登录的时候打勾了自动登录，所以一直都是自动登录用户。现在有其他设备想新建用户登录，留下自己的阅读记录，请问如何退出现有用户的登录？没找到哈。请大佬给说一下。

**Comment by hectorqin** [comment]
换个浏览器

**Comment by hectorqin** [comment]
Docker 新版已增加注销功能

**Comment by liuxiaoleo** [comment]
好的。谢谢。这就更新。
