### ISSUE TITLE
很卡

### ISSUE THREAD

**Issue by xzyl4303** [hectorqin/reader#483]
# 我是在vps上部署，打开后感觉很卡

 - OS: Linux
 - Deploy Method: Docker
 - Program Version: 3.1

**Comment by greatbody** [comment]
> # 我是在vps上部署，打开后感觉很卡
> * OS: Linux
> * Deploy Method: Docker
> * Program Version: 3.1

能提供详细的信息么，比如部署的服务器的规格，Docker 的资源占用情况。

如果能持续监测一段时间，观察资源占用随时间或者操作的变化就更好了。不过如果是启动后资源逐步占用增加，我记得作者此前都是建议频繁重启容器即可。
