### ISSUE TITLE
删除书源失败 Error: Network Error

### ISSUE THREAD

**Issue by Mabisi** [hectorqin/reader#485]
为什么删除失效的书源会提示这个错误？
一个一个删除倒是不会提示这个错误
![image](https://github.com/hectorqin/reader/assets/19968269/c8139f55-78d4-45d9-888e-cddb95089da4)

Docker部署
 - v3.2.7-01010833
容器没有错误日志

**Comment by hectorqin** [comment]
那有可能是网络问题
