### ISSUE TITLE
提问safari的缓存文件在那里？

### ISSUE THREAD

**Issue by zushl** [hectorqin/reader#488]
没找到讨论，只能发issue了
使用的docker-compose.yaml version: '3.1'
在ios 17.2上使用safari看小说，选择缓存章节，尝试脱离局域网环境，可以继续阅读，故请问，缓存目录在那里？又该如何删除？

**Comment by hectorqin** [comment]
浏览器的本地缓存，书架-书籍管理 这里可以删除缓存

**Comment by zushl** [comment]
> 浏览器的本地缓存，书架 - 书籍管理 这里可以删除缓存

找到了，感谢
