### ISSUE TITLE
reader在一些站抓到的内容是乱序的，，，

### ISSUE THREAD

**Issue by caliban511** [hectorqin/reader#489]
如题。
希望在界面里能加一个打开源页面的按钮。
因为69书吧系的网站，以69xinshu这个新启用域名为例，
最近用阅读和reader抓取到的新更新章节内容是乱序的，而直接去它网站看则没有问题。
试了下，过滤它的广告可以，但不能禁止主域名的js加载，否则就会乱序，，阅读和reader只是抓取文本，所以直接抓过来就是乱的，，，
因为目前还没有其它站能取代69书吧系的书站，所以希望大佬能给个打开它对应章节页面的按钮。
并且希望是新标签打开，而不是原标签跳转。
退一步讲，以后其他站说不定也会有什么骚操作，把原地址亮出来，也算是一个简单的解决方案吧。

阅读的界面上方会有原页面地址的显示，如下图所示。
但reader目前没有，，，

https://www.69xinshu.com/txt/46977/36928204
![Screenshot_2024-02-06-13-41-16-844-edit_io legado app release](https://github.com/hectorqin/reader/assets/13557387/75955305-4551-4e7b-acaa-87a5b74f5777)

如下图。
图里圈出的，就是禁用以后会导致乱序的那个JS脚本：

![Screenshot_2024-02-06-16-12-16-445-edit_org mozilla firefox](https://github.com/hectorqin/reader/assets/13557387/c1fbf7d9-a3cb-42f0-9c57-1d1f3853b820)

![Screenshot_2024-02-06-16-13-27-094-edit_org mozilla firefox](https://github.com/hectorqin/reader/assets/13557387/0e2310e2-c42b-455f-a4a1-eee33417e27a)

**Comment by hectorqin** [comment]
有空加一下

**Comment by caliban511** [comment]
> 有空加一下

谢谢大佬。👍
