### ISSUE TITLE
关于书籍换源的一些小问题。。。

### ISSUE THREAD

**Issue by caliban511** [hectorqin/reader#490]
如题。
在书籍阅读界面，用最顶端的 “书源” 按钮换源时，会因为不同盗版站。上面登记的作者名字不同，而导致搜索不到，无法换源。
只能退出阅读界面，在书架界面左侧搜索栏重新进行搜索书籍，才能搜出来。
如下图所示，
因为作者不同被识别为两本书，导致在阅读界面搜索不出更多的书源。
希望大佬有空能把这个问题解决一下。

![Screenshot_2024-02-06-16-50-51-931_org mozilla firefox](https://github.com/hectorqin/reader/assets/13557387/6637374c-9289-440e-ad3f-e26d125565ee)
![Screenshot_2024-02-06-16-50-59-475_org mozilla firefox](https://github.com/hectorqin/reader/assets/13557387/c075a97b-e856-45a5-8eb9-cb6151185a43)
![Screenshot_2024-02-06-16-51-27-102_org mozilla firefox](https://github.com/hectorqin/reader/assets/13557387/bb459672-35e5-4426-a191-2316aa31f967)

**Comment by hectorqin** [comment]
作者不同肯定不能当成同一本书的，因为可能同名

**Comment by caliban511** [comment]
> 作者不同肯定不能当成同一本书的，因为可能同名

好的，谢谢大佬回复。
