### ISSUE TITLE
【建议】希望可以添加自动加载下一章内容以达到更顺滑阅读的功能

### ISSUE THREAD

**Issue by OMDaniru** [hectorqin/reader#492]
每次阅读到一章页尾都要再点一下才能到下一章，所以希望添加自动加载下一章的功能，以达到更顺滑的阅读体验，非常感谢

**Comment by caliban511** [comment]
这个有啊，去设置里看看。

**Comment by OMDaniru** [comment]
> 这个有啊，去设置里看看。

啊？有的吗？请问是在下图的设置里面的哪个选项呢？

不是自动翻页，是自动加载，从而阅读到一章结尾时不用点击页尾的**加载下一章**就能直接看到预加载好的下一章的内容

阅读设置界面截图：
![PixPin_2024-02-07_12-42-07](https://github.com/hectorqin/reader/assets/127623916/a28daee4-9e24-448c-8291-9180968194ce)

页尾的**加载下一章**标志截图：
![Clip_2024-02-07_12-48-02](https://github.com/hectorqin/reader/assets/127623916/fe2bb679-0ed7-4cf1-8abd-549891968b26)

**Comment by caliban511** [comment]
翻页方式，上下滚动，，，就那么几个选项，你但凡试一下也早就发现了，，，😂😂😂

**Comment by OMDaniru** [comment]
> 翻页方式，上下滚动，，，就那么几个选项，你但凡试一下也早就发现了，，，😂😂😂

我去，我确实没想预加载会跟翻页方式牵扯在一起，亏我试了好久，太艹了，虽然但是，非常感谢
