### ISSUE TITLE
手机端朗读时切换至后台或锁屏即中断

### ISSUE THREAD

**Issue by wxyhxh** [hectorqin/reader#495]
手机端朗读时切换至后台或锁屏即中断。

**版本说明**
 - IOS17.3 safari浏览器
 - 群晖 DOCKER部署 v3.2.7-01010833

**Comment by hectorqin** [comment]
浏览器限制，暂时无解

**Comment by wxyhxh** [comment]
感谢老大回复！说来也怪，有时可以有时不行。
