### ISSUE TITLE
部分文字乱码

### ISSUE THREAD

**Issue by ifwlzs** [hectorqin/reader#5]
# 1. 窗口并没有消失

我这都启动好久了，上次你说这个白窗口会自动消失，但是现在还是没有自己隐藏

![image](https://user-images.githubusercontent.com/49548316/132832341-5a1e1407-77ad-411f-a109-80d1ca911ece.png)

# 2. 部分文字乱码

edge（chromium内核）93.0.961.38 
![image](https://user-images.githubusercontent.com/49548316/132825609-29cbc125-7e10-458f-80db-0748829e7956.png)
![image](https://user-images.githubusercontent.com/49548316/132825660-e4181f4f-58c9-43eb-99de-6eb6e35520cd.png)

firefox 92.0 
![image](https://user-images.githubusercontent.com/49548316/132826205-6f024646-f015-45d8-bc0d-b80e89df5394.png)
![image](https://user-images.githubusercontent.com/49548316/132826616-942225e3-8a94-4abe-a624-f203731cb42f.png)
![image](https://user-images.githubusercontent.com/49548316/132826936-c0951a6d-8ef1-44a6-8ce3-f4d969d8e64f.png)

# 3. 上传自定义图片会显示后端连接失败（连接的是手机web接口）
![GIF 2021-9-10 17-30-15](https://user-images.githubusercontent.com/49548316/132833233-49efddfb-ecd8-402f-9d9a-d8ae0ff14c95.gif)

**Comment by hectorqin** [comment]
1. 那是个浏览器窗口，用最新版的试试
2. 浏览器设置字符编码为 UTF-8 试试
3. 手机web接口是 阅读3app开启的接口？这个web页面只能使用这个项目的接口，阅读3app目前没有提供这些接口

**Comment by ifwlzs** [comment]
> 1. 那是个浏览器窗口，用最新版的试试
> 2. 浏览器设置字符编码为 UTF-8 试试
> 3. 手机web接口是 阅读3app开启的接口？这个web页面只能使用这个项目的接口，阅读3app目前没有提供这些接口
1. 的确是最新版的1.2.0阿
![GIF 2021-9-10 21-06-51](https://user-images.githubusercontent.com/49548316/132859208-7dfe6ae5-fede-4896-ac54-a30d38d07fad.gif)

2. 我直接从jar包中提取index.html打开是正常的
![image](https://user-images.githubusercontent.com/49548316/132856394-4046cf69-f8e6-4f4e-80c5-616ac3fd245b.png)

另外有没有考虑端口也能自定义😋

**Comment by hectorqin** [comment]
看看日志

**Comment by ifwlzs** [comment]
> 看看日志

[reader-2021-09-10.0.log](https://github.com/hectorqin/reader/files/7147835/reader-2021-09-10.0.log)

**Comment by hectorqin** [comment]
奇怪为啥浏览器是白屏。。

**Comment by hectorqin** [comment]
只能先用浏览器访问了，应该是支持pwa的

**Comment by hectorqin** [comment]
由于应用启动流程，端口自定义暂时没法解决

**Comment by hectorqin** [comment]
你在白屏窗口，右键点击 重新加载 试试

**Comment by ifwlzs** [comment]
还是白的 emmm
[reader-2021-09-11.0.log](https://github.com/hectorqin/reader/files/7147859/reader-2021-09-11.0.log)

**Comment by hectorqin** [comment]
那只能先用浏览器看书了

**Comment by hectorqin** [comment]
1.3版本应该修复了文字乱码的问题，端口自定义也支持了

**Comment by ifwlzs** [comment]
> 1.3版本应该修复了文字乱码的问题，端口自定义也支持了

乱码解决了！但是端口自定义exe不知道咋设置。不过曲线救国可以解决这个问题：
![image](https://user-images.githubusercontent.com/49548316/132977495-85397f64-3c68-49d0-9e96-9a466b91d622.png)

**Comment by hectorqin** [comment]
看README，在windowConfig.json里面配置
