### ISSUE TITLE
服务器多用户版 webDev备份到服务器失败

### ISSUE THREAD

**Issue by zhenghuanqi** [hectorqin/reader#50]
app端配置好webDev地址后，点击备份，服务器能接收到备份请求，观察日志，发现出现一堆乱码，然后备份失败。
![图片](https://user-images.githubusercontent.com/20548314/165532238-f1f8f68f-ffab-4e4b-9639-6357134d6d66.png)

**Comment by zhenghuanqi** [comment]
请指教，感谢作者开发出这么好的程序

**Comment by hectorqin** [comment]
乱码没关系，主要看看备份目录有没有文件
