### ISSUE TITLE
软件安装未创建一个新文件夹，导致卸载时把同目录其它文件一起都删了。。。

### ISSUE THREAD

**Issue by jkqxl** [hectorqin/reader#500]
**为避免无效问题和冗余问题，提问前请确认**
1. 你确定Google不能解决你的问题
2. 你确定已有的issue不能解决你的问题
3. 你确定issue的title按照格式如下：[web/simple-web/server]：description

**Describe the bug 描述你遇到的问题**
如标题，在使用软件自身的删除程序时，导致误删文件的重大损失。一开始是不小心安装错了位置到桌面，想要删除重新安装下就这样了。这到底是多少年前的老安装程序了，简直无语！！！

**To Reproduce 如何重现问题**
1. 下载Reader.Desktop_3.2.7_x64-setup.exe
2. 直接安装在某目录，使用根目录卸载程序，该目录的的其它文件一起被删掉了

**Expected behavior  期待修复的效果**
1.期望，软件安装时可以创建一个新文件夹。不过因为这不是软件本身的问题，那其实还是希望可以对软件直接进行打包，而不是使用什么安装程序。
2.创建软件的便携版本，要是便携的，手动选择删除，就不会出现该问题了。

**版本说明**
 - 操作系统：win10

**Comment by hectorqin** [comment]
抱歉，建议直接使用  reader-server 版本

**Comment by jkqxl** [comment]
> 抱歉，建议直接使用 reader-server 版本

reader-server 版本，仅有代码运行，没有图形界面，不太清楚具体该怎样使用。

**Comment by hectorqin** [comment]
可以自行修改 startup.cmd 里面的参数，把  `-server -Xms1g -Xmx1g`   中的1g修改为你自己的配置
