### ISSUE TITLE
[web]IOS web端语音朗读息屏卡住

### ISSUE THREAD

**Issue by AinzLimuru** [hectorqin/reader#501]
**为避免无效问题和冗余问题，提问前请确认**
1. 你确定Google不能解决你的问题
2. 你确定已有的issue不能解决你的问题
3. 你确定issue的title按照格式如下：[web/simple-web/server]：description

**Describe the bug 描述你遇到的问题**
语音朗读过程中，
使用浏览器选项能够做到熄屏后朗读当前章节的内容，但无法继续朗读下一章。屏幕点亮之后才能够继续朗读下一章的内容。
使用大声朗读功能在熄屏后只能朗读当前段落，然后就立即停止。

**To Reproduce 如何重现问题**
Steps to reproduce the behavior:  把你遇到的问题的发生步骤替换掉下面的内容：
1. 在ios的web上尝试朗读
2. 熄屏

**Expected behavior  期待修复的效果**
能够连续不断的朗读

**版本说明**
 - OS: ios
 - docker server
 - v3.2.7-01010833
 - Browser [e.g. chrome, safari]  ios 自带浏览器/chrome/firefox

**Comment by Aurora82** [comment]
同样有此问题

**Comment by tnnevol** [comment]
ios 大声朗读模式，息屏后必现

**Comment by hectorqin** [comment]
浏览器限制，暂时无解

**Comment by Yinghai75** [comment]
但是我用audiobookshelf听书，Safari浏览器发送到主屏，是可以熄屏听的

**Comment by hectorqin** [comment]
> 但是我用audiobookshelf听书，Safari浏览器发送到主屏，是可以熄屏听的

这是播放的完整的音频，而 Reader 是一段一段生成的音频，在一段音频结束后过渡到下一段的时候可能会被浏览器限制

**Comment by Yinghai75** [comment]
> > 但是我用audiobookshelf听书，Safari浏览器发送到主屏，是可以熄屏听的
> 
> 
> 
> 这是播放的完整的音频，而 Reader 是一段一段生成的音频，在一段音频结束后过渡到下一段的时候可能会被浏览器限制

的确是这样
