### ISSUE TITLE
server: 管理员账户被自动删除

### ISSUE THREAD

**Issue by harley-zh** [hectorqin/reader#503]
**Describe the bug 描述你遇到的问题**
只注册了一个管理员账户，该账户被自动删除。登录时提示用户未注册。

**To Reproduce 如何重现问题**
Steps to reproduce the behavior:  把你遇到的问题的发生步骤替换掉下面的内容：
1. 在服务器上用docker-compose搭建的服务
2. Storage目录指向了挂载在服务器的夸克网盘，Logs目录还是指向的本地服务器路径
3. 通过本地上传，进行书籍上传
4. 几天后通过导入JSON文件的方式导入了书源（不清楚是不是由于这个影响）
5. 系统直接提示登录用户未注册，但自己未手动删除过该唯一账户。

**Expected behavior  期待修复的效果**
想知道到底是由于导入了外部书源导致的问题，还是Storage目录指向的是网盘的原因。

**Screenshots 如有必要，可以截图说明**

**版本说明**
 - OS: [e.g. win]  Ubuntu 22.04.3
 - Deploy Method Docker-Compose
 - Program Version Latest 
 - Browser [e.g. chrome, safari]  MacOS/iOS, Edge

**Additional context 其他说明**

**Comment by hectorqin** [comment]
查看 storage/data/user.json 文件内容

**Comment by a494413872** [comment]
> 查看 storage/data/user.json 文件内容

docker-compose安装，配置了READER_APP_SECUREKEY，但是不知道管理员用户名是啥。查看 storage/data/user.json 文件，里面并没有管理员用户的信息。

**Comment by hectorqin** [comment]
没有管理员账号，只有管理密码，注册账号后登录进去，点击进入管理模式，输入管理密码就可以了

**Comment by gyy1201** [comment]
> 没有管理员账号，只有管理密码，注册账号后登录进去，点击进入管理模式，输入管理密码就可以了

大佬，我界面没有 进入管理模式 ，docker安装的
<img width="226" alt="QQ20240530-125225@2x" src="https://github.com/hectorqin/reader/assets/7831716/1571bd1c-f6ac-4c15-839c-411b5e6222e2">
在docker下添加READER_APP_DEFAULTUSERBOOKSOURCELIMIT=1000 也无效
<img width="477" alt="QQ20240530-125425@2x" src="https://github.com/hectorqin/reader/assets/7831716/893b1c1b-4c85-4471-a395-ccfb211daafc">

**Comment by hectorqin** [comment]
添加环境变量之后有重启吗？

> > 没有管理员账号，只有管理密码，注册账号后登录进去，点击进入管理模式，输入管理密码就可以了
> 
> 大佬，我界面没有 进入管理模式 ，docker安装的 <img alt="QQ20240530-125225@2x" width="226" src="https://private-user-images.githubusercontent.com/7831716/335045138-1571bd1c-f6ac-4c15-839c-411b5e6222e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzMzMDgsIm5iZiI6MTcxODE3MzAwOCwicGF0aCI6Ii83ODMxNzE2LzMzNTA0NTEzOC0xNTcxYmQxYy1mNmFjLTRjMTUtODM5Yy00MTFiNWU2MjIyZTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTJUMDYxNjQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjhmMTUzZTU3MmY4Zjk0YTVkYmFiZDk1ZmQxYmUxMjk3YTY1YWMzZDI1NGYzZDI1ZjdmMjBjMTM1ZjhlYWY2MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.THyz7Cl8y5mf00-ZIoMBvZff1Rfe7j1qs-aAQBnSEQ0"> 在docker下添加READER_APP_DEFAULTUSERBOOKSOURCELIMIT=1000 也无效 <img alt="QQ20240530-125425@2x" width="477" src="https://private-user-images.githubusercontent.com/7831716/335045364-893b1c1b-4c85-4471-a395-ccfb211daafc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzMzMDgsIm5iZiI6MTcxODE3MzAwOCwicGF0aCI6Ii83ODMxNzE2LzMzNTA0NTM2NC04OTNiMWMxYi00Yzg1LTQ0NzEtYTM5NS1jY2ZiMjExZGFhZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTJUMDYxNjQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzA4MzA2NzM0OTQ0N2I3NTlmMTNhM2UzYzlhYWZjYmZlNzIyYmVhZGZjNTAzMTMzNWMyYWM0MzY4ZGI4M2M2ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oDTwNcrOgvdZTJ4-cr0EcnwNDkBtr5HlQKeOd_NOoS4">

**Comment by gyy1201** [comment]
> 添加环境变量之后有重启吗？
> 
> > > 没有管理员账号，只有管理密码，注册账号后登录进去，点击进入管理模式，输入管理密码就可以了
> > 
> > 
> > 大佬，我界面没有 进入管理模式 ，docker安装的 <img alt="QQ20240530-125225@2x" width="226" src="https://private-user-images.githubusercontent.com/7831716/335045138-1571bd1c-f6ac-4c15-839c-411b5e6222e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzMzMDgsIm5iZiI6MTcxODE3MzAwOCwicGF0aCI6Ii83ODMxNzE2LzMzNTA0NTEzOC0xNTcxYmQxYy1mNmFjLTRjMTUtODM5Yy00MTFiNWU2MjIyZTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTJUMDYxNjQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjhmMTUzZTU3MmY4Zjk0YTVkYmFiZDk1ZmQxYmUxMjk3YTY1YWMzZDI1NGYzZDI1ZjdmMjBjMTM1ZjhlYWY2MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.THyz7Cl8y5mf00-ZIoMBvZff1Rfe7j1qs-aAQBnSEQ0"> 在docker下添加READER_APP_DEFAULTUSERBOOKSOURCELIMIT=1000 也无效 <img alt="QQ20240530-125425@2x" width="477" src="https://private-user-images.githubusercontent.com/7831716/335045364-893b1c1b-4c85-4471-a395-ccfb211daafc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzMzMDgsIm5iZiI6MTcxODE3MzAwOCwicGF0aCI6Ii83ODMxNzE2LzMzNTA0NTM2NC04OTNiMWMxYi00Yzg1LTQ0NzEtYTM5NS1jY2ZiMjExZGFhZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTJUMDYxNjQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzA4MzA2NzM0OTQ0N2I3NTlmMTNhM2UzYzlhYWZjYmZlNzIyYmVhZGZjNTAzMTMzNWMyYWM0MzY4ZGI4M2M2ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oDTwNcrOgvdZTJ4-cr0EcnwNDkBtr5HlQKeOd_NOoS4">

大佬，有重启的，基本都试过了，文件夹权限给了最高的读写，docker重启过了，连nas都重启过了，我还怕变量区分大小写，大小写都转换过了，怕拼错还直接复制了文档里的词。
