### ISSUE TITLE
想自己在windows上搭建webview

### ISSUE THREAD

**Issue by carcoonzyk** [hectorqin/reader#505]
如题，想自己在windows上搭建webview，请问哪里有说明书？

**Comment by hectorqin** [comment]
推荐使用docker运行

**Comment by carcoonzyk** [comment]
对的，我就是想搭建在winserver容器里运行，目前不知道该怎么搭？

**Comment by hectorqin** [comment]
这个没有测试过

**Comment by carcoonzyk** [comment]
有类似reader打包的包吗？我可以自己配docker环境

**Comment by hectorqin** [comment]
`hectorqin/remote-webview`

**Comment by carcoonzyk** [comment]
？没看到有这个项目的github，或者dockerhub官网也没找到关于windows内核的容器

**Comment by hectorqin** [comment]
代码未开源，也不支持windows内核

**Comment by carcoonzyk** [comment]
好吧
