### ISSUE TITLE
换个cdn吧，cdn.jsdelivr.net太慢了

### ISSUE THREAD

**Issue by kongxiangyiren** [hectorqin/reader#507]

**Comment by hectorqin** [comment]
有什么好用的cdn推荐吗?

**Comment by kongxiangyiren** [comment]
unpkg.com或者registry.npmmirror.com , https://registry.npmmirror.com/npm包名/版本号/files/文件路径

**Comment by ShowMeBaby** [comment]
> cdn有什么好用的推荐吗？
可否考虑在docker包中增加个配置项, 以关闭CDN直接使用本地资源, 我部署在高带宽机器上, 测试出 移动网络 首页加载不出来,或这加载异常缓慢, 排查发现是 jsdelivr 在国内加载太慢导致的, 在用户不多时其实可以考虑不启用CDN, 即使1M小水管那几百K也差不了多久, 一旦启用cdn就得考虑各个运营商对CDN的屏蔽了

**Comment by famousprince** [comment]
`cdn.jsdelivr.net/npm` 直接替换成 `s4.zstatic.net/npm`

**Comment by hectorqin** [comment]
3.2.9 已修改为本地资源
