### ISSUE TITLE
EPUB文件如果是htm不是html则无法注入js调整页面高度

### ISSUE THREAD

**Issue by niphor** [hectorqin/reader#509]
**Describe the bug 描述你遇到的问题**
如果EPUB打包文件里面的章节是htm，不是html则`// reader-inject-javascript-1.9.0` 这个js无法注入

**To Reproduce 如何重现问题**
1. 我测试用的文档是 [三体三部曲](https://zh.singlelogin.re/book/16559847/261850/%E4%B8%89%E4%BD%93%E4%B8%89%E9%83%A8%E6%9B%B2.html)
2. 默认导入后，在阅读界面会出现滚动条
3. 修改EPUB文件，将htm文件后缀都改为html，保存
4. 界面能正常展现

**Expected behavior  期待修复的效果**
没有滚动条，页面能正常展示，高度正常

**Screenshots 如有必要，可以截图说明**
默认EPUB，出现滚动条
![image](https://github.com/hectorqin/reader/assets/927255/2d80866a-bff1-484d-8a75-b05bccecbe58)

修改后的EPUB，界面能正常展现
<img width="776" alt="image" src="https://github.com/hectorqin/reader/assets/927255/e90d505d-a149-42de-aea8-b302f3734146">

**版本说明**
 - OS: MacOS 14.4.1
 - Deploy Method: Docker
 - Program Version: v3.2.7-01010833
 - Browser: Chrome 123.0.6312.58 (Mac),Chrome 122 (Android)

**Comment by hectorqin** [comment]
试试新版本

**Comment by niphor** [comment]
感谢

应该可以了
