### ISSUE TITLE
kindle浏览器打开是空白页

### ISSUE THREAD

**Issue by lz-lz-lz** [hectorqin/reader#51]
kindle浏览器打开是空白页

**Comment by liuxiaoleo** [comment]
老大回答过这个问题，Kindle的浏览器太陈旧了，不支持web版的阅读。等等28号的越狱吧，越狱后另外装个浏览器试试吧。一定不要升级固件啊，5.14.2及以下才能越狱。

**Comment by superfat1988** [comment]
kindle远古跑h5性能太低了。哪怕jb后，装插件，也还是原来的浏览器核心。估计得等大佬适配。
ps: 假如大佬愿意抽时间适配，我能提供ko2给大佬当开发机。

**Comment by hectorqin** [comment]
试试beta版看看

**Comment by liuxiaoleo** [comment]
KPW4，固件5.14.2，试了刚更新的beta版，还是空白页。kindle的浏览器太弱鸡了啊。

**Comment by hectorqin** [comment]
那暂时没办法了

**Comment by hectorqin** [comment]
待会儿试试最新的beta版，然后用 kindle 访问链接    `http://ip:端口/#/?errorAlert=1`，看看有没有错误弹窗，有的话拍照看看

**Comment by liuxiaoleo** [comment]
用了刚更新的Beta3，仍然不行，是空白页。访问给的这个链接，依然空白。附上照片了
![Uploading IMG_4515.JPG…]()
![IMG_4514](https://user-images.githubusercontent.com/103955258/165946544-b9b2862c-debd-46e1-bab1-a4e490a42e40.JPG)

**Comment by hectorqin** [comment]
你有没有启用 javascript ？

**Comment by superfat1988** [comment]
> 你有没有启用 javascript ？

已经更新Beta3 Docker, 已开启Javascript, 按http://ip:端口/#/?errorAlert=1输入浏览器， 依旧是空白页。
![2be309305c7bf55180bb27e1fa23a81](https://user-images.githubusercontent.com/48008274/166112958-571df73c-74f4-4bae-828c-cb212535db39.jpg)

**Comment by hectorqin** [comment]
那没办法了。。

**Comment by superfat1988** [comment]
> 那没办法了。。

好吧， 多谢大老

**Comment by 269774331** [comment]
> 那没办法了。。



> 待会儿试试最新的beta版，然后用 kindle 访问链接 `http://ip:端口/#/?errorAlert=1`，看看有没有错误弹窗，有的话拍照看看

我也是空白，输入这个网址，显示这个
![Uploading 1653660023683..jpg…]()

**Comment by hectorqin** [comment]
试试打开demo服务器看看

**Comment by hectorqin** [comment]
kindle不支持 es5 的 getter 和 setter 特性，目前无法解决
