### ISSUE TITLE
PDF不能正常获取TOC和封面截图，只能显示output-x.png作为目录

### ISSUE THREAD

**Issue by niphor** [hectorqin/reader#510]
**Describe the bug 描述你遇到的问题**
PDF 本身有 TOC，但是导入时，不能正常获取，目录列表里都是`output-x.png`
另外 PDF的封面建议可以取第一页的图片作为封面图进行展示。
现在要有目录 只能点击边上的 书本 图标，用浏览器来浏览PDF

**To Reproduce 如何重现问题**
1. 我测试的文档是：[大规模语言模型：从理论到实践](https://zh.singlelogin.re/book/27045090/48d384/%E5%A4%A7%E8%A7%84%E6%A8%A1%E8%AF%AD%E8%A8%80%E6%A8%A1%E5%9E%8B%E4%BB%8E%E7%90%86%E8%AE%BA%E5%88%B0%E5%AE%9E%E8%B7%B5.html)
2. 导入文档时，可以看见 目录都是 `output-x.png`,且封面没有

**Expected behavior  期待修复的效果**
能够正常获取目录

**Screenshots 如有必要，可以截图说明**
导入时 无法获取正确的目录信息
<img width="443" alt="image" src="https://github.com/hectorqin/reader/assets/927255/736e82dd-d40e-4d4a-9507-689b68b0a548">
PDF本身是带有书签的
<img width="299" alt="image" src="https://github.com/hectorqin/reader/assets/927255/763ef270-a35f-4956-8e5c-00be5b53d7e4">

**版本说明**
 - OS: MacOS 14.4.1
 - Deploy Method: Docker
 - Program Version: v3.2.7-01010833
 - Browser: Chrome 123.0.6312.58

**Additional context 其他说明**
如果可以的话，还是最好能判断下PDF是文本类型的，还是图片类型的，文本类型的以HTML输出的话能利用下 类似朗读功能

**Comment by hectorqin** [comment]
嗯，现在pdf只是转成一页一页图片，因为要解析pdf的话逻辑有点复杂，如果直接用pdf.js的话，每次打开又得下载pdf全文，所以暂时没有好办法

**Comment by niphor** [comment]
@hectorqin 感谢回复

现阶段转成图片的话，也可以接受，正常阅读没啥问题。
但是建议 可以单独取目录信息，这样起码比都是`output-x.png`好点
Java类库比如`pdfbox`,也有现成的方法，比如：[如何使用Java中的PDFBox获取PDF文件中的所有书签](https://blog.51cto.com/u_16213377/8105560) 
完整示例也才40多行代码

希望可以考虑

**Comment by hectorqin** [comment]
试试新版本

**Comment by niphor** [comment]
感谢

可以正常获取和使用

**Comment by greatbody** [comment]
我用的 hectorqin/reader:3.2.10 镜像，导入到 PDF 无法识别 TOC，无法正常显示章节内容。
[《毛泽东选集》（第一卷）（正文）.pdf](https://github.com/user-attachments/files/16422445/default.pdf)

**Comment by shuaishi1991** [comment]
> 嗯，现在pdf只是转成一页一页图片，因为要解析pdf的话逻辑有点复杂，如果直接用pdf.js的话，每次打开又得下载pdf全文，所以暂时没有好办法

这就是阅读pdf最好的办法，就应该这样
