### ISSUE TITLE
[web]导入的本地书籍在其他设备无法阅读

### ISSUE THREAD

**Issue by slept-yogurt** [hectorqin/reader#514]
**为避免无效问题和冗余问题，提问前请确认**
1. 你确定Google不能解决你的问题
2. 你确定已有的issue不能解决你的问题
3. 你确定issue的title按照格式如下：[web/simple-web/server]：description

**Describe the bug 描述你遇到的问题**
A clear and concise description of what the bug is.  简洁有效的说明。
在pc端导入的本地书籍，在其他设备的浏览器看提示章节文件不存在, 获取章节内容失败.
![Screenshot_2024-04-10-18-06-03-849_com android chrome](https://github.com/hectorqin/reader/assets/35197921/1e1639cf-34b2-492e-95e0-558c135379f4)

**Expected behavior  期待修复的效果**
导入的本地书籍，即使在其他设备，登录同个账号之后应该可以阅读。

**版本说明**
 - OS: freebsd
 - Deploy Method: jar包部署
 - Program Version: 3.27
 - Browser :chrome, safari

**Additional context 其他说明**
看start.out日志都是正常输出的INFO没有到报错信息.
__2024-04-10 04:05:34 [c7075d5e] [DefaultDispatcher-worker-10] INFO  c.h.r.api.controller.BookController - chapterFilePath: /home/gs/domains/reader/storage/data/ytb/刘慈欣作品集_刘慈欣/刘慈欣科幻作品集.epub/index/OEBPS/text/part0000_split_009.html OEBPS__
对比了一下日志，报错的时候多了这一行，按路径去看了下，index目录下没有OEBPS这个文件夹

**Comment by Diaoest-Mian** [comment]
😶观察发现是服务运行一段时间后会出现这个问题，但是出现问题后马上重启不能立即恢复，得是服务停止一段时间再重新启动才能恢复

**Comment by hectorqin** [comment]
未复现
