### ISSUE TITLE
[WEB]: 希望能添加TTS语音接口设置

### ISSUE THREAD

**Issue by Yinghai75** [hectorqin/reader#516]
**为避免无效问题和冗余问题，提问前请确认**
1. 你确定Google不能解决你的问题
2. 你确定已有的issue不能解决你的问题
3. 你确定issue的title按照格式如下：[web/simple-web/server]：description

**Describe the bug 描述你遇到的问题**
A clear and concise description of what the bug is.  简洁有效的说明。
**现在TTS无法自定义，希望可以
- url导入在线语音库，和/或
- 本地导入json，和/或
- 自已填写Azure TTS的密钥和区域**
- 
**To Reproduce 如何重现问题**
Steps to reproduce the behavior:  把你遇到的问题的发生步骤替换掉下面的内容：

**Expected behavior  期待修复的效果**
A clear and concise description of what you expected to happen. 简单描述。
**听书时可以使用例如：微软晓晓多语言** 

**Screenshots 如有必要，可以截图说明**

**版本说明**
 - OS: [e.g. win]  说明操作系统
 - Deploy Method 说明软件部署方式
 - Program Version 说明软件版本
 - Browser [e.g. chrome, safari]  说明终端、浏览器型号

**Additional context 其他说明**
Add any other context about the problem here. 添加你认为有必要的内容，否则不写。

**Comment by hectorqin** [comment]
有没有相关的规范？

**Comment by Yinghai75** [comment]
> 有没有相关的规范？

不知指的是何规范？ 我是想能用上微软晓晓多语言，然后发现 源阅读 可以很方便地实现。 ![image](https://github.com/hectorqin/reader/assets/116246701/1559735e-81ed-4d44-8a7f-c7704db0b7de)

**Comment by hectorqin** [comment]
发几个出来测试一下看看

**Comment by hectorqin** [comment]
试试新版本

**Comment by Yinghai75** [comment]
大佬牛B，导入微软晓晓多语言正常，就是不能调语速，一调就没声了
默认语速还可以

**Comment by Yinghai75** [comment]
现在就只缺一个IPA了，不然只能开着屏听
有空的时候，看能不能把调语速修一下 ^_^

**Comment by hectorqin** [comment]
3.2.9 语速优化了一下

**Comment by Yinghai75** [comment]
3.2.9感觉是最慢速度是原先API的默认速度，调速正常了，太棒了

**Comment by chaoqunxie** [comment]
> > 大佬牛B，导入微软晓晓多语言正常，就是不能调语速，一调就没声了 默认语速还可以
> 
> 兄弟，我也是想用晓晓多语言，我有api但是不会配置，可以把你配置给我参考一下吗

同问

**Comment by rodingbaba** [comment]
> > > 大佬牛B，导入微软晓晓多语言正常，就是不能调语速，一调就没声了 默认语速还可以
> > 
> > 
> > 兄弟，我也是想用晓晓多语言，我有api但是不会配置，可以把你配置给我参考一下吗
> 
> 同问

我学会了，我的配置是这样的，你可以试一下，替换你的API，还有URL可能也需要换。

{
    "id": 1716363163596,
    "name": "Azure 晓晓 多语言",
    "url": "https://southeastasia.tts.speech.microsoft.com/cognitiveservices/v1,{\"method\":\"POST\",\"body\":\"<speak version=\\\"1.0\\\" xmlns=\\\"http://www.w3.org/2001/10/synthesis\\\" xmlns:mstts=\\\"https://www.w3.org/2001/mstts\\\" xml:lang=\\\"zh-CN\\\"><voice name=\\\"zh-CN-XiaoxiaoMultilingualNeural\\\"><prosody rate=\\\"{{speakSpeed*4}}%\\\" pitch=\\\"default\\\">{{speakText}}</prosody></voice></speak>\",\"headers\":{\"Ocp-Apim-Subscription-Key\":\"输入你的api\",\"Content-Type\":\"application/ssml+xml\",\"X-Microsoft-OutputFormat\":\"audio-24khz-48kbitrate-mono-mp3\",\"User-Agent\":\"legado\"}}",
    "contentType": "audio/mpeg",
    "concurrentRate": "0",
    "loginUrl": "",
    "loginUi": "",
    "header": "{\"Ocp-Apim-Subscription-Key\":\"输入你的api\",\"Content-Type\":\"application/ssml+xml\",\"X-Microsoft-OutputFormat\":\"audio-24khz-48kbitrate-mono-mp3\",\"User-Agent\":\"legado\"}",
    "enabledCookieJar": false,
    "loginCheckJs": "",
    "lastUpdateTime": 1716363170008,
    "tag": "Azure 晓晓 多语言",
    "loginJs": "",
    "key": "httpTts:1716363163596"
}

**Comment by chaoqunxie** [comment]
> > > > 大佬牛B，导入微软晓晓多语言正常，就是不能调语速，一调就没声了 默认语速还可以
> > > 
> > > 
> > > 兄弟，我也是想用晓晓多语言，我有api但是不会配置，可以把你配置给我参考一下吗
> > 
> > 
> > 同问
> 
> 我学会了，我的配置是这样的，你可以试一下，替换你的API，还有URL可能也需要换。
> 
> { "id": [1716363163596](tel:1716363163596), "name": "Azure 晓晓 多语言", "url": "[https://southeastasia.tts.speech.microsoft.com/cognitiveservices/v1,{\"method\":\"POST\",\"body\":\](https://southeastasia.tts.speech.microsoft.com/cognitiveservices/v1,%7B%5C%22method%5C%22:%5C%22POST%5C%22,%5C%22body%5C%22:%5C)"<speak version=\"1.0\" xmlns=\"[http://www.w3.org/2001/10/synthesis\\\](http://www.w3.org/2001/10/synthesis%5C%5C%5C)" xmlns:mstts=\"[https://www.w3.org/2001/mstts\\\](https://www.w3.org/2001/mstts%5C%5C%5C)" xml:lang=\"zh-CN\"><voice name=\"zh-CN-XiaoxiaoMultilingualNeural\"><prosody rate=\"{{speakSpeed*4}}%\" pitch=\"default\">{{speakText}}","headers":{"Ocp-Apim-Subscription-Key":"输入你的api","Content-Type":"application/ssml+xml","X-Microsoft-OutputFormat":"audio-24khz-48kbitrate-mono-mp3","User-Agent":"legado"}}", "contentType": "audio/mpeg", "concurrentRate": "0", "loginUrl": "", "loginUi": "", "header": "{"Ocp-Apim-Subscription-Key":"输入你的api","Content-Type":"application/ssml+xml","X-Microsoft-OutputFormat":"audio-24khz-48kbitrate-mono-mp3","User-Agent":"legado"}", "enabledCookieJar": false, "loginCheckJs": "", "lastUpdateTime": [1716363170008](tel:1716363170008), "tag": "Azure 晓晓 多语言", "loginJs": "", "key": "httpTts:[1716363163596](tel:1716363163596)" }

感谢🙏
