### ISSUE TITLE
字号调整能不能更细化呢

### ISSUE THREAD

**Issue by liuxiaoleo** [hectorqin/reader#52]
在手机上看书时，用16号字有点小，18号又有点大。目前的调节只能按“+-”按钮，一次调2个号，不能点击数字输入想要的字号。请问老大能不能开发一下字号的精细调节功能。谢谢了。

**Comment by hectorqin** [comment]
可以

**Comment by liuxiaoleo** [comment]
老大nb，回复好及时啊。哈哈。
