### ISSUE TITLE
安卓web封面显示问题

### ISSUE THREAD

**Issue by sunjiahao5340** [hectorqin/reader#520]
**Describe the bug 描述你遇到的问题**

电脑端web页面图片能正常显示，但手机端web页面某些书源封面无法正常显示，如下图
![Snipaste_2024-05-06_16-01-27](https://github.com/hectorqin/reader/assets/47418170/779d180d-4a93-477f-a359-11d1f52540ba)
![1714990743649](https://github.com/hectorqin/reader/assets/47418170/f46b7a8c-23f2-479c-8e88-471d7c1dd353)

**To Reproduce 如何重现问题**
[自用.json](https://github.com/hectorqin/reader/files/15219357/default.json)
例如使用以上书源，搜索添加书架后，在电脑web页面封面正常显示，安卓端web显示不了。

**Expected behavior  期待修复的效果**
封面能够正常显示

**Screenshots 如有必要，可以截图说明**
图片附上

**版本说明**
 - OS:：安卓14
 - Deploy Method：docker-compete
 - Program Version： 3.2.8
 - Browser ：chrome,edge

**Additional context 其他说明**
服务端页面自定义样式如何使用

**Comment by kfab1983** [comment]
其实电脑访问web页面有时候一样会有部分封面显示不出来。

**Comment by hectorqin** [comment]
一般是网络问题
