### ISSUE TITLE
不能盲搜书籍吗？

### ISSUE THREAD

**Issue by jxjxjhjh** [hectorqin/reader#521]
docker最新版

被讨厌的勇气
所有书只能搜索全名，如果搜索 被讨厌，就搜不到这本书，这和阅读APP使用体验不一样，非常不合理

**Comment by luwu4455** [comment]
我用最新的版本也没办法盲搜，之前的版本是可以实现的，请问是BUG嘛？

**Comment by hectorqin** [comment]
之后会考虑加个选项，来区分模糊搜索和精确搜索

**Comment by hectorqin** [comment]
新版本的模糊搜索请使用   `%` + `关键字` 来搜索，如  `%斗罗`
