### ISSUE TITLE
翻页，自动阅读相关问题

### ISSUE THREAD

**Issue by 798love** [hectorqin/reader#522]
能否将翻页方式和翻页区域分开？

选择左右滑动时，翻页区域就变成左右的了，手机左手使用时容易误触，还是想用上下的翻页区域

或者下图这种翻页方式也挺好的
<img width="455" alt="image" src="https://github.com/hectorqin/reader/assets/26137612/55c5e31f-0a2f-4662-9476-08f951c648e2">

手机开启自动阅读时，参数重置，翻页速度改到10，会出现上下抖动的残影，完全看不了

**Comment by hectorqin** [comment]
3.2.9 已新增固定布局的翻页方式
