### ISSUE TITLE
Server：docker搭建的阅读，会经常提示错误 io.vertx.core.json.DecodeException……

### ISSUE THREAD

**Issue by FeiLZX3Km** [hectorqin/reader#525]
**为避免无效问题和冗余问题，提问前请确认**
1. 确定Google不能解决你的问题
2. 确定已有的issue不能解决你的问题
3. 确定issue的title按照格式如下：[web/simple-web/server]：description

**Describe the bug 描述你遇到的问题**
io.vertx.core.json.DecodeException: Failed to decode:No content to map due to end-of-input at [Source: (String)""; line: 1, column: 0]

**To Reproduce 如何重现问题**
刷新页面、导入书源等各种操作，均会出现该问题。
刷新页面百分百出现该错误提示。
书源虽然会提示导入错误，但能够导入。但是虽然能够导入该书源，但是在左侧栏目搜索书籍搜不到结果。

**Expected behavior  期待修复的效果**
解决掉该错误提示反映出来的问题。

**Screenshots 如有必要，可以截图说明**
![image](https://github.com/hectorqin/reader/assets/21981195/251570e6-9bf1-4ebe-a397-cbd96663adea)

**版本说明**
 - OS:Windows11
 - Deploy Method docker
 - Program Version 阅读v3.2.8-05010259
 - Browser edge

**Comment by hectorqin** [comment]
这种一般是数据出问题了，查看日志找到对应文件，在对应目录一般会有备份文件
