### ISSUE TITLE
在ios上使用时，如果在打开的图书界面，直接刷新，会导致界面卡主，按钮都不可用

### ISSUE THREAD

**Issue by Edwinzzzs2** [hectorqin/reader#526]
**Describe the bug 描述你遇到的问题**
在ios上使用时，如果在打开的图书界面，直接刷新，会导致界面卡主，一直转圈loading显示正在获取内容，此时也无法返回到书架

**To Reproduce 如何重现问题**
Steps to reproduce the behavior:  把你遇到的问题的发生步骤替换掉下面的内容：
1、从书架点击图书进入阅读
2、直接使用浏览器的刷新按钮刷新整个页面
3、页面一直显示正在获取内容，并且也无法返回书架，界面卡死

**Expected behavior  期待修复的效果**
可以正常阅读时，使用浏览器的刷新按钮刷新界面，不会卡死能正常加载

**Screenshots 如有必要，可以截图说明**
[
![Snipaste_2024-05-11_22-53-33](https://github.com/hectorqin/reader/assets/122032171/0c33dc15-3da2-4785-8d5e-2afbeb2a684b)
](url)

**版本说明**
 - OS: [e.g. win]  说明操作系统
 - Deploy Method 说明软件部署方式
 - Program Version 说明软件版本
 - Browser [e.g. chrome, safari]  说明终端、浏览器型号

**Additional context 其他说明**
Add any other context about the problem here. 添加你认为有必要的内容，否则不写。

**Comment by kasfori** [comment]
这个问题之前版本就有了，安卓也是一样，这个问题是导致我部署不用的原因！！

**Comment by Edwinzzzs2** [comment]
那你现在用的哪个，分享一下

**Comment by Edwinzzzs2** [comment]
> 这个问题之前版本就有了，安卓也是一样，这个问题是导致我部署不用的原因！！

你现在用的哪个，分享一下呀

**Comment by hectorqin** [comment]
哪个版本开始出现这个问题的？

**Comment by Edwinzzzs2** [comment]
> 哪个版本开始出现这个问题的？

我用的最新的，3.2.8

**Comment by hectorqin** [comment]
3.2.9 应该修复了
