### ISSUE TITLE
[server]博趣网（www.bq0.net）不能搜索小说（该网站搜索和阅读时需要填写验证码）

### ISSUE THREAD

**Issue by darkelfzdy** [hectorqin/reader#527]
**为避免无效问题和冗余问题，提问前请确认**
1. 你确定Google不能解决你的问题：不能
3. 你确定已有的issue不能解决你的问题：不能
4. 你确定issue的title按照格式如下：[web/simple-web/server]：description：确定

**Describe the bug 描述你遇到的问题**
docker部署，使用的博趣网书源（https://www.yckceo.com/yuedu/shuyuan/content/id/4106.html），搜索无法出现书籍（提示错误），也不能填写验证码（在阅读app上可以填写验证码）

**To Reproduce 如何重现问题**
1.搜索书籍
2.提示错误：com.script.ScriptException: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "0" from null (<Unknown source>#7) in <Unknown source> at line number 7

**Expected behavior  期待修复的效果**
能够填写验证码实现书籍搜索

le, add screenshots to help explain your problem.

**版本说明**
 - OS: armbian 
 - Deploy Method：docker
 - Program Version ：v3.2.8
 - Browser ：edge122.0.2365.66

**Comment by 0xddy** [comment]
想太多了，防火墙的验证种类太多了

**Comment by darkelfzdy** [comment]
这种验证码验证我只看到博趣网有。而阅读app是可以跳出对话框填写验证码的。另外，博趣网的书更得比较近，所以还是希望能够实现填写验证码

**Comment by hectorqin** [comment]
由于是服务器版，不支持登录、验证码等交互方式
