### ISSUE TITLE
[web/simple-web]：音量键翻页对于左右滑动模式不适配

### ISSUE THREAD

**Issue by oh-ao** [hectorqin/reader#528]
**Describe the bug 描述你遇到的问题**
在via和einkbro浏览器中打开音量键翻页功能后，在上下滑动/上下滚动模式下可以正常使用音量键翻页，但是在左右滑动模式下无反应。对于左右滑动翻页式模式均有此问题，包括原始web和simple-web。
连接实体键盘后，左右翻页模式下对于‘page up’，‘page down’，‘home’，‘end’按键均无反应，且上下滑动模式有正常反应，于是推测为网页适配问题。

**To Reproduce 如何重现问题**
1. via浏览器→设置→通用→操作设定→使用音量键翻页
    或einkbro→设置→操作习惯→使用向上/向下方向键翻页
2. 打开reader web或simple-web，进入书籍阅读页面（自适应为手机模式）
3. 在上下滑动/滚动模式下按下音量加减按键，或实体键盘的‘page up’，‘page down’键，可以正常翻页
4. 更改翻页模式为左右滑动
5. 按下音量加减，或实体键盘的‘page up’，‘page down’键，无法正常翻页

**Expected behavior  期待修复的效果**
在左右滑动模式下，在via或einkbro类似浏览器中，按下音量加减键可以正常翻页和进入下一章节。

**版本说明**
 - OS: 群晖DSM7.1.1
 - Deploy Method: Docker容器
 - Program Version: v3.2.8-05010259
 - Browser: via_v5.5.1, webview版本124.0.6367.172(636717233)，einkbro_v11.7.0

**Comment by hectorqin** [comment]
嗯，下个版本加上这些按键的监听

**Comment by hectorqin** [comment]
试试 3.2.9

**Comment by hectorqin** [comment]
https://keyboard.bmcx.com/   用手机打开这个页面，按一下看看

**Comment by hectorqin** [comment]
我试了一下x浏览器，看起来就是直接滚动页面的

**Comment by hectorqin** [comment]
那就没办法了
