### ISSUE TITLE
登陆刷新报错

### ISSUE THREAD

**Issue by CN0579** [hectorqin/reader#53]
java.lang.IllegalArgumentException: Cannot construct instance of `io.legado.app.data.entities.BookSource`, problem: Should never call `set()` on setterless property ('headerMap') at [Source: UNKNOWN; line: -1, column: -1]

**Comment by hectorqin** [comment]
检查一下你的书源，看看有没有书源包含了  headerMap 属性

**Comment by RouJiANG-14** [comment]
> 

有的话应该怎么删除呢？ 好多书源要一个一个的看么？

**Comment by RouJiANG-14** [comment]
java.lang.IllegalArgumentException: Cannot construct instance of `io.legado.app.data.entities.BookSource`, problem: Should never call `set()` on setterless property ('headerMap') at [Source: UNKNOWN; line: -1, column: -1]

现在情况是前端书源删除的话，也报错这个.....有好的解决办法么 佬！

> 检查一下你的书源，看看有没有书源包含了 headerMap 属性

**Comment by hectorqin** [comment]
手动编辑书源文件吧
