### ISSUE TITLE
[web]：书籍正文中“乾”字显示为“干”字

### ISSUE THREAD

**Issue by g881199** [hectorqin/reader#531]
**Describe the bug 描述你遇到的问题**
导入本地txt书籍，文件非标题中的“乾”字在阅读时大部分情况下变成了“干”字，仅在与特定字符组词时才正常显示。

**To Reproduce 如何重现问题**
Steps to reproduce the behavior:  把你遇到的问题的发生步骤替换掉下面的内容：
1.创建txt文件。
2.txt文件内输入“乾”和“乾隆”。
3.导入txt文件。
4.阅读时，内容显示为”干“和”乾隆“。

**Screenshots 如有必要，可以截图说明**
<img width="761" alt="issue" src="https://github.com/hectorqin/reader/assets/67706992/cbe1d6ae-11f5-4b55-961e-52793d5ece01">
<img width="501" alt="issue2" src="https://github.com/hectorqin/reader/assets/67706992/b4b6de0f-0537-4b5c-b048-a8201b016f67">

**版本说明**
 - OS: [e.g. win]  Windows、MacOS，iOS
 - Deploy Method MacOS、Windows、服务器端
 - Program Version 3.2.8
 - Browser [e.g. chrome, safari]  Chrome、Safari电脑端，Safari手机端

**Additional context 其他说明**
1.导入的txt文件编码为UTF-8或GB2312都会出现此问题，其他编码未测试。
2.将txt文件转换为epud文件再导入会正常显示。
3.搜索文本时，使用”乾“字能正常搜索，搜索结果显示正常。
4.将导入的文件再导出为txt，显示正常。

**Comment by hectorqin** [comment]
是不是有替换规则？

**Comment by hectorqin** [comment]
应该是这个问题
