### ISSUE TITLE
[web/simple] 小说封面图自动保存到本地

### ISSUE THREAD

**Issue by RogerProSelf** [hectorqin/reader#533]
目前只有本地上传的封面图是存储在服务器，从在线书源引入的封面图是以URL形式存储的，希望能自动将其保存到本地，避免URL因为书源换域名等因素失效，特别是一些比较罕见的网文，很多只有1-2个书源能提供。图片也不会占据多少本地空间。

对于封面图后期更换，可以在每次启动Reader3的时候自动清理掉没有被引用的封面图。

感谢！

**Comment by hectorqin** [comment]
只有新增的书籍会保存到本地
