### ISSUE TITLE
[web-mac]mac最新客户端（arm64）修改后端服务后，重新启动会丢失后端服务为默认的localhost

### ISSUE THREAD

**Issue by trainliang** [hectorqin/reader#535]
**为避免无效问题和冗余问题，提问前请确认**
1. 你确定Google不能解决你的问题： 是的
2. 你确定已有的issue不能解决你的问题 ：没有搜索到
3. 你确定issue的title按照格式如下：[web/simple-web/server]：description

**Describe the bug 描述你遇到的问题**
A clear and concise description of what the bug is.  简洁有效的说明。
mac最新客户端3.2.8-05010322（arm64）修改后端服务后，点击版本号或重新启动会丢失后端服务为默认的localhost，

**To Reproduce 如何重现问题**
Steps to reproduce the behavior:  把你遇到的问题的发生步骤替换掉下面的内容：
1.下载最新版本mac客户端
2.首页修改后端地址为网络地址
3.点击左上角版本号会恢复默认地址
4.退出重新登录会恢复为默认地址
5.概率后端地址第一次配置检测会报错

**Expected behavior  期待修复的效果**
A clear and concise description of what you expected to happen. 简单描述。
后端地址可以保存配置，建议增加多地址配置（内网地址和公网地址）方便设备切换依然能访问和使用软件

**Screenshots 如有必要，可以截图说明**

**版本说明**
 - OS: [e.g. win]  说明操作系统 macos 14.3.1 (23D60)
 - Deploy Method 说明软件部署方式  安装
 - Program Version 说明软件版本 Reader.Desktop_3.2.8_aarch64.dmg
 - Browser [e.g. chrome, safari]  说明终端、浏览器型号

**Additional context 其他说明**
Add any other context about the problem here. 添加你认为有必要的内容，否则不写。
服务端为docker部署并拥有https域名。

**Comment by hectorqin** [comment]
都用了客户端，为啥要设置远程地址？要用远程地址，直接用浏览器访问，保存为 pwa 不行吗？

**Comment by trainliang** [comment]
> 都用了客户端，为啥要设置远程地址？要用远程地址，直接用浏览器访问，保存为 pwa 不行吗？

1.浏览器页面可能会被关闭，会被页面优化
2.功能确实有bug
3.我手边主要是ios、mac随身带，win不常开机，想要统一管理而且同步浏览记录，而且主要用听书大声朗读，部署到nas上的server了其他设备实在没有更好的方案用了

**Comment by hectorqin** [comment]
客户端自带了服务，不支持设置为远程server，而且客户端其实也是调用的系统浏览器
