### ISSUE TITLE
[web]最新docker部署server，使用ios的spa或mac的spa使用大声朗读或其他播放渠道BUG

### ISSUE THREAD

**Issue by trainliang** [hectorqin/reader#538]
**为避免无效问题和冗余问题，提问前请确认**
1. 你确定Google不能解决你的问题
2. 你确定已有的issue不能解决你的问题
3. 你确定issue的title按照格式如下：[web/simple-web/server]：description

**Describe the bug 描述你遇到的问题**
A clear and concise description of what the bug is.  简洁有效的说明。
遇到的问题：
1.手机端（测试saf、qq、uc）都有概率不能使用听书的三个方式，但使用夸克成功率高
2.mac使用客户端或spa时使用阅读三种方式都有大概率一直跳章节，不能听书

**To Reproduce 如何重现问题**
Steps to reproduce the behavior:  把你遇到的问题的发生步骤替换掉下面的内容：
1. 使用浏览器或客户端网页打开小说
2. 点击右下角听书图标
3. 测试浏览器、大声阅读、tts
4. 点击播放：测试会出现一下问题（立即停止播放、播放按钮切换但是章节一直跳且不能正常播放、正常播放无异常）

**Expected behavior  期待修复的效果**
A clear and concise description of what you expected to happen. 简单描述。
修复该问题，实现spa可以正常使用听书功能

**Screenshots 如有必要，可以截图说明**

**版本说明**
 - OS: [e.g. win]  说明操作系统  ios、mac
 - Deploy Method 说明软件部署方式 各种浏览器、mac客户端
 - Program Version 说明软件版本 v3.2.8-05010259
 - Browser [e.g. chrome, safari]  说明终端、浏览器型号 14.3.1 (23D60) 

**Additional context 其他说明**
Add any other context about the problem here. 添加你认为有必要的内容，否则不写。

**Comment by hectorqin** [comment]
为啥要不断切换方式？这三种是不同的方案，所以切换会有兼容问题

**Comment by trainliang** [comment]
> 为啥要不断切换方式？这三种是不同的方案，所以切换会有兼容问题

因为有的浏览器里有的方式不能用

**Comment by hectorqin** [comment]
现在大声朗读废了，只能使用httptts了
