### ISSUE TITLE
如何批量管理书籍啊？

### ISSUE THREAD

**Issue by ahmengkai** [hectorqin/reader#54]
比如批量删除 批量分组

**Comment by ahmengkai** [comment]
部分txt书籍导入提示java.lang.NullPointerException

**Comment by hectorqin** [comment]
这个功能不是很必要的操作，暂无计划

**Comment by hectorqin** [comment]
> 部分txt书籍导入提示java.lang.NullPointerException

试试beta版看看

**Comment by hectorqin** [comment]
Docker新版已支持
