### ISSUE TITLE
用docker版的服务器，打不开webdav配置文件

### ISSUE THREAD

**Issue by Elliont** [hectorqin/reader#541]
默认设置，输入http://IP:端口/reader3/webdav 后，提示

找不到 192.168.1.254 的网页找不到与以下网址对应的网页：http://192.168.1.254:8300/reader3/webdav
HTTP ERROR 404

输入http://IP:端口/reader3/webdav/ 后，提示
该网页无法正常运作如果问题仍然存在，请与网站所有者联系。
HTTP ERROR 405

不知道哪里出了问题

**Comment by hectorqin** [comment]
webdav 是不能用浏览器打开的
