### ISSUE TITLE
多书源搜索失败

### ISSUE THREAD

**Issue by kitmanten** [hectorqin/reader#542]
版本 ：3.2.8-05010259
docker部署的服务，在浏览器页面上选择多少书源查询，大多数情况是查不到书籍的，但是在手机的书源阅读上可以搜到，而且两个用的同样的书源数据

所以我想知道多书源查询的逻辑，是不支持模糊查询吗？

**Comment by kitmanten** [comment]
另外如果使用全部分组查询100%查不到数据

**Comment by hectorqin** [comment]
3.2.8 改成默认是精确搜索了，下个版本会改回模糊搜索

**Comment by hectorqin** [comment]
3.2.9 已改成默认模糊搜索
