### ISSUE TITLE
后端端口频繁掉怎么办？掉了之后就很难连接上

### ISSUE THREAD

**Issue by ethuh** [hectorqin/reader#549]
![image](https://github.com/hectorqin/reader/assets/23073985/da9d7e9b-d53b-4253-a8f2-b5ee75c972c2)
![image](https://github.com/hectorqin/reader/assets/23073985/83761419-6137-4502-b524-66505d871772)

这个地址前面是我的域名解析到的，然后我也没更改过，默认就是这个，不知道怎么老是掉后端，点了连接然后转圈，然后对话框消失，依然提示红色字体的点击设置后端接口前缀，应该怎么设置才不会掉呢？

版本：v3.2.9-06080715

**Comment by hectorqin** [comment]
一般是不需要设置的，看看你的后端服务是否正常

**Comment by ethuh** [comment]
> 一般是不需要设置的，看看你的后端服务是否正常

如何确认后端是否正常呢？我是docker-compose安装的

**Comment by since25** [comment]
这是cl的免费域名吧，1m的水管访问，好像连接后超过20000ms缓存时间就会报错停止连接后端，换局域网访问看看是不是不会出现，如果是的话就换别的服务商，不知道这样能不能帮到你

**Comment by kfab1983** [comment]
我是每次更新版本后就会遇到，解决办法是更新好后重启一下服务器就没事了。不知道问题在哪，也不知道问题怎么解决的。

**Comment by mizb** [comment]
我也经常掉，部署在甲骨文，套了cf，做了saas。感觉是网络的问题。

**Comment by skyofwing** [comment]
docker，使用ip直连。更严重的类似问题，我是后台连不上。任何一台设备都能很顺畅的打开应用主页并登录上，但就是后台连不上，如果网络不通的话，那为什么能正常打开应用首页，也能正常登录呢？日志里也没有任何报错。
![image](https://github.com/user-attachments/assets/a398d095-2fc6-44bb-92fa-2e257fedd5ab)

tcping 也没问题。
![67](https://github.com/user-attachments/assets/49931551-70d2-419f-863b-ceef29146437)

**Comment by 1103394945** [comment]
我也是docker部署的  一直掉后端    试了两三次了  一摸一样

**Comment by 1103394945** [comment]
> ![图像](https://private-user-images.githubusercontent.com/23073985/339037992-da9d7e9b-d53b-4253-a8f2-b5ee75c972c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNzgyMTUsIm5iZiI6MTczNDA3NzkxNSwicGF0aCI6Ii8yMzA3Mzk4NS8zMzkwMzc5OTItZGE5ZDdlOWItZDUzYi00MjUzLWE4ZjItYjVlZTc1Yzk3MmMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDA4MTgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNGEzMzk0NmY5NjlmNGUzNWYzYTA5MzdkNjZlNTk1YTI2NDkyMWUwYzNkMmEwYzc4MjEzZTI5OTRhZmFlNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4PEm1AsDteKKrQZfA0xdzhHJ4xvUiDixU2jAy0dOrpE) ![图像](https://private-user-images.githubusercontent.com/23073985/339038044-83761419-6137-4502-b524-66505d871772.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNzgyMTUsIm5iZiI6MTczNDA3NzkxNSwicGF0aCI6Ii8yMzA3Mzk4NS8zMzkwMzgwNDQtODM3NjE0MTktNjEzNy00NTAyLWI1MjQtNjY1MDVkODcxNzcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDA4MTgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzOTU5YTRjOGY5ODFmMTk3ZjdiZTQwNjM5MzUzNTkzNWE3Y2JiODVkY2Q2YzEzN2IyYTU4NmU4ODI0NGM1OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._rjXoYl6gM3EUu5aKAAoOv9527KGVl6E_1usM_zBGR4)
> 
> 这个地址前面是我的域名解析到的，然后我也没更改过，默认就是这个，不知道怎么老是掉后端，点了连接然后转圈，然后对话框消失，依然提示红色字体的点击设置后端接口前缀，应该怎么设置才不会掉呢？
> 
> 版本：v3.2.9-06080715

你好 请问你这个有解决方法了吗
