### ISSUE TITLE
希望可以增加自动加载下一章节功能以入可以设置翻页区域为左右翻页

### ISSUE THREAD

**Issue by yzbleaf** [hectorqin/reader#55]
希望可以增加自动加载下一章节功能以入可以设置翻页区域为左右翻页，现在每个章节翻到最后一页后，还需要点击加载下一页才能加载下一章节，同时在使用手机web时，上下翻页没有左右翻页方便，毕竟主要是用来翻下一页。

**Comment by hectorqin** [comment]
有左右翻页的

**Comment by hectorqin** [comment]
新版已支持自动缓存下一章
