### ISSUE TITLE
[web]IOS替换规则管理无法滚动

### ISSUE THREAD

**Issue by Yinghai75** [hectorqin/reader#550]
使用iphone在替换规则管理界面，当规则超过一屏后，无法滑动屏幕。

**To Reproduce 如何重现问题**
书架设置-替换规则。
每次都重现。

**版本说明**
 - OS: [e.g. win]  IOS 17.5.1
 - Deploy Method 威联通Container
 - Program Version 全部最新
 - Browser [e.g. chrome, safari]  Safari

**Comment by hectorqin** [comment]
在右侧可以滑动
