### ISSUE TITLE
[web] 使用VIA浏览器浏览界面时碰到的一些小问题

### ISSUE THREAD

**Issue by lalakiop** [hectorqin/reader#551]
**To Reproduce 如何重现问题**
1.  使用VIA浏览器时点击封面进入详情后返回会直接退回系统桌面；只有点击' X '才能返回书架，是不是直接返回后退回到书架界面符合直觉一些？
2. 建议目录的按钮防止在目前“阅读进度‘’的位置，这样会更符合直觉一些？
3. 书籍信息-修改封面-选择其他书源-选择封面-确认选择的图片-操作成功（操作成功的弹出的绿色提示有概率不会自己消失）
4. 在搜索书籍的时候返回也和问题1一样直接退回系统桌面，是不是直接返回后退回到书架界面符合直觉一些？

**版本说明**
 - OS: ；小米13使用via浏览器访问web界面
 - Deploy Method ：群晖7.2 docker安装服务
 - Program Version ：最新版
 - Browser [e.g. chrome, safari]  VIA浏览器

**Comment by hectorqin** [comment]
你的返回时浏览器提供的吧？目前只有两个页面，书架和阅读页面，在书架页面点击各种操作，显示的都是弹窗，只能用弹窗自带的关闭按钮关闭，不能使用返回关闭
