### ISSUE TITLE
[web]新增方案持续丢失

### ISSUE THREAD

**Issue by Yinghai75** [hectorqin/reader#552]
如题。

**To Reproduce 如何重现问题**
设置-配置方案-新增方案
使用一段时间后，特别是隔天后经常莫名丢失新增方案。 恢复备份可以成功恢复，但是仍然会莫名再丢失。

**版本说明**
 - OS: [e.g. win]  IOS
 - Deploy Method 威联通Container
 - Program Version 全部最新
 - Browser [e.g. chrome, safari]  safari (IOS/MacOS)

**Comment by hectorqin** [comment]
可能是浏览器清理了本地缓存

**Comment by M4nk1n** [comment]
所以这部分是写在浏览器缓存的？我记得服务端好想有这个配置文件的吧。可以修改默认配置吗？

**Comment by Yinghai75** [comment]
希望新增方案可以写在服务器的配置文件里

**Comment by Yinghai75** [comment]
主要那个默认的黑夜，字体实在太暗了，看不清楚

**Comment by hectorqin** [comment]
可以通过备份来保存到服务器

**Comment by Yinghai75** [comment]
现在是设置上做了什么更改都需要备份设置，下次开启WEB基本上都需要同步才能取回设置，十分不便且容易丢失设置。希望能够默认记住保存的设置修改。通常同步取回设置，是灾备而非常规手段。
