### ISSUE TITLE
[kindle]缓冲全部章节导致浏览器崩溃退出

### ISSUE THREAD

**Issue by Yinghai75** [hectorqin/reader#553]
如题。

**To Reproduce 如何重现问题**
只要缓冲全部章节，每次都会重现。

**Screenshots 如有必要，可以截图说明**
![Longshot-20240614132047](https://github.com/hectorqin/reader/assets/116246701/095a3db2-2a61-46cd-8899-ec1436cb18d8)

**版本说明**
 - OS: [e.g. win]  kindle oasis2，5.16.2固件
 - Deploy Method 威联通Container
 - Program Version 服务器版本3.2.9
 - Browser [e.g. chrome, safari]  kindle oasis2, 内置浏览器

**Comment by hectorqin** [comment]
kindle 配置太垃圾，没法优化
