### ISSUE TITLE
[web]：关于在PC端浏览器中使用上下方向键和空格键翻页的问题

### ISSUE THREAD

**Issue by bigoovip** [hectorqin/reader#554]
**为避免无效问题和冗余问题，提问前请确认**
1. 已确定Google不能解决我的问题
2. 已确定已有的issue不能解决我的问题
3. 已确定issue的title按照格式如下：[web/simple-web/server]：description

**Describe the bug 描述你遇到的问题**
目前使用的服务器是docker安装的v3.2.9-06080715版本，在PC端浏览器中使用上下方向键翻页不能翻一屏了，只能一行一行的翻，以前的版本都是一屏一屏的翻页；同时空格键翻页只能翻半屏，以前的版本也是一次翻一屏。

这导致在PC端阅读的体验大幅下降，我是用蓝牙遥控器翻页的，以前的服务器版本上下方向键直接对应向上或向下翻一屏，非常方便，如果不用蓝牙遥控器，我使用空格向下翻一页也非常方便，现在导致翻页一下，就要找一下翻页前看到的位置，太难受了。目前只能临时用油猴脚本实现上下方向键和空格键来翻一屏。

**To Reproduce 如何重现问题**
1. 使用docker安装v3.2.9-06080715版本服务
2. 使用PC端浏览器(我尝试了chrome和Edge，都会出现这个问题)
3. 使用上下方向键翻页和空格键翻页，即可看到当前翻页情况

**Expected behavior  期待修复的效果**
期待恢复成以前的翻页设定，在PC端浏览器中使用上下方向键翻页一次翻一屏；同时空格键翻页也能一次翻一屏。
或者可以自定义快捷键翻页设定。

**版本说明**
 - OS: windows11
 - Deploy Method : docker 部署的服务器
 - Program Version ：服务器版本v3.2.9-06080715
 - Browser ： chrome 版本 126.0.6478.62，Edge 版本 126.0.2592.56 (正式版本) (64 位)

**Comment by Yinghai75** [comment]
有同样问题

**Comment by kfab1983** [comment]
我是用脚本解决的

**Comment by LaoZhangRen** [comment]
> 我是用脚本解决的

在留个脚本

**Comment by hectorqin** [comment]
== 后续增加相关配置

**Comment by liukuan97** [comment]
存在同样问题，笔记本没有PageUp,PageDown按键，上下键翻页又被取消了，而空格键翻页只能翻半屏，翻页后总是得花时间去找到已经看到哪儿了，期待在下个版本可以解决

**Comment by Yinghai75** [comment]
我现在是直接按两下空格

**Comment by hectorqin** [comment]
已增加自定义快捷键设置
