### ISSUE TITLE
[web]：希望阅读界面添加侧栏常驻显示目录

### ISSUE THREAD

**Issue by coooooin** [hectorqin/reader#559]
类似于这种效果，目的是在跳章或者章节缺失后快速知道是否存在该情况
![image](https://github.com/hectorqin/reader/assets/108573937/78776572-ab09-44c2-81a3-fe8817508228)

**Comment by hectorqin** [comment]
阅读界面的逻辑已经很复杂了，而且没有多大必要加上这个功能
