### ISSUE TITLE
[server]：关于封面保存到本地的问题

### ISSUE THREAD

**Issue by MiloEvans** [hectorqin/reader#560]
1. 本地书仓的封面不会保存在本地（在线书籍可以）。
2. 更换封面或删除书籍不会同步删除本地封面图片。

**版本说明**
 - OS: [e.g. win]  iOS17
 - Deploy Method docker
 - Program Version v3.2.9
 - Browser [e.g. chrome, safari]  Safari

**Comment by hectorqin** [comment]
新版已处理
