### ISSUE TITLE
定时扫描硬盘问题

### ISSUE THREAD

**Issue by muyi0114** [hectorqin/reader#563]
安装并配置好docker并正常使用后，机械硬盘每隔一个小时会启动一次，而在此之前已经设置好了硬盘自动休眠且能正常休眠。尝试先安装docker在固态盘后再插入机械盘，问题依旧，机械硬盘不建立文件夹问题依旧，在停止docker后，问题解决。
这个docker访问硬盘的机制是什么？能否取消定时扫描非安装硬盘？

**Comment by muyi0114** [comment]
以下是部分硬盘状态日志，8点25分保持standby是因为停止了docker：
Fri Jul 12 00:20:01 CST 2024 drive state is: standby
Fri Jul 12 00:25:01 CST 2024 drive state is: active/idle
Fri Jul 12 00:30:01 CST 2024 drive state is: active/idle
Fri Jul 12 00:35:01 CST 2024 drive state is: active/idle
Fri Jul 12 00:40:02 CST 2024 drive state is: standby
Fri Jul 12 00:45:02 CST 2024 drive state is: standby
Fri Jul 12 00:50:02 CST 2024 drive state is: standby
Fri Jul 12 00:55:02 CST 2024 drive state is: standby
Fri Jul 12 01:00:02 CST 2024 drive state is: standby
Fri Jul 12 01:05:02 CST 2024 drive state is: active/idle
Fri Jul 12 01:10:01 CST 2024 drive state is: active/idle
Fri Jul 12 01:15:01 CST 2024 drive state is: active/idle
Fri Jul 12 01:20:01 CST 2024 drive state is: active/idle
Fri Jul 12 01:25:01 CST 2024 drive state is: active/idle
Fri Jul 12 01:30:01 CST 2024 drive state is: active/idle
Fri Jul 12 01:35:01 CST 2024 drive state is: active/idle
Fri Jul 12 01:40:01 CST 2024 drive state is: standby
Fri Jul 12 01:45:01 CST 2024 drive state is: standby
Fri Jul 12 01:50:01 CST 2024 drive state is: standby
Fri Jul 12 01:55:01 CST 2024 drive state is: standby
Fri Jul 12 02:00:01 CST 2024 drive state is: standby
Fri Jul 12 02:05:01 CST 2024 drive state is: standby
Fri Jul 12 02:10:01 CST 2024 drive state is: standby
Fri Jul 12 02:15:01 CST 2024 drive state is: standby
Fri Jul 12 02:20:01 CST 2024 drive state is: standby
Fri Jul 12 02:25:01 CST 2024 drive state is: active/idle
Fri Jul 12 02:30:01 CST 2024 drive state is: active/idle
Fri Jul 12 02:35:01 CST 2024 drive state is: active/idle
Fri Jul 12 02:40:01 CST 2024 drive state is: standby
Fri Jul 12 02:45:01 CST 2024 drive state is: standby
Fri Jul 12 02:50:01 CST 2024 drive state is: standby
Fri Jul 12 02:55:01 CST 2024 drive state is: standby
Fri Jul 12 03:00:01 CST 2024 drive state is: standby
Fri Jul 12 03:05:01 CST 2024 drive state is: standby
Fri Jul 12 03:10:01 CST 2024 drive state is: active/idle
Fri Jul 12 03:15:01 CST 2024 drive state is: active/idle
Fri Jul 12 03:20:01 CST 2024 drive state is: active/idle
Fri Jul 12 03:25:01 CST 2024 drive state is: active/idle
Fri Jul 12 03:30:01 CST 2024 drive state is: active/idle
Fri Jul 12 03:35:01 CST 2024 drive state is: active/idle
Fri Jul 12 03:40:01 CST 2024 drive state is: standby
Fri Jul 12 03:45:01 CST 2024 drive state is: standby
Fri Jul 12 03:50:01 CST 2024 drive state is: standby
Fri Jul 12 03:55:01 CST 2024 drive state is: standby
Fri Jul 12 04:00:01 CST 2024 drive state is: standby
Fri Jul 12 04:05:01 CST 2024 drive state is: standby
Fri Jul 12 04:10:01 CST 2024 drive state is: standby
Fri Jul 12 04:15:01 CST 2024 drive state is: standby
Fri Jul 12 04:20:01 CST 2024 drive state is: standby
Fri Jul 12 04:25:01 CST 2024 drive state is: active/idle
Fri Jul 12 04:30:01 CST 2024 drive state is: active/idle
Fri Jul 12 04:35:01 CST 2024 drive state is: active/idle
Fri Jul 12 04:40:01 CST 2024 drive state is: standby
Fri Jul 12 04:45:01 CST 2024 drive state is: standby
Fri Jul 12 04:50:01 CST 2024 drive state is: standby
Fri Jul 12 04:55:01 CST 2024 drive state is: standby
Fri Jul 12 05:00:01 CST 2024 drive state is: standby
Fri Jul 12 05:05:01 CST 2024 drive state is: standby
Fri Jul 12 05:10:01 CST 2024 drive state is: standby
Fri Jul 12 05:15:01 CST 2024 drive state is: standby
Fri Jul 12 05:20:01 CST 2024 drive state is: standby
Fri Jul 12 05:25:01 CST 2024 drive state is: active/idle
Fri Jul 12 05:30:01 CST 2024 drive state is: active/idle
Fri Jul 12 05:35:01 CST 2024 drive state is: active/idle
Fri Jul 12 05:40:01 CST 2024 drive state is: standby
Fri Jul 12 05:45:01 CST 2024 drive state is: standby
Fri Jul 12 05:50:01 CST 2024 drive state is: standby
Fri Jul 12 05:55:01 CST 2024 drive state is: active/idle
Fri Jul 12 06:00:01 CST 2024 drive state is: active/idle
Fri Jul 12 06:05:01 CST 2024 drive state is: active/idle
Fri Jul 12 06:10:01 CST 2024 drive state is: standby
Fri Jul 12 06:15:01 CST 2024 drive state is: standby
Fri Jul 12 06:20:01 CST 2024 drive state is: standby
Fri Jul 12 06:25:01 CST 2024 drive state is: active/idle
Fri Jul 12 06:30:01 CST 2024 drive state is: active/idle
Fri Jul 12 06:35:01 CST 2024 drive state is: active/idle
Fri Jul 12 06:40:01 CST 2024 drive state is: standby
Fri Jul 12 06:45:01 CST 2024 drive state is: standby
Fri Jul 12 06:50:01 CST 2024 drive state is: standby
Fri Jul 12 06:55:01 CST 2024 drive state is: standby
Fri Jul 12 07:00:01 CST 2024 drive state is: standby
Fri Jul 12 07:05:01 CST 2024 drive state is: standby
Fri Jul 12 07:10:01 CST 2024 drive state is: standby
Fri Jul 12 07:15:01 CST 2024 drive state is: standby
Fri Jul 12 07:20:01 CST 2024 drive state is: standby
Fri Jul 12 07:25:01 CST 2024 drive state is: active/idle
Fri Jul 12 07:30:01 CST 2024 drive state is: active/idle
Fri Jul 12 07:35:01 CST 2024 drive state is: active/idle
Fri Jul 12 07:40:01 CST 2024 drive state is: standby
Fri Jul 12 07:45:01 CST 2024 drive state is: standby
Fri Jul 12 07:50:01 CST 2024 drive state is: standby
Fri Jul 12 07:55:01 CST 2024 drive state is: standby
Fri Jul 12 08:00:01 CST 2024 drive state is: standby
Fri Jul 12 08:05:01 CST 2024 drive state is: standby
Fri Jul 12 08:10:01 CST 2024 drive state is: standby
Fri Jul 12 08:15:01 CST 2024 drive state is: standby
Fri Jul 12 08:20:01 CST 2024 drive state is: standby
Fri Jul 12 08:25:01 CST 2024 drive state is: standby
Fri Jul 12 08:30:01 CST 2024 drive state is: standby
Fri Jul 12 08:35:01 CST 2024 drive state is: standby
Fri Jul 12 08:40:01 CST 2024 drive state is: standby
Fri Jul 12 08:45:01 CST 2024 drive state is: standby
Fri Jul 12 08:50:01 CST 2024 drive state is: standby
Fri Jul 12 08:55:01 CST 2024 drive state is: standby

**Comment by hectorqin** [comment]
这个不清楚
