### ISSUE TITLE
[Docker-Compose]Windows Docker-Compose 重启丢失数据

### ISSUE THREAD

**Issue by Tamanegii** [hectorqin/reader#564]
**为避免无效问题和冗余问题，提问前请确认**
1. 你确定Google不能解决你的问题
2. 你确定已有的issue不能解决你的问题
3. 你确定issue的title按照格式如下：[web/simple-web/server]：description

**Describe the bug 描述你遇到的问题**
我在Windows平台的Docker-Desktop中部署了这个项目，但是每次电脑重启的时候都会发生所有存储数据全部丢失的Bug，怀疑是配置中的volumes设置出现了问题，但是不知道应该如何修改。

**To Reproduce 如何重现问题**
Steps to reproduce the behavior:  把你遇到的问题的发生步骤替换掉下面的内容：
1. 重启Windows
2. 打开Docker项目
3. 所有数据全部丢失

**Expected behavior  期待修复的效果**
Windows重启不影响数据

**Screenshots 如有必要，可以截图说明**

**版本说明**
 - OS: [e.g. win]  win
 - Deploy Method Docker-Desktop
 - Program Version 4.28.0
 - Browser [e.g. chrome, safari]  Edge

**Additional context 其他说明**
Add any other context about the problem here. 添加你认为有必要的内容，否则不写。

**Comment by w211691** [comment]
配置挂载到本地吧
