### ISSUE TITLE
请教一下，为什么阅读进度手机APP可以同步到网页，但网页的不能同步到APP？

### ISSUE THREAD

**Issue by long533150** [hectorqin/reader#565]
请教一下，为什么阅读进度手机APP可以同步到网页，但网页的不能同步到APP？
正常架设成功，之前双端都可以同步，重新架设后就不行了

**Comment by hectorqin** [comment]
重新架设是做了什么操作？

**Comment by long533150** [comment]
> 重新架设是做了什么操作？

没有其他操作，就按照Docker-Compose版架设的，系统是Ubuntu
webdav文件夹里阅读进度的文件也在，
APP同步到网页是正常的，网页端到APP就不行
现在我发现，如果APP上打开“自动跳转最近阅读”的话，就可以同步网页端第一本书的阅读进度，但其他的就不能同步

**Comment by hectorqin** [comment]
这个得看APP那边是否做了更新的操作
