### ISSUE TITLE
希望能添加批量更新命令

### ISSUE THREAD

**Issue by since25** [hectorqin/reader#567]
Docker版
书架内的书籍较多，3000+书籍全选点击批量缓存到服务器，首先是看不到缓存进度，后台看docker流量跑的也不快，感觉没有在缓存，而且好像是需要一直开着浏览器才行，能不能通过进入容器后使用命令后台更新？

**Comment by hectorqin** [comment]
有必要批量缓存这么多书到服务器吗？

**Comment by since25** [comment]
谢谢作者回复
主要原因是怕书源失效以后很多书看不了，然后有时候点进未缓存的书籍时会提示未配置书源，返回书架重复几次后又能够刷新出内容（还是原来的书源），所以希望能一劳永逸的解决缓存问题，如果这个比较麻烦去实现的话，我就尽量以安卓版阅读去缓存然后导出到webdav再看。
顺便一提，如果导入比较多的本地书仓>200本，载入就会比较卡（J4125-ESXI-ISTOREOS-DOCKER，不知道是不是透了太多层影响性能），另外在书籍管理的部分好像不能按照书架的分组进行管理（试着用搜索关键字的方式好像也不行，搜索的关键词匹配好像只匹配到书名，是否可以加入分组匹配这样方便管理？）
谢谢！

**Comment by hectorqin** [comment]
书籍按分组管理，可以考虑加一下。批量缓存的话，有空看看吧

**Comment by since25** [comment]
好的，谢谢哥

**Comment by hectorqin** [comment]
新版已添加
