### ISSUE TITLE
[server]：建议添加书源去重功能

### ISSUE THREAD

**Issue by MiloEvans** [hectorqin/reader#569]
书源数量一千条以上或数千条的时候，大量重复的书源会无意义的拖慢换源速度（或是选择书源的时候充斥着重复书源）。

http://x.x.x
http://x.x.x/
http://x.x.x#aa
http://x.x.x/#aa

建议添加书源去重功能。

**Comment by hectorqin** [comment]
这个建议使用其他的工具去重
