### ISSUE TITLE
部署不成功

### ISSUE THREAD

**Issue by JackieHeCc** [hectorqin/reader#570]
使用docker-compose、一键部署、Railway均不成功，访问ip:端口，提示502，防火墙也放行了对应的端口，不知道哪里出问题了。。。

**Comment by JackieHeCc** [comment]
在我的另外一台Windows server服务器上安装后可以访问这台服务器的ip+端口了，很奇怪。。。

**Comment by hectorqin** [comment]
起不来就查看日志有没有报错

**Comment by JackieHeCc** [comment]
> 起不来就查看日志有没有报错

另外一台WIndows服务器上可以了，Debian上面那个放弃了，不搞了，能用就行。
