### ISSUE TITLE
docker版3.2.8升级3.2.10不成功，重新部署也打不开了。

### ISSUE THREAD

**Issue by xfxme** [hectorqin/reader#571]
docker版3.2.8升级3.2.10不成功，重新部署也打不开了。
safari无反应，其他浏览器网页提示503
控制台都是显示ReaderApplication Started

**Comment by hectorqin** [comment]
503 应该是走了nginx等反向代理转发，检查一下你的反向代理软件

**Comment by xfxme** [comment]
没有代理软件，服务器和之前都是一样的设置没有变过的。就是升级了就打不开了
