### ISSUE TITLE
docker 系统占用

### ISSUE THREAD

**Issue by yanxin152133** [hectorqin/reader#575]
就缓存个章节，占用就这么高嘛？
![image](https://github.com/user-attachments/assets/bf97e17d-bdf7-4aba-8413-34f52a83292f)

**Comment by since25** [comment]
建议你查一下你的书源，我也遇到类似的高占用问题了，后来排查了一下是因为书源地址解析的问题，比如我有一批书的书源是需要走代理才能访问的，查看日志就会看到host解析DNS失败的提示，貌似目前会持续向书源地址请求直到超时，然后并行任务似乎没有取消，希望作者可以设置一个超时跳过之类的设定，这个bug严格意义上也不算问题，最好是自己排查一下。

**Comment by yanxin152133** [comment]
确实有好多超时的
![image](https://github.com/user-attachments/assets/e30774b8-445e-45aa-ac1b-3790d9546b57)

**Comment by since25** [comment]
是的，能找到问题就行，我排查这个也试了好久，服务器版的不像安卓的阅读会自动换源主要是.

**Comment by yanxin152133** [comment]
> 是的，能找到问题就行，我排查这个也试了好久，服务器版的不像安卓的阅读会自动换源主要是.

谢了，无脑加了三千多个书源，是时候精简下了
