### ISSUE TITLE
[desktop]：MacOS桌面版本启动失败

### ISSUE THREAD

**Issue by endlessc** [hectorqin/reader#577]
**Describe the bug 描述你遇到的问题**
下载最新版本的MacOS版本桌面端，安装后启动直接一闪而过，没有任何反应，不存在权限和安全性问题，就是启动没反应

**Expected behavior  期待修复的效果**
MacOS M1环境下可以正常运行

**版本说明**
 - OS: MacOS Sonoma 14.6 (23G80) M1 Pro
 - Deploy Method
 桌面版
 - Program Version 
 [Reader Desktop v3.2.10](https://github.com/hectorqin/reader/releases/tag/v3.2.10)

**Comment by hectorqin** [comment]
建议使用 server 版
