### ISSUE TITLE
[web]段落间连读优化

### ISSUE THREAD

**Issue by Yinghai75** [hectorqin/reader#579]
已经打开连读优化的开关，但是段落之间仍然有短时间的停顿。 配置的是https, 微软Azure TTS.

**Expected behavior  期待修复的效果**
希望能达到阅读APP朗读时的连读效果， 感觉不到段落之间有额外的停顿。

**版本说明**
 - OS: [e.g. win]  macOS最新
 - Deploy Method： Docker
 - Program Version 最新
 - Browser [e.g. chrome, safari]  IOS, Safari

**Comment by hectorqin** [comment]
可以用电脑看看，朗读时网络请求的情况
