### ISSUE TITLE
使用cloudflared绑定域名开启ssl访问会导致封面加载失败

### ISSUE THREAD

**Issue by ycj1379** [hectorqin/reader#587]
本人在debian系统中，使用Docker部署，命令为：
多用户版(建议修改映射端口)
docker run -d --restart=always --name=reader -v $(pwd)/logs:/logs -v $(pwd)/storage:/storage -p 8080:8080 hectorqin/reader java -jar /app/bin/reader.jar --spring.profiles.active=prod --reader.app.secure=true --reader.app.secureKey=管理密码 --reader.app.inviteCode=注册邀请码

然后使用cloudflared绑定域名开启ssl访问，发现封面加载失败，使用端口的情况下可以正常加载的。
进入Chrome控制台追踪发现域名后增加多了一段".hxxxx.com/reader3"，封面的链接地址为“https://reader3.hxxx.com/.hxxxx.com/reader3/assets/xxxxxxn/covers/ee530f79eb6ec53f73e741692c55b537.jpg”
如果直接访问”https://reader3.hxxx.com/assets/xxxxxxn/covers/ee530f79eb6ec53f73e741692c55b537.jpg“是可以正常打开封面图片的。
![微信截图_20240906110749](https://github.com/user-attachments/assets/a581bbac-b22e-4091-ac5d-55bfbc4660b9)

请问这个问题需要如何解决呢？

**Comment by hectorqin** [comment]
在书架页面修改一下接口地址

**Comment by woodchen-ink** [comment]
> 在书架页面修改一下接口地址

不好意思大佬, 我也有这个问题, 没找到修改接口地址的地方, 请问可以截个图吗

**Comment by hectorqin** [comment]
书架页面，后端设定
