### ISSUE TITLE
我的书源特别大，5000多条，但我的带宽不是很大 4m小水管，加载书源过程中超过30秒自动timeout

### ISSUE THREAD

**Issue by Susiia** [hectorqin/reader#589]
https://legado.uxxxxxxxxxr.top/reader3/getBookSources?simple=1&accessToken=sxxxa:6xxxxxx0&v=17xxxxxx2
![1726726961384](https://github.com/user-attachments/assets/6ba65eb5-e5bc-4dd1-aaf8-0d58ab7acf28)

**Comment by Susiia** [comment]
我的nginx 相关配置
proxy_read_timeout   3600s;
client_max_body_size 5000m;

**Comment by hectorqin** [comment]
建议精简书源
