### ISSUE TITLE
Safari添加到主屏幕没有按键

### ISSUE THREAD

**Issue by ahuaiab** [hectorqin/reader#591]
![IMG_9023](https://github.com/user-attachments/assets/82caf06c-7a77-4d3b-b5b0-d85f4615999e)

ios版本18.0
在华为云 docker compose部署
safari浏览器里正常 但是添加到主屏幕就无法显示

**Comment by hectorqin** [comment]
进入到阅读界面，点击阅读设置，选择正常模式，不要选择简洁模式
