### ISSUE TITLE
[web/server]希望大佬优化下iOS/iPadOS端通过Safari分享到书签到桌面的图标显示（已附教程）

### ISSUE THREAD

**Issue by Profitter** [hectorqin/reader#592]
**Describe the bug 描述你遇到的问题**
issue如题，非常感谢大佬开发此项目，目前美中不足只有这个关于图标的小问题，下文截图可见未适配Safari的展示样式。烦请大佬抽空解决下这个小问题，[教程已附上](https://blog.zhheo.com/p/5728da61.html)，在此感谢。

**Screenshots 如有必要，可以截图说明**
![IMG_0985](https://github.com/user-attachments/assets/01a0c67c-2475-473f-ac3d-a24cdaf9a983)

**版本说明**
 - OS: iOS/iPadOS
 - Deploy Method docker
 - Program Version v3.2.10-07270648
 - Browser Safari

**Comment by hectorqin** [comment]
我这边是用的矩形图标哦，而且我这边测试ios上是正常的

**Comment by JamesWDGu** [comment]
Hi @hectorqin ,

iOS 18.2.1 是没问题的
iPad 18.2.1 就和上边截图显示的一样

感觉是 iPad 需要单独适配一下，桌面放一个带黑边的 icon 确实不好看。
如果需要我单独开一个 issue，请告知。感谢！

**Comment by JamesWDGu** [comment]
> Hi [@hectorqin](https://github.com/hectorqin) ,
> 
> iOS 18.2.1 是没问题的 iPad 18.2.1 就和上边截图显示的一样
> 
> 感觉是 iPad 需要单独适配一下，桌面放一个带黑边的 icon 确实不好看。 如果需要我单独开一个 issue，请告知。感谢！

iPhone 16 pro & iPad mini 7
