### ISSUE TITLE
每次从阅读界面返回到书架界面总是需要刷新

### ISSUE THREAD

**Issue by lalakiop** [hectorqin/reader#593]
**Describe the bug 描述你遇到的问题**
1. 每次从阅读界面返回到书架界面总是需要刷新，特别是搜索界面进去试阅读后返回到搜索，总是需要刷新很长时间

2. 书架的书无法进行搜索，书籍一多每次找书需要翻很长时间

3. 搜索浏览没有历史记录，会找不到之前搜的书籍

**版本说明**
 - OS: [e.g. win]  说明操作系统
 - 群晖
 - Deploy Method 说明软件部署方式.
 - docker

 - Program Version 说明软件版本
 - 最新版
 - Browser [e.g. chrome, safari]  说明终端、浏览器型号
 - safari

**Additional context 其他说明**
Add any other context about the problem here. 添加你认为有必要的内容，否则不写。

**Comment by hectorqin** [comment]
1、可能是你的书太多了，我后面看看怎么优化一下
2、书架的书是可以搜索的，点击编辑就可以搜索了
3、暂时没想好怎么加
