### ISSUE TITLE
搜索书源分组下拉框会导致整个浏览器卡死

### ISSUE THREAD

**Issue by sleikang** [hectorqin/reader#597]
![image](https://github.com/user-attachments/assets/fc38c96f-8d17-479c-9b82-c65d569cb531)
希望这个分组不要全部显示出来或者动态加载（触底或者触定加载）现在有个书源分组太多导致这个下拉框渲染几千个分组直接卡死整个浏览器

**Comment by sleikang** [comment]
我试了把书源分组合并了也很卡，现在23000多个书源
![image](https://github.com/user-attachments/assets/9bb19705-f56a-47a2-8e56-0ab93ac32951)

**Comment by hectorqin** [comment]
建议精简书源
