### ISSUE TITLE
无法找到jdk路径

### ISSUE THREAD

**Issue by pheotry** [hectorqin/reader#599]
![image](https://github.com/user-attachments/assets/a6fe9fd4-aeb4-4783-b642-d40384f8caae)
![image](https://github.com/user-attachments/assets/4c7220da-6ef6-4284-a135-894282920b64)
![image](https://github.com/user-attachments/assets/27183597-f699-4d76-abd5-7bd5879bea09)

**Comment by hectorqin** [comment]
换个目录看看，有可能是权限问题
