### ISSUE TITLE
希望增加opds支持，对接calibre书库

### ISSUE THREAD

**Issue by czahoi** [hectorqin/reader#60]
对接calibre自有书源

**Comment by hectorqin** [comment]
opds不是自带web服务吗？怎么个对接法？

**Comment by flyxj** [comment]
> 对接calibre自有书源

顶起来。

**Comment by flyxj** [comment]
> opds不是自带web服务吗？怎么个对接法？

我理解的是还是用 calibre-web 管理，然后用 reader 只是获取目录，远程加载 opds 源，可以在线看。

**Comment by hectorqin** [comment]
直接将calibre的书籍目录挂载为本地书仓的目录，然后在书架导入即可
