### ISSUE TITLE
GBK网页需要使用webView时解析到的内容乱码

### ISSUE THREAD

**Issue by sleikang** [hectorqin/reader#603]
![image](https://github.com/user-attachments/assets/ee6bf632-7d01-4ae7-9cf6-0edd5be6cc61)
已经使用了"charset":"gbk"好像没有用，日志里面全是乱码的，搜索页面需要webView日志乱码解析出来的书名也是乱码，其他页面不需要webView日志乱码解析出来的是正常的

**Comment by sleikang** [comment]
{
    "bookSourceUrl": "https://www.52wx.com",
    "bookSourceType": 0,
    "bookSourceName": "笔趣阁",
    "bookSourceGroup": "私有书源",
    "bookSourceComment": "",
    "loginUrl": "",
    "loginUi": "",
    "loginCheckJs": "",
    "concurrentRate": "",
    "header": "",
    "bookUrlPattern": "",
    "searchUrl": "/modules/article/search.php,{\"charset\":\"gbk\",\"method\":\"POST\",\"body\":\"searchkey={{java.encodeURI(key,'gbk')}}\",\"headers\":{\"User-Agent\":\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0\",\"Referer\":\"https://www.52wx.com/modules/article/search.php\",\"Origin\":\"https://www.52wx.com\",\"Content-Type\":\"application/x-www-form-urlencoded\"},\"webView\":true}",
    "exploreUrl": "玄幻奇幻::https://www.52wx.com/list/1_{{page}}.html,{\"charset\":\"gbk\"}\n武侠仙侠::https://www.52wx.com/list/2_{{page}}.html,{\"charset\":\"gbk\"}\n都市言情::https://www.52wx.com/list/3_{{page}}.html,{\"charset\":\"gbk\"}\n历史军事::https://www.52wx.com/list/4_{{page}}.html,{\"charset\":\"gbk\"}\n科幻灵异::https://www.52wx.com/list/5_{{page}}.html,{\"charset\":\"gbk\"}\n网游竞技::https://www.52wx.com/list/6_{{page}}.html,{\"charset\":\"gbk\"}\n女生频道::https://www.52wx.com/list/7_{{page}}.html,{\"charset\":\"gbk\"}",
    "enabled": true,
    "enabledExplore": true,
    "weight": 0,
    "customOrder": 0,
    "lastUpdateTime": 1730627995165,
    "ruleSearch": {
        "bookList": ".txt-list:nth-child(2) li:nth-child(n+2) ",
        "name": "> .s2 > a@text",
        "author": " > .s4@text",
        "kind": " > .s1@text",
        "lastChapter": "> .s3 > a@text",
        "bookUrl": "> .s2 > a@href"
    },
    "ruleExplore": {
        "bookList": ".txt-list-row5 li",
        "name": " > .s2 > a@text",
        "author": " > .s4@text",
        "kind": " > .s1@text",
        "lastChapter": " > .s3 > a@text",
        "bookUrl": " > .s2 > a@href"
    },
    "ruleBookInfo": {
        "name": ".top > h1@text",
        "author": ".fix > p:nth-child(1)@text##作者：",
        "intro": ".desc@text",
        "coverUrl": ".imgbox img@src"
    },
    "ruleToc": {
        "chapterList": "#section-list li",
        "chapterName": " > a@text",
        "chapterUrl": " > a@href"
    },
    "ruleContent": {
        "content": "#content@html"
    }
}

**Comment by hectorqin** [comment]
试试新版本看看
