### ISSUE TITLE
IOS18.1 web端大声朗读不能用了

### ISSUE THREAD

**Issue by wxyhxh** [hectorqin/reader#604]
**为避免无效问题和冗余问题，提问前请确认**
1. 你确定Google不能解决你的问题
2. 你确定已有的issue不能解决你的问题
3. 你确定issue的title按照格式如下：[web/simple-web/server]：description

**Describe the bug 描述你遇到的问题**
IOS web端大声朗读不能用了，朗读方式选浏览器的话，中文语音只有婷婷等几个死板的声音。

**To Reproduce 如何重现问题**
Steps to reproduce the behavior:  把你遇到的问题的发生步骤替换掉下面的内容：

**Expected behavior  期待修复的效果**
A clear and concise description of what you expected to happen. 简单描述。

**Screenshots 如有必要，可以截图说明**

**版本说明**
 - OS: ios
 - Deploy Method: docker
 - Program Version: v3.2.10-07270648
 - Browser [e.g. chrome, safari]  iphone、edge浏览器

**Additional context 其他说明**
Add any other context about the problem here. 添加你认为有必要的内容，否则不写。

**Comment by lklbjn** [comment]
我也一样，用Windows电脑打开edge浏览器或者Chrome【大声朗读】都没有声音了

**Comment by hectorqin** [comment]
大声朗读已经被微软禁用了，建议使用httptts
