### ISSUE TITLE
希望继续release  mac x64

### ISSUE THREAD

**Issue by ChitaGideon** [hectorqin/reader#605]
**Describe the bug 描述你遇到的问题**
A clear and concise description of what the bug is.  简洁有效的说明。
最新的几个版本release 都没有 mac x64

**To Reproduce 如何重现问题**
Steps to reproduce the behavior:  把你遇到的问题的发生步骤替换掉下面的内容：
1. Go to release 页面

**Expected behavior  期待修复的效果**
A clear and concise description of what you expected to happen. 简单描述。
希望新版本继续支持  mac x64

**Screenshots 如有必要，可以截图说明**

**版本说明**
 - OS: [e.g. win]  说明操作系统 mac
 - Deploy Method 说明软件部署方式  客户端
 - Program Version 说明软件版本  
 - Browser [e.g. chrome, safari]  说明终端、浏览器型号

**Additional context 其他说明**
Add any other context about the problem here. 添加你认为有必要的内容，否则不写。

**Comment by hectorqin** [comment]
action的macos版本太高，编译失败，直接使用 server 版吧
