### ISSUE TITLE
docker部署后任何书源点击都提示:java.net.UnknownHostException: xxx.xxx: Try again

### ISSUE THREAD

**Issue by ptcar** [hectorqin/reader#607]
感觉就是外网通不了，群晖docker部署的reader服务，最新版跟网上教程里的3.2.7版都一个问题。部署的是多用户版本。

**Comment by hectorqin** [comment]
检查一下是否能联网，或者换个书源看看

**Comment by ptcar** [comment]
已经发现是群晖打开防火墙的缘故，我关闭就可以正常搜书源，但是我本身开了ipv6，所以必须开启防火墙，已经放行了8080端口，还是不行，不知道还需要放行哪几个端口才能正常访问

**Comment by hectorqin** [comment]
需要允许所有出口流量
