### ISSUE TITLE
阅读界面不显示两边的功能按钮

### ISSUE THREAD

**Issue by ChenGaber** [hectorqin/reader#611]
阅读 v3.2.10-07270648 docker部署在群晖上，ipv6 ddns解析到域名，苹果15pm系统ios18.1.1使用alook浏览器访问，在阅读界面不显示左右两侧的功能按键，已截图
![IMG_4129](https://github.com/user-attachments/assets/23a5ccbe-3423-4735-9367-e8bc4dcc83c1)

**Comment by hectorqin** [comment]
看看是不是被拦截了，用safari打开看看
