### ISSUE TITLE
使用的docker-compose部署完后当书架中只有一本书并删除后会出现后端无法连接上

### ISSUE THREAD

**Issue by creeper2020** [hectorqin/reader#63]
![image](https://user-images.githubusercontent.com/30111010/166615023-45292c24-66d6-4788-ad00-6f9e1502a2ec.png)
![image](https://user-images.githubusercontent.com/30111010/166615043-373a995f-7d64-46d5-bbf0-94266cc7c7bf.png)
日志
[reader-2022-05-04.0.log](https://github.com/hectorqin/reader/files/8617574/reader-2022-05-04.0.log)

**Comment by creeper2020** [comment]
nginx反向代理没问题，因为使用原端口问题同样出现

**Comment by hectorqin** [comment]
已修复，试试docker新版

**Comment by creeper2020** [comment]
感谢大佬

**Comment by creeper2020** [comment]
> 已修复，试试docker新版

感谢大佬
