### ISSUE TITLE
文字排版问题

### ISSUE THREAD

**Issue by saintartoria** [hectorqin/reader#7]
手机使用阅读的时候，点击滑动书页会导致裁切错误，经常出现字只有一半的情况，希望可以解决一下
PS：跪求增加arm的docker版本。。

**Comment by hectorqin** [comment]
上下翻页没法准确裁切，可以使用左右翻页
arm版可以自己编译发布

**Comment by saintartoria** [comment]
左右翻页也是一样的，会导致裁切到一半的文字。。

**Comment by hectorqin** [comment]
你用手机访问   https://reader.htmake.com 看看

**Comment by saintartoria** [comment]
![1632360424(1)](https://user-images.githubusercontent.com/63177702/134442884-6a308784-c448-41c8-942c-74a278c09500.jpg)
![photo_2021-09-23_09-32-17](https://user-images.githubusercontent.com/63177702/134442888-7c3ef2e2-ff41-410d-96f8-c23619168ae5.jpg)
一个是我自己搭建的，调整了字体大小，一个是你公益的，默认设置

**Comment by saintartoria** [comment]
增加一个文本显示范围应该可以解决问题

**Comment by hectorqin** [comment]
使用 左右翻页模式

**Comment by saintartoria** [comment]
是左右翻页模式的，2个都是，并不是所有页面都会裁切错误，手机是S20U

**Comment by hectorqin** [comment]
奇怪，你这个手机怎么没有底部的菜单栏？

**Comment by saintartoria** [comment]
https://user-images.githubusercontent.com/63177702/134443375-a5dd9152-5674-4fdf-95a8-3f517f6aaa84.mp4

录了个屏，你看一下

**Comment by saintartoria** [comment]
> 奇怪，你这个手机怎么没有底部的菜单栏？

有，点击屏幕中央会呼出菜单栏，但是会覆盖文字，点击下一页就会隐藏

**Comment by hectorqin** [comment]
你不隐藏菜单栏试试

**Comment by saintartoria** [comment]
> 你不隐藏菜单栏试试

不行，安卓手机没有这个选项，我尝试了以网络应用模式安装桌面应用，也会有这个问题

**Comment by hectorqin** [comment]
那你换个手机浏览器试试？

**Comment by hectorqin** [comment]
这种兼容问题很难搞的

**Comment by saintartoria** [comment]
我尝试了三星浏览器，Chrome，alook浏览器，都是一样的情况..so我觉得设置一个显示范围应该可以解决问题

**Comment by hectorqin** [comment]
正常的阅读界面是这样的：

![image](https://user-images.githubusercontent.com/14220132/134444343-6f7faa63-a662-4f9b-ac6a-036a4f73b226.png)

**Comment by hectorqin** [comment]
你这显示的短了一截

**Comment by saintartoria** [comment]
> 你这显示的短了一截

这应该不是手机吧？我测试了iOS用safari也是同样的情况，保存桌面应用的话甚至会出现无法控制顶部设置的情况，完全无法点击。。

**Comment by saintartoria** [comment]
不对，重启了一下桌面应用确实可以了，但是顶部还是不太舒服，比如章节名被刘海给挡了。。顶部设置要仔细按才能点到，最好还是修改一下显示范围和适配一下常用分辨率，S20U的屏幕比例要比iPhone长一些的，估计是这个原因导致

**Comment by hectorqin** [comment]
查清楚了，是 `100vh` 这个样式兼容问题，之后的版本会修复的

**Comment by saintartoria** [comment]
感谢大佬

**Comment by hectorqin** [comment]
新版本应该修复了

**Comment by saintartoria** [comment]
吼，晚上回去就更新

**Comment by dumpmemory** [comment]
boox poke4 自带浏览器也会有这个问题 有什么方式修复一下么

**Comment by realtonyig** [comment]
我用的android15又出现左右滑动时，滑着滑着就开始切字了。越切越厉害，最后就左边显示上面的一部分字，右边显示本页的一部分字。没办法现在只能暂时用上下滑动。
版本 v3.2.14-05250935
