### ISSUE TITLE
建议docker基础镜像使用 ibm-semeru-runtimes:open-8u312-b07-jdk

### ISSUE THREAD

**Issue by ilay1678** [hectorqin/reader#74]
ibm-semeru-runtimes:open-8u312-b07-jdk 使用的jdk是openj9，能大幅度降低内存占用

**Comment by hectorqin** [comment]
现在内存占用应该比较低了吧？demo服务目前内存占用在 100M ~ 250M 左右

**Comment by ilay1678** [comment]
我刚搭建了一个，内存占用六百多，只添加了一个用户

**Comment by hectorqin** [comment]
用的最新版吗？

**Comment by hectorqin** [comment]
用的最新版吗？

**Comment by ilay1678** [comment]
最新的，用的docker-compose
自己用ibm-semeru-runtimes:open-8u312-b07-jdk本地打包后，内存占用200多M

**Comment by hectorqin** [comment]
你可以用docker限制一下内存使用的

实际内存占用可以访问接口  `http://ip:端口/reader3/getSystemInfo` 来获得内存信息

**Comment by ilay1678** [comment]
使用openj9 {"isSuccess":true,"errorMsg":"","data":{"freeMemory":"7M","totalMemory":"25M","maxMemory":"982M"}}
未使用时totalMemory是二百多

**Comment by hectorqin** [comment]
这个openj9有点厉害啊，就是镜像有点大

**Comment by ilay1678** [comment]
应该有更小的openj9，我用的这个是底层镜像貌似是debian或者Ubuntu，所以大

**Comment by ilay1678** [comment]
adoptopenjdk:8u292-b10-jre-openj9-0.26.0-focal 
这个小一些

**Comment by hectorqin** [comment]
已添加openj9镜像
