### ISSUE TITLE
反馈一些使用问题

### ISSUE THREAD

**Issue by zouhy2001** [hectorqin/reader#76]
首先非常感谢作者的辛苦付出!
刚刚使用docker成功部署,稍微体验了十分钟,我有遇到以下问题:

1. 希望文档能够稍稍详细一点点,比如列出登录的ip:port uname pwd,不是所有的人都会去详细的阅读yaml文件,部署起来可能稍微麻烦.

2. 不管是手机端,还是网页都遇到了设置scroll滚动的问题,(有点类似安卓里的framelayout的点击穿透的问题)
     pc端:鼠标滚动滚轮,有时文章界面滑动,有时设置项滑动
     ios:同样的问题,上下滑动,有时文章界面滑动,有时设置项滑动

3. 希望可以增加多样的左右翻页动效,现有的动效比较单一,滑动时给我一种顿挫的感觉,体验不是很友好.

4. 手机端希望可以设置是否隐藏文章title,做出类似沉浸状态栏的感觉,不然文章内容和状态栏的padding感觉很突兀.

电脑端我看着很舒服,手机端体验可能稍差,希望作者能够稍加改进,瑞斯拜!

**Comment by hectorqin** [comment]
1.文档可以提pr过来
2.滚动是没有问题的
3.这只是个网页，不支持其它特效。
4.这只是个网页，不支持
