### ISSUE TITLE
手机访问出现页码乱跳

### ISSUE THREAD

**Issue by Ndministrator** [hectorqin/reader#77]
有人跟我一样手机上阅读的时候,中间滑动过程中,总页数会浮动(比如28页总页数有时候又变26页,待会又变30页),导致当前页面乱跳,影响观看的情况嘛?
换了一个chrome的,一个手机系统原生的,好像都有这样的问题.
用桌面模式好像就不会.
不知道是不是浏览器的bug?

**Comment by hectorqin** [comment]
你的浏览器地址栏和工具栏是不是会变化？

**Comment by Ndministrator** [comment]
> 你的浏览器地址栏和工具栏是不是会变化？

chrome滑动到某个位置会隐藏掉地址栏,跟这个有关系吗?
大佬有遇到过没

**Comment by hectorqin** [comment]
地址栏隐藏会导致浏览器视口发生变化，页面就会计算，位置就会变，建议添加到桌面，使用 pwa 模式体验更加
