### ISSUE TITLE
iOS使用时的字体问题

### ISSUE THREAD

**Issue by itcbx** [hectorqin/reader#78]
为什么使用docker创建的服务端，在iOS系统中访问，设置字体比如楷体仿宋什么的都没有效果，不管怎么设置都是默认字体，有什么办法改变字体吗

**Comment by hectorqin** [comment]
ios没有内置这些字体，所以更换无效

**Comment by itcbx** [comment]
web端现在是不是有种技术是可以引用在线字体？

**Comment by hectorqin** [comment]
字体文件很大的，一个都要几十M，网页不适合引用远程字体
