### ISSUE TITLE
storage变为storage-backup

### ISSUE THREAD

**Issue by lq-259** [hectorqin/reader#8]
服务器版重启服务器后再启动reader.jar
storage会变为storage-backup
有什么办法避免吗

**Comment by hectorqin** [comment]
从旧版升级的会这样，直接用新版就没事了，见 README

**Comment by lq-259** [comment]
> 从旧版升级的会这样，直接用新版就没事了，见 README

没有升级，就是重启后这样

**Comment by hectorqin** [comment]
把  storage-backup 重命名为 storage， 手动创建  storage/data/default 目录，然后重启服务

**Comment by lq-259** [comment]
> 把 storage-backup 重命名为 storage， 手动创建 storage/data/default 目录，然后重启服务

好的
