### ISSUE TITLE
书海功能中的标签不能滚动

### ISSUE THREAD

**Issue by CNorato** [hectorqin/reader#80]
![Issue](https://user-images.githubusercontent.com/33372866/167891450-fa9c9d3a-847e-41be-a43a-36ea9121c341.png)
如图, 如果标签足够多或足够长则后面的标签就看不到了. 还有图中的这些标签也没有完全解析.

**Comment by hectorqin** [comment]
看不见但是可以滚动，json标签暂时无法解析

**Comment by CNorato** [comment]
移动端网页可以滚动，但电脑上的网页不行，只能通过选中文本来拖到后面，这个展开能否改为y方向上的？

**Comment by CNorato** [comment]
好吧

**Comment by CNorato** [comment]
添加一个el-scrollbar的话可以吗？
