### ISSUE TITLE
希望可以增加HTTPS支持

### ISSUE THREAD

**Issue by UnicornUnderMoon** [hectorqin/reader#83]
本人自己搭了个网站，给域名申请了SSL证书。用服务器版本的时候，使用FIREFOX连HTTP下的端口，浏览器自动跳到HTTPS协议，浏览器反馈“建立安全连接失败”，造成无法登录。安卓版的阅读里设置webdav也遇到问题，使用http地址备份时，备份不成功。所以希望能添加HTTPS支持功能。
另外，希望尽早出下怎么配置服务器版运行参数的说明。

**Comment by hectorqin** [comment]
请用 nginx 反向代理，来使用 HTTPS
