### ISSUE TITLE
什么时候可以适配订阅源的支持呢 

### ISSUE THREAD

**Issue by Felmon** [hectorqin/reader#84]
比如一程大佬的订阅源：https://e-c.coding.net/p/yicheng/d/YD/git/raw/master/dy.json

**Comment by Felmon** [comment]
以及手机端侧滑显示侧边栏和手机侧滑返回冲突

**Comment by hectorqin** [comment]
侧滑冲突无法解决，目前支持导入远程书源，订阅书源功能暂时没有必要

**Comment by Felmon** [comment]
不是订阅书源哦，是阅读3.0的订阅源，可能是JavaScript的原因？

**Comment by Felmon** [comment]
> 侧滑冲突无法解决，目前支持导入远程书源，订阅书源功能暂时没有必要

好吧。。或者改下排版？用底部导航栏？

**Comment by hectorqin** [comment]
rss源应该也是支持的哦

**Comment by hectorqin** [comment]
什么情况下会有侧滑返回？你没有用pwa模式吗？

**Comment by Felmon** [comment]
> rss源应该也是支持的哦
https://e-c.coding.net/p/yicheng/d/YD/git/raw/master/dy.json 比如这个是阅读的 rss源，导入后并不能点击打开

**Comment by Felmon** [comment]
> 什么情况下会有侧滑返回？你没有用pwa模式吗？

ios添加到桌面依旧有侧滑返回呀

**Comment by Felmon** [comment]
大佬可以针对ios作优化不。。。。感觉最近用服务器版的都是ios刚需

**Comment by hectorqin** [comment]
有什么建议可以提出来，合理的话我有空就弄弄

**Comment by kindomLee** [comment]
> > rss源应该也是支持的哦
> > https://e-c.coding.net/p/yicheng/d/YD/git/raw/master/dy.json 比如这个是阅读的 rss源，导入后并不能点击打开

這個好像還是沒解決？比如說影片的 rss 源

**Comment by hectorqin** [comment]
Docker新版已支持多tab订阅源
