### ISSUE TITLE
手机网页端无法呼出侧边栏搜索

### ISSUE THREAD

**Issue by FduJyy** [hectorqin/reader#85]
首页最上面一行的按钮消失了，如图。
![IMG_0283](https://user-images.githubusercontent.com/16150809/168082105-8340e8e3-2494-4c65-b593-cb1e4ba0ca6e.PNG)

**Comment by Marcotso** [comment]
kindle模式似乎是这样，得进书内修改成正常模式

**Comment by FduJyy** [comment]
> kindle模式似乎是这样，得进书内修改成正常模式

改了确实可以了。

不过在我的理解中kindle模式主要功能应该是黑白主题和去除翻页动画，为什么首页侧边栏会消失也是让人有点

**Comment by hectorqin** [comment]
kindle模式为了节省内存，开启后书架的相关功能都关闭了
