### ISSUE TITLE
希望可以代理到二级目录

### ISSUE THREAD

**Issue by M-HALLIDAY** [hectorqin/reader#87]
因为还安装了其他项目，希望代理能够从一个端口出去，从而达到一个端口访问所有应用的目的。
例如：
https://192.168.20.100:9999/nextcloud    ---访问nextcloud
https://192.168.20.100:9999/gitea    ---访问gitea 
https://192.168.20.100:9999/reader    ---访问reader

这样的话我仅需要在100这台机器上做nginx，即可通过9999这一个端口访问我所有的应用

**Comment by hectorqin** [comment]
自行使用nginx进行反向代理

**Comment by M-HALLIDAY** [comment]
```
    location ^~ /reader {
        proxy_pass http://192.168.20.101:4395/;
    }

    location ^~ /reader3 {
        proxy_pass http://192.168.20.101:4395/reader3/;
    }

    location ^~ /assets {
        proxy_pass http://192.168.20.101:4395/assets/;
    }

```
尝试了一下，需要代理上述上个地方，不知是否有更好的办法来解决这个问题。

```
 'overwritewebroot'  => '/nextcloud',
```
在nextcloud的中，可以通过配置文件来修改根路径，这样所有的请求都挂在/nexcloud下面，从而达到了这个目的。

**Comment by hectorqin** [comment]
以后有时间可以考虑支持一下
