### ISSUE TITLE
点击加载下一章会直接跳转到下一章的末尾

### ISSUE THREAD

**Issue by decexfox** [hectorqin/reader#89]
点击加载下一章，有时候会直接跳转到下一章的末尾，不知道大家遇到过没
![微信图片_20220513084640](https://user-images.githubusercontent.com/40815825/168189741-30e1c1d8-1211-4f0f-b2cb-f16d8ac8952b.png)

**Comment by lmingzhi** [comment]
是有这问题，不知道能否到达一章的底部，自动加载下一章？

**Comment by hectorqin** [comment]
暂时未复现

**Comment by lmingzhi** [comment]
> 暂时未复现

可以试试 we2read.xyz
用户 weread
密码 we2read.xyz

**Comment by decexfox** [comment]
> 暂时未复现

感谢大佬回复，这个问题是在koyeb搭建的阅读使用过程中遇到的问题。railway搭建的已使用一天，也没有这个问题，不清楚是不是服务器的原因

**Comment by lmingzhi** [comment]
会不会是网络丢包造成的？我部署的服务器偶尔会丢包...

**Comment by hectorqin** [comment]
你们不喜欢用左右翻页模式吗？

**Comment by lmingzhi** [comment]
> 试试点击章节进度，然后缓存章节，再看看会不会出现

缓存后还是不行，可以看看bug视频
https://share.weiyun.com/qzl3ZqVC
密码: rlihx7

**Comment by decexfox** [comment]
> > 试试点击章节进度，然后缓存章节，再看看会不会出现
> 
> 缓存后还是不行，可以看看bug视频 https://share.weiyun.com/qzl3ZqVC 密码: rlihx7

和视频现象是一样的，缓存效果需要时间验证，这个现象不是频繁出现，后续会在这里回复效果

**Comment by decexfox** [comment]
> 你们不喜欢用左右翻页模式吗？

哈哈哈，左右翻页感觉读起来不连贯

**Comment by hectorqin** [comment]
我这边测试也没出现过，暂时先放着吧

**Comment by yanglihao347** [comment]
同样的问题，我的复现概率有50%左右，不过我看完这里的回复才知道可以改成左右翻页，所以我就无所谓了，左右翻页好像没这个问题。

**Comment by LifeZero** [comment]
我用腾讯云服务器搭建的，这个问题频繁出现=-=

**Comment by hectorqin** [comment]
试试 Docker 新版看看
