### ISSUE TITLE
希望增加屏蔽触摸层的设置

### ISSUE THREAD

**Issue by letterk** [hectorqin/reader#9]
在pc上手痒鼠标随便点点, 会造成非常多的误操作
还有过滤也是一样, 选择文字就会弹出过滤设置

**Comment by hectorqin** [comment]
选择文字过滤可以考虑加个开关，点击翻页这个熟悉了就好，有显示翻页区域的功能

**Comment by letterk** [comment]
点击翻页也可能增加开关啊, 在pc上一般是不会用点击翻页的, 一个开关切换键鼠和触屏操作

另外, 一些被墙的书源该怎样使用
提示`java.net.SocketTimeoutException: connect timed out`

**Comment by hectorqin** [comment]
那翻页的开关也加一下吧

阅读app支持被墙的书源吗？

**Comment by letterk** [comment]
不支持, 手机上必须通过第三方工具代理
这个书源是可用的, 在app上用了代理就能用

**Comment by hectorqin** [comment]
试试新版本看看

**Comment by hectorqin** [comment]
你没有用docker吗？

**Comment by hectorqin** [comment]
新版本已发布
