### ISSUE TITLE
怎么设置才能自动加载下一章呢？

### ISSUE THREAD

**Issue by xiaohaozifeifeifei** [hectorqin/reader#90]
希望上下滑动时候可以自动加载下一章，不然还要点一下才能加载，增加了阅读舒适性。

**Comment by hectorqin** [comment]
翻页到最后几页的时候会自动加载下一章的

**Comment by lmingzhi** [comment]
最新的docker版(v2.0.0-05120253)好像不行

**Comment by hectorqin** [comment]
你说的自动加载下一章是什么意思？

**Comment by lmingzhi** [comment]
> 你说的自动加载下一章是什么意思？

就是点到本章的最后一页，底部出现"加载下一章"，这时候随不点击屏幕(而是手机向下滑)，是不会自动进入下一章，然后tts有时候也就卡着不进入下一章

自动加载类似于预加载...

**Comment by hectorqin** [comment]
上下翻页模式 暂时没法将下一章内容拼接到上一章的后面，因为章节进度是根据页面滚动条计算的，如果内容拼接了，那么章节进度就没法计算了

**Comment by jorejia** [comment]
滑动党表示这个章节进度好像没有太大意义，或者做成滑到最后再下滑一次进入下一章

**Comment by hectorqin** [comment]
docker新版已支持滚动翻页模式

**Comment by xiaohaozifeifeifei** [comment]
> 

好的，谢谢，我试试
