### ISSUE TITLE
IDEA运行页面访问不了，接口可以调

### ISSUE THREAD

**Issue by VCE-K** [hectorqin/reader#96]
web端 http://localhost:8080/访问显示：Resource not found
接口地址 http://localhost:8080/reader3/任意接口都可以访问
请问是前端页面VUE还需要别的支持才能启动吗？

**Comment by hectorqin** [comment]
需要先执行  `./build.sh yarn sync` 命令来编译web页面

**Comment by Meng-X-G** [comment]
> 需要先执行 `./build.sh yarn sync` 命令来编译web页面

请问怎么才能在windows的IDEA上打包出releases里的那种可以直接运行的jar包呢

**Comment by hectorqin** [comment]
推荐使用脚本 `build.sh`，IDEA没怎么用，不清楚

**Comment by Meng-X-G** [comment]
> 推荐使用脚本 `build.sh`，IDEA没怎么用，不清楚
我就是用build.sh一直报错，所以才问问怎么在windows上打包😂
![image](https://user-images.githubusercontent.com/49837258/169436708-c2d8afca-b807-4189-b937-0a0fb5eb1bd2.png)

**Comment by Meng-X-G** [comment]
找到问题了，Dos和Unix文本类型的问题，我是把项目从windows上传到linux的，所以要把Dos文件格式转成Unix格式
